### ISSUE TITLE
mise en place de mails automatiques de relance utilisateurs sur leur parcours pour leur demander de faire des actions (parcours et timing en réflexion)

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1018]
Objectif : automatiser les relances d'actions que l'on demande à nos utilisateurs qui aujd sont gérées par les biz dévs

ex : 
"relancer un utilisateur qui a créé un compte mais pas de cantine" 
"un utilisateur qui a créé une cantine, mais pas de diag"

première étape : 
faire la config/archi tech pr prévoir cet envoi automatique de mails de relance

(en cours : on réfléchit et on discute d'un parcours, procédure d'envoi tout au long du parcours user)

premier cas d'usage : 

envoi d'un email : 
- aux utilisateurs qui ont un auto-diag avec la case "je suis volontaire à l'expé gaspi alimentaire"
- à T0 + 3 mois (T0 étant la date de mise en place de l'expé que le user a renseignée) envoi de mail automatique "mettez à jour vos données"

**Comment by hfroot** [comment]
Est-ce qu'on a parlé avec les utilisateurs sans cantine/sans diag pour leur demander pourquoi iels n'ont pas poursuivit les prochaines actions ?

**Comment by alemangui** [comment]
Ces emails sont en place. Je me permets de fermer cet issue, quitte à en ouvrir d'autres pour des éventuels ajustements sur la périodicité, le texte, etc.
