### ISSUE TITLE
Début amélioration landing page

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1020]
Merci d'avoir créé cette discussion. 
J'ai l'impression, qu'avant de parler de refonte totale de la landing; on peut déjà continuer le travail que tu avais fait @hfroot en changeant, dans la bannière qui est censée décrire notre mission, changer notre tagline et CTA, avec comme tu dis, en tête, les besoins et bénéfices que l'on apporte aux users. 

Mes propositions : 
**Tagline :** "Mieux manger de la crêche à l’EHPAD" : plus large que l'actuelle tagline qui se focus sur la loi, parle de diagnostic de manière jargonneuse et exclus les convives qui sont un de nos personae importants

**sous-titre :** "ma-cantine accompagne la transition alimentaire de la restauration collective en outillant les gestionnaires afin de fomenter les bonnes pratiques tant en matière de santé que de respect de l’environnement et en informant les convives sur le contenu de leur assiette !"

Là je pense que l'on peut faire mieux niveau rédaction... J'aimerais introduire les deux notions : 
- transparence des assiettes
- si et seulement si on outille les gestionnaires

en lien avec proposition de **CTAs**

1 > Découvrir le réseau de cantines 
qui renvoie vers /nos-cantines

2 > Me créer un compte/m'identifier gestionnaire
qui renvoie vers création de compte

<img width="857" alt="Capture d’écran 2022-02-07 à 13 30 13" src="https://user-images.githubusercontent.com/36134318/152789200-76c6d2cd-8c5c-425e-acf9-ed18ccbd7336.png">

j'embarquerais bien ces premiers changements sur le prochain sprint; mais à discuter niveau évolution /modifs des textes

_Originally posted by @JenniferStephan in https://github.com/betagouv/ma-cantine/discussions/1002#discussioncomment-2125027_

**Comment by JenniferStephan** [comment]
propositions bannières avec des vidéos libres de droit :)
https://www.canva.com/design/DAE4VdqL3Z4/RpDl27lzpQdJ9h4UWF8vrg/view?mode=prototype#untitled-page
@alemangui @hfroot @valeriemerle qu'en pensez-vs ?

**Comment by alemangui** [comment]
CR de la réunion avec Anne-So concernant la landing page : 

### Wording
- Éviter les "je suis" ou "je veux" car difficile de trouver la partie différentiante
- Éviter le jargon pour tout ce qui est à destination des convives. En revanche, le jargon technique peut être utilisé pour les pros (gestionnaires et élus) tant qu'iels soient habitués à ces termes et que les comprennent bien.
- Nos phrases sont trop longues. La landing page n'a pas vocation à être exhaustive car son rôle est d'accrocher et rediriger. Nos phrases doivent être courtes et avec un verbe d'action. L'outil [Hemingway](https://hemingwayapp.com/) indique quand une phrase est trop longue et donc à racourcir (couleurs jaune et rouge). Chaque mot compte.
- Dans la section pour les trois personnas : parler de l'objectif final, par ex privilégier "Étudier l'évolution de votre territoire" plutôt que "Je suis élu/élue"
- Dans la section pour les trois personnas : la phrase et le bouton son redondantes - s'inspirer de [le.taxi](https://le.taxi/) dans lequel on a une carte cliquable sans bouton.
- Prendre en compte qu'on ne lit pas dans l'ordre dans le web. Dans notre cas les gens liront : titre, bouton, texte au milieu.
- Le texte de sous-titre est trop long et comprend des mots un peu compliqués à interpreter (par ex. "fomenter"). Peut-être reformuler en bullet-points très concis comme [le.taxi](https://le.taxi/)
- Les deux boutons principales sont redondants avec ceux dans la section pour les trois personnas. Ça avait du sens à l'époque où on avait une seule personna/proposition de valeur, mais maintenant qu'on en a plus, on peut les enlever (voir [le.taxi](https://hemingwayapp.com/), dans lequel la première partie de leur landing n'a pas des éléments cliquables).

### UI
- On peut utiliser une bordure ou une couleur de fond pour séparer les sections et faciliter la visibilité. Possibilité aussi de faire des cartes pour les trois éléments de la section personnas
- Le sous-titre de la section principale doit avoir une taille de police plus importante que les sous-titres de la section personnas.
- Avoir une vidéo aesthétique de fond n'est pas très intéressante car a) ça n'apporte pas d'info, b) pas top niveau a11y (contrastes changeants, mouvement, distraction), et c) trop de ressources pour pas grand gain (interdit d'ailleurs dans le DSFR par des considérations d'éco-conception et a11y)
- Laisser seulement les actions des trois cartes personnas.

**Comment by alemangui** [comment]
Cette story est maintenant en prod :)
