### ISSUE TITLE
(suivi achats) ajoutant 2 champs : un permettant de renseigner la valeur totale d'achat sur une année (celle en cours) et un champ calculé avec le total des lignes crées

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1023]
<img width="544" alt="Capture d’écran 2022-02-07 à 14 29 55" src="https://user-images.githubusercontent.com/36134318/152797410-9d6d7ad8-62d1-4563-8144-5d114b2537f0.png">

avec contrôle et alert si les deux valeurs ne correspondent pas ?

**Comment by hfroot** [comment]
ancienne idée, je ferme l'issu et si ça revient on le gère avec picardie
