### ISSUE TITLE
no data available

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1037]
Lors d'un webinaire, un problème m'a été remonté par plusieurs utilisateurs lors de l'inscription de leur cantine.
Je joins une capture après essai avec mon propre compte. 
J'ai un navigateur safari, mais ça arrive aussi sur chrome. 
<img width="1208" alt="Capture d’écran 2022-02-09 à 11 07 18" src="https://user-images.githubusercontent.com/85872944/153176677-9e6077b9-f710-4c23-8029-854137a2abe6.png">

**Comment by hfroot** [comment]
`Content Security Policy: The page's settings blocked the loading of a resource at https://api-adresse.data.gouv.fr/search/?q=libou&type=municipality&autocomplete=1 ("connect-src").`
-> on doit ajouter dans settings.py le site
