### ISSUE TITLE
🐛 Ajout de gestionnaire supplémentaire non réalisé

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1100]
Un petit bug technique rapporté par une utilisatrice et testé de mon côté.
J'ajoute un gestionnaire sur mon compte ; je valide. J'ai message pour m'informer que l'ajout est bien réalisé.
Or je ne reçois ni de mail de création du compte, et la demande n'apparait pas en attente (en rouge) dans la partie "gestionnaires".

**Comment by hfroot** [comment]
C'est sur quel navigateur et plateforme ?

**Comment by gauthierandre** [comment]
Pas plus d'info, j'ai posé la question et j'ai pas eu de retours.

**Comment by hfroot** [comment]
Et quand t'as vu ce bug toi-même, quelle plateforme est-ce que t'as utilisé ? Peut-être tu peux me montrer ça demain matin ?

**Comment by gauthierandre** [comment]
Safari; Mais si tu as deux minutes je peux te montrer ça maintenant.

**Comment by hfroot** [comment]
Pour noté ici : On a vu que c'était un pb d'ajouter un adresse qui est déjà dans la liste de gestionnaires, mais le message n'est pas trop clair dans ce cas là. À voir avec l'utilisatrice quel pb elle a vu.

**Comment by gauthierandre** [comment]
Une nouvelle utilisatrice a le même problème. L'utilisateur est bien "invitation en cours" dans la section mais le courriel n'est pas reçu, ni dans les SPAM. Elle utilise google chrome et Mozilla, et utilise parfois un VPN. J'ai pas de capture d'écran.

**Comment by hfroot** [comment]
> Une nouvelle utilisatrice a le même problème. L'utilisateur est bien "invitation en cours" dans la section mais le courriel n'est pas reçu, ni dans les SPAM. Elle utilise google chrome et Mozilla, et utilise parfois un VPN. J'ai pas de capture d'écran.

Dans ce cas tu peux le conseiller de créer un compte de façon normal et on va rechercher si on peut identifier le problème

**Comment by gauthierandre** [comment]
Oui, merci. C'est ce que je l'ai invité à faire. Si tu veux des infos sur l'utilisatrice, on peut en parler sur mattermost.

**Comment by hfroot** [comment]
ancien bug
