### ISSUE TITLE
(landing) ajouter une section "témoignages" / "transparence"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1117]
![illu-home-5-a1a7d3443fec153c7d029505fab674ef13c5fdb8376ca1d3fc13fa3a87102b0b](https://user-images.githubusercontent.com/36134318/155967249-ca906364-87f9-46ee-96a6-c659e2c50b7b.png)
<img width="826" alt="Capture d’écran 2022-02-28 à 11 25 38" src="https://user-images.githubusercontent.com/36134318/155967333-2be758c5-1bbc-4157-aaab-97bc688bce01.png">

"Parcourez les dernières mises à jour 
de nos cantines partenaires "

**Comment by hfroot** [comment]
fait en 2022
