### ISSUE TITLE
UI/UX plusieurs achat par facture

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1166]
![multi-product](https://user-images.githubusercontent.com/9282816/157914120-ab1913ee-9324-4b32-a2d0-aa8afbb0b720.gif)

- [ ] Comment éviter d'avoir trop des champs (par example pour plusieurs produits) active au même temps ?
- [ ] Comment donner l'utilisateur l'option de modifier seulement les détails de la facture ?
- [ ] Est-ce que c'est étonnant de tomber sur une page avec plusieurs produits quand on clique sur seulement un ?

**Comment by hfroot** [comment]
je mets le lien vers cette proposition dans le ticket picardie

**Comment by Tdauvet89** [comment]
Elle est parfaite cette solution de 2022 😅
En effet, de ce que je vois à l'écrans, lorsque le gestionaire clique sur valider et ajouter un nouveau produit, toutes les informations "administratives à savoir la date, la cantine, le fournisseur reste). 

Il faudrait pousser cette solution en prod, soit dans le sprint pro si on veut avoir un petit ticket ou celui d'encore après

**Comment by hfroot** [comment]
Cool que ça réponde au besoin :) le code n'est plus valide, et en tout cas j'ai que créé qqch de front pour experimenter la solution. Il faudrait p-e 3-5 jours pour développer cette solution en vrai avec notre base de code actuel et en design DSFR.

**Comment by Tdauvet89** [comment]
Ok je note dans le ticket qu'il  faut 5 jours, mais pas prio pour le moment
:)
Plutot à partir d'octobre
