### ISSUE TITLE
XP végé

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1205]
<img width="454" alt="Capture d’écran 2022-03-22 à 11 12 13" src="https://user-images.githubusercontent.com/36134318/159457743-658e35f1-a936-4065-af96-c11cc1ae57da.png">

**Comment by hfroot** [comment]
Est-ce qu'il y a plus de contexte pour cet issu ?

**Comment by alemangui** [comment]
Discussion ici : https://github.com/betagouv/ma-cantine/discussions/1228
