### ISSUE TITLE
🐛🧀 Difficulté à valider des achats sur l'outil de suivi. 

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1236]
Quand l'utilisatrice veut ajouter ses fromages, elle se retrouve avec ce message d'erreur.
D'après elle, cela fonctionne parfois.
Ce n'est pas le même bug qu'avec la virgule (même si c'est un nombre décimal, mais même avec le point ça ne marche pas)
Je joins une capture, n'hésitez pas si vous avez besoin de plus.
Navigateur : EDGE
![Capture 1](https://user-images.githubusercontent.com/85872944/160765471-72f31f7c-c94d-4f6e-9772-03d5814af36a.PNG)

**Comment by alemangui** [comment]
Hello, merci pour l'issue. Je vois en effet quelques "Bad Request"s dans les logs, on investigue.

**Comment by hfroot** [comment]
ancien bug
