### ISSUE TITLE
"No data available" texte en placeholder à changer

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#1246]
"No data available" est affiché lors de la sélection d'une ville (création cantine) avant qu'on tape quelque chose.

À remplacer par "Renseignez votre ville"

![image](https://user-images.githubusercontent.com/1225929/161512236-0eddd661-b637-49df-bba4-f47146f9c8c9.png)

**Comment by hfroot** [comment]
On peut aussi juste supprimer le menu quand il y a pas de données: https://vuetifyjs.com/en/api/v-combobox/#props-hide-no-data
