### ISSUE TITLE
Envoi automatique d'email

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#1256]

**Comment by gauthierandre** [comment]
A/ CREATION CANTINE : 
Scénario 1 : 
condition : si création d'un compte utilisateur et rien d'autre
> effet : **une semaine après la création email CREATION CANTINE** (ex: vous pouvez ajouter votre cantine) ; 
condition : si une semaine après pas de création de cantine
> effet : email de relance 1 CREATION CANTINE 
(à valider) : condition si une semaine après le dernier mail, toujours pas de création de cantine : 
> effet : email de relance 2 CREATION CANTINE 

Scenario 2 
condition : création d'une cantine après premier mail mais pas de diagnostic 
> effet : **email DIAGNOSTIC**
condition : si une semaine après le précédent mail, pas de création de diagnostic : 
> effet : **email DIAGNOSTIC relance 1**

Scenario 3 : 
condition : création d'une cantine et d'un diagnostic après les scénarios précédents
> effet : **email PUBLICATION**
condition : création d'une cantine, et d'un diagnostic mais pas de publication une semaine après le mail précédent
> effet : **email PUBLICATION relance 1**

**Comment by gauthierandre** [comment]
C/ CREATION PUBLICATION :
Scénario 1 :
* condition : si création d'un compte utilisateur, d'une cantine, d'un diagnostic mais sans publication
effet : une semaine après email PUBLICATION (ex: communiquez avec vos convives) ;
* condition : si une semaine après pas de création de diagnostic
effet : **email de relance 1 PUBLICATION **
* (à valider) : condition si une semaine après le dernier mail, toujours pas de création de cantine :
effet : **email de relance 2 PUBLICATION**

**Comment by gauthierandre** [comment]
J'ajoute les emails plus tard.

**Comment by hfroot** [comment]
Merci ! 
Questions :
1. Si un utilisateur a quelques cantines (quelques sans diagnostic, quelques avec mais pas publiées) est-ce que tu es d'acc qu'on veut seulement envoyer un mail pour ne pas spammer la personne ?
1.a. Si oui, quel mail est-ce que tu veux prioritiser ? CREATION DIAGNOSTIC ou PUBLICATION ?
2. Est-ce que on veut avoir un minimum de données renseignées pour le mail PUBLICATION ?

**Comment by gauthierandre** [comment]
@JenniferStephan @valeriemerle
