### ISSUE TITLE
ajouter une meta image / meta description  lors du partage du lien du site

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1281]
contexte : 
lorsque l'on partage le lien de ma-cantine, on a pas d'image : 
<img width="529" alt="Capture d’écran 2022-04-12 à 11 57 54" src="https://user-images.githubusercontent.com/36134318/162936153-5597172f-3943-4fc8-8619-eec1b60d9dac.png">

<img width="490" alt="Capture d’écran 2022-04-12 à 11 56 56" src="https://user-images.githubusercontent.com/36134318/162936320-c852dd13-12c6-47fb-b37a-7e33456e6745.png">

proposition : 
![metaimage_ma-cantine](https://user-images.githubusercontent.com/36134318/162935765-c6d7dff2-df32-4922-b908-d7210c10bf7c.png)

**Comment by hfroot** [comment]
https://github.com/betagouv/ma-cantine/pull/1333
