### ISSUE TITLE
Ajouter un champ ds le modèle user "comment avez-vous connu ma-cantine ?" optionnel

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1284]
Comment avez-vous connu ma-cantine ? pr le compte user

options : 
- Webinaire
- Recherche web
- Communication institutionnelle (DRAAF, association régionale)
- Bouche à oreille
- Réseaux sociaux
- Autre

**Comment by hfroot** [comment]
Même design que champ fonction mais afficher quand l'utilisateur n'a pas des infos d'un lien tracking, quand ils ont créé au moins une cantine
