### ISSUE TITLE
[retours staging] encart newsletter

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#132]
- [x] mettre le titre en plus gros et remplacer par "Suivre les actualités du site ma cantine"
- [x] l'input et le bouton se chevauchent bizarrement on peut p-e les mettre l'un au dessus de l'autre ? 
- [x] sur mobile, le bouton flotte et empiète sur le footer

**Comment by Forster-Groux** [comment]
J'ai pas compris "l'input et le bouton se chevauchent bizarrement on peut p-e les mettre l'un au dessus de l'autre ?" possible d'avoir plus de détails ?
