### ISSUE TITLE
[retours staging] affiche

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#133]
- [x] BUG dans la génération d'affiche, j'ai un espace plan quand je génère mon pdf en premiere partie d'affiche
- [ ] faire des inputs qui prennent la taille du contenu ? qui suivent la complétion du contenu en s'agrandissant
- [ ] inverser les couleurs sous les inputs. mettre en surbrillance orange foncé quand besoin de remplir 
- [x] harmoniser les espaces entre les lignes de texte dans le formulaire
- [x] sur l'affiche, ajouter les images des logos en liste sous le "% de produits durables"
- [x] typo : "la commune" à la place de "le commune" 
- [x] remplacer le placeholder "Plouer-sur-Rance" par "nom de la commune" et "nom de l'école" par "nom de l'établissement"
- [x] ajouter un sous-titre "En remplissant ce formulaire, vous pourrez générer un pdf à afficher ou à envoyer par mail à vos convives. Cette affiche présente vos données d'achats à vos convives comme demandé par une sous-mesure de la loi EGAlim. En savoir plus sur cette mesure (en lien de la mesure)"

**Comment by Forster-Groux** [comment]
J'ai pas compris "inverser les couleurs sous les inputs. mettre en surbrillance orange foncé quand besoin de remplir", tu veux inverser quoi et quoi ?

**Comment by JenniferStephan** [comment]
ajouter bloc mesure appro avec le texte pour expliquer les objectifs

**Comment by JenniferStephan** [comment]
- [ ] dans les achats, mettre le placeholder 15000 à 70000 euros plutôt et pour le bio "14000" et "21000" pour le durable; pour commerce equitable "3500"
