### ISSUE TITLE
ajouter un "votre avis"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1354]
<img width="473" alt="Capture d’écran 2022-05-03 à 11 12 00" src="https://user-images.githubusercontent.com/36134318/166429598-73fcf5c5-5e8a-43a0-9acf-dd3dcc0bc7b5.png">

**Comment by JenniferStephan** [comment]
premier outil partagé par la commu beta, qui ressemble de ouf : https://www.hotjar.com/product/feedback/

**Comment by alemangui** [comment]
Le seul souci (à vérifier avec Thomas M) c'est qu'il faudra une bannière de cookies si on ajoute hotjar :(

**Comment by JenniferStephan** [comment]
on peut faire un truc comme sur mon-entreprise un truc in-house : 

- [ ] un NPS type étoile 
- [ ] ouverture d'un champ libre "votre avis nous intéresse"

<img width="1273" alt="Capture d’écran 2022-05-17 à 10 41 56" src="https://user-images.githubusercontent.com/36134318/168769637-f7a7951e-6ace-4ad5-9753-a25748bb681d.png">

<img width="583" alt="Capture d’écran 2022-05-13 à 11 43 10" src="https://user-images.githubusercontent.com/36134318/168769813-63e99345-5c92-4b09-a943-46711139c08d.png">
<img width="623" alt="Capture d’écran 2022-05-13 à 11 43 16" src="https://user-images.githubusercontent.com/36134318/168769832-7cc6b32f-3927-47f1-bf96-8af974814ac0.png">

s'affiche à la création d'une cantine et auto-diag
s'il répond à la création d'une cantine; alors on le remet sur l'autodiag
sinon, on le laisse sur les 2

**Comment by alemangui** [comment]
Slides par ici : https://docs.google.com/presentation/d/185FVt22qHfcvEYtck0MQnhWllwbdD0F1ZsmtoZ7cqFc/edit?usp=sharing
