### ISSUE TITLE
Question activation badge

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1356]
Un utilisateur qui a rempli la quasi intégralité tout son diagnostic sur la diversification des sources de protéines et menu végé ne voit pas le badge correspondant sur la page de sa cantine publiée. Est-ce normal ?

Le cantine en question : https://ma-cantine.beta.gouv.fr/nos-cantines/40--Restaurant%20Interadministratif%20de%20Lyon

En back office : 
<img width="952" alt="Capture d’écran 2022-05-04 à 14 52 35" src="https://user-images.githubusercontent.com/85872944/166684944-9de08fe7-39d7-4983-8a19-364a2e479fe9.png">
C'est le diagnostic de 2022 mais il est identique de 2020 à 2022.

**Comment by hfroot** [comment]
selon [ces règles](https://jennstephan.notion.site/jennstephan/df398fe4dd0440e69de2037e80ce6b81?v=c87ac75bb3ef444d95ddd4a30b3d5dd1), les etablissements hors du scolaire ont besoin d'offrir un menu végé par jour

**Comment by gauthierandre** [comment]
Meri @hfroot pour la réponse ! 
Je n'ai pas vu l'information passer.

Je me demande si on ne peut pas alléger l'activation du badge végé pour les secteurs hors administration car à part l'école où le plat végétarien quotidien est en expérimentation + l'administration où il sera obligatoire, tous les autres secteurs ne sont pas encore concernés. (j'ai eu deux trois questions encore à ce sujet).

**Comment by valeriemerle** [comment]
Est ce que dans l’activation du badge on prend en compte le fait que l'utilisateur a mis en place un plan de diversification? La règle doit effectivement tenir compte du secteur car l'obligation du menu vege n'est faite qu'aux scolaires (primaire jusqu'au lycée) quant à l'obligation quotidienne elle ne sera en place qu'en 2023 pour l'administration donc pas possible de prendre en compte ce critère dans la règle d'attribution des badges.

**Comment by JenniferStephan** [comment]
mais est-ce qu'on ne veut pas justement, avec les badges, ne pas se cantonner aux objectifs réglementaires mais décider entre ns de règles qui font qu'on considère qu'un établissement joue le jeu ou pas ? 
une option de menu végé ds un établissement me parait être une condition sine qua none pr avoir le badge "végé" non ?

**Comment by gauthierandre** [comment]
Ouais, je vois ce que tu veux dire. 
Si on reste sur cette piste, c'est quelque chose qu'il faudrait préciser aux users, j'ai eu quelques remarques (pas en masses non plus) qui ne comprenaient pas forcément pourquoi ils n'avaient pas le badge tout en cochant toutes les cases (sauf repas quotidien).

**Comment by hfroot** [comment]
ancien pb, si c'est remonté encore on peut le traiter avec un nouveau issu
