### ISSUE TITLE
[retours staging] les 5 mesures

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#138]
- [x] enlever le diagnostic dans la page "5 mesures-phares"
- [x] enlever "tableau de bord" ou remplacer par un "toutes les mesures"
- [x] remplacer "Voir un exemple d’affiche (à venir)" par la section rose "pour generer son affiche..." comme à la fin du diagnostic

**Comment by hfroot** [comment]
Qu'est-ce que ça veut dire "enlever le diagnostic dans la page "5 mesures-phares"" ?

**Comment by JenniferStephan** [comment]
à discuter avec Valérie, mais ça serait = "enlever les boutons "fait"/"programmé"/"à faire" dans la page d'affichage des 5 mesures-phare
