### ISSUE TITLE
sur l'inscription compte, ajouter un texte explicitant que la prochaine page c'est la création de la cantine !

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1387]
proposition : Préciser en amont qu’il faut se munir du numéro de SIREN de la cantine “pour continuer munissez-vous du numero de SIREN de votre organisation”

**Comment by alemangui** [comment]
C'est fait :+1: https://ma-cantine.beta.gouv.fr/creer-mon-compte
