### ISSUE TITLE
Mes Achats comptabilise les produits locaux dans la catégorie EGalim?

### ISSUE THREAD

**Issue by YodBetYod** [betagouv/ma-cantine#1392]
Une utilisatrice m'a fait remarquer que le montant des "produits de qualité et durable" qui s'affiche dans son diagnostic 2021 inclut ses achats de produits qui ont l'appellation "produit local", "provenance France" et "circuit court". Or elle a saisi toutes ses factures sur Mes Achats. Donc Mes Achats doit vraisemblablement comptabiliser, à tort, dans la catégorie "produits de qualité et durables" tous les produits locaux.

@alemangui, @hfroot, @JenniferStephan, est-ce bien le cas?

<img width="444" alt="Capture d’écran 2022-05-12 à 14 52 27" src="https://user-images.githubusercontent.com/93709421/168082137-ce09d3a9-7cdb-4359-9869-4e476976f392.png">
<img width="831" alt="Capture d’écran 2022-05-12 à 14 58 52" src="https://user-images.githubusercontent.com/93709421/168082143-93520fe9-5abc-4951-964b-dfed46fc35f9.png">
<img width="218" alt="Capture d’écran 2022-05-12 à 14 58 54" src="https://user-images.githubusercontent.com/93709421/168082149-d102b56e-0f2b-4d9d-98e8-53c963a30631.png">

**Comment by alemangui** [comment]
Effectivement ils sont comptabilisés. Faites-nous signe si ceci n'est pas correct et on fera le changement si besoin d'ignorer "produit local", "provenance France" et "circuit court"

**Comment by YodBetYod** [comment]
@valeriemerle, as-tu des infos à ce sujet? (Je t'identifie car l'utilisatrice m'a relancé à ce sujet.)
