### ISSUE TITLE
Editorialisation de la page stats

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1412]
### Discussed in https://github.com/betagouv/ma-cantine/discussions/1366

<div type='discussions-op-text'>

<sup>Originally posted by **JenniferStephan** May  9, 2022</sup>
objectif :  fournir en indicateurs clés la page stats actuelles; en ajoutant du texte et en contextualisation les graphes metabase actuels

proposition en cours : https://www.figma.com/file/Wy0JohuTd3zP9fTGERs5qq/Egalim-nouveauparcours?node-id=12%3A123</div>

**Comment by JenniferStephan** [comment]
### Proposition d’indicateurs pr une page /stats avec des graphes et visualisation de metabase embed

1. **Acquisition croissante d’utilisateurs**

Nb de cantines totales inscrites

Cantines par dpt - répartition sur carte

% de croissance du nb total de cantines inscrites par sem

(diagramme en barre) Evolution par mois du nb d’inscription de cantines

Diagramme avec répartition par type de production (site, satellite, centrale, centrale avec service sur place)

Répartition par secteur (en catégorie, pas name)

Type de gestion des cantines (camembert concédée et directe)

Tunnel depuis creation de cantines > diag 2021 > publi > TD

1. **Evolution des pratiques**

Appro : 

évolution part de bio ds le secteur scolaire par an

évolution part de bio ds le secteur admin par an

évolution part de bio ds le secteur health + social par an

SUR LA TOTALITE DES DIAGS SIMPLES : 

évolution part d’EGAlim (SIQO, critères d’achat, autres) ds le secteur scolaire par an

évolution part de bio ds le secteur admin par an

évolution part de bio ds le secteur health + social par an

PLASTIQUES : 

Nb de cantines qui ont supprimé tous les plastiques (donc qui ont coché les quatre cases)

DIVERSIVERSIFICATION : 

nb de participation expé végé

plan de diversification en place

nb de cantines par fréquence de menu végé en place (4 options : moins d’une…)

GASPI : 

nb de participation expé solution de repas

sur les types d’actions mises en oeuvre contre le gaspillage

1. **moyens et outils pour l’amélioration :** 

Nb d’affiches générées sur le site

Nb de cantines utilisateurices

**Comment by valeriemerle** [comment]
indicateur cantine inscrite = compte créé ou cantines crées?
évolution part de bio ds le secteur health + social par an : separer le secteur santé et le secteur medico social?
On peut rajouter 
Nombre de cantine utilisant l'outil de saisie en ligne
Nombre de publication : avec données appro, sans aucune info (pour le suivi des coquilles vides? )
Nombre de cantine ayant télédeclarée en 2021/ nombre total de teledeclaration (pour inclure les autres années?)

On peut aussi penser à editorialiser les chiffres affichés sur carte publi (demande des DRAAF)?

**Comment by hfroot** [comment]
https://github.com/betagouv/ma-cantine/pull/1974
