### ISSUE TITLE
Page - webinaire

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1442]
https://www.figma.com/file/Wy0JohuTd3zP9fTGERs5qq/Egalim-nouveauparcours?node-id=12%3A123

<img width="617" alt="Capture d’écran 2022-05-27 à 16 46 55" src="https://user-images.githubusercontent.com/36134318/170723322-08cf7f46-86d7-407d-8244-56e8f07c61d9.png">
<img width="606" alt="Capture d’écran 2022-05-27 à 16 47 03" src="https://user-images.githubusercontent.com/36134318/170723348-a255ca70-f0a8-4a41-83ac-4d6dfaa51bcc.png">
<img width="607" alt="Capture d’écran 2022-05-27 à 16 47 08" src="https://user-images.githubusercontent.com/36134318/170723373-93b1324b-b158-4a53-8a21-cf974c1942de.png">

**Comment by JenniferStephan** [comment]
to do 

- [ ] page spécifique webinaire avec titre webinaire, description, noms des intervenant.e.s, date et heure, lieu ou visio, lien d'inscription
- [ ] sur l'admin, permettre aux membres de l"équipe de créer eux-mêmes des encarts webinaires
- [ ] espace des replays des anciens webinaires
- [ ] encart d'inscription à la newsletter pr recevoir toutes les nouvelles modifs d'évents et rencontres


nice to have : 

- [ ] création d'une communauté FB et lien pr s'inscrire au groupe
- [ ] encart pour ns écrire et proposer des sujets de webinaires

**Comment by JenniferStephan** [comment]
vu en planif : 

on fait petit à petit la page webinaire : 
1. cartels avec affichages des webinaires à venir
2. bouton vers gitbook des replays
3. FAQ

puis on gère la bannière d'annonce des prochains webinaires

**Comment by alemangui** [comment]
@hfroot, ce qu'on a discuté ce matin : 
- Ajout d'une image dans le modèle _webinaire_ avec la logique de compression présente dans le modèle `canteen.py`
- API qui renvoie les webinaires dans le futur (et non pas les passés)
- Éventuellement dans une deuxième PR si pas le temps : possibilité d'ajouter plusieurs auteur.rice.s avec nom, titre/post, et photo 

Et le diagramme pour le header ci dessous. Une idée serait de mettre l'ID du dernier webinaire lors que l'utilisateur a fermé la bannière comme valeur du cookie .

![image](https://user-images.githubusercontent.com/1225929/171360019-e654f46c-25b1-4fa3-964c-db40b3bf6313.png)

**Comment by JenniferStephan** [comment]
https://ma-cantine-1.gitbook.io/ma-cantine-egalim/webinaires-les-defis-de-ma-cantine @hfroot 
liens replays

**Comment by hfroot** [comment]
@JenniferStephan suggestions suite à tes commentaires
![Screenshot 2022-06-08 at 11 42 23](https://user-images.githubusercontent.com/9282816/172585925-efcd48bc-6ccf-4a47-9273-b3e87fc4bc36.png)
![Screenshot 2022-06-08 at 11 41 03](https://user-images.githubusercontent.com/9282816/172585677-5a26b315-1c0e-434b-a1a3-58153084bb27.png)
![Screenshot 2022-06-08 at 11 36 53](https://user-images.githubusercontent.com/9282816/172585703-54de3bd4-2ea9-43b4-b5f7-052d6eeed495.png)

**Comment by JenniferStephan** [comment]
fan de la proposition 2 avec le background vert !!! @hfroot
