### ISSUE TITLE
A11y revue juin 2022

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1458]
# A11y review

J'ai fait un revue avec WAVE

Actuellement 91 % sur les choses qui peuvent être testées automatiquement https://dashlord.incubateur.net/report/aHR0cHM6Ly9tYS1jYW50aW5lLmJldGEuZ291di5mcg==/lhr.html#accessibility

### Landing page - connected

WAVE : 6 errors, 1 contrast error, 9 alerts

- [x] Banner needs fixing for close button and constrast on m'inscrire
- [x] Banner close to be accessible by tabbing once (not twice)

 Blog link appears twice

 PDF link

 5 x underlined text - ignore b/c on linked card

 Video

 Objectifs, Measures phares cards, latest blog posts, tools to be lists ?

- [ ] Blog cards have two tab actions when ideally have one ?

 Tab order looks good

### Landing page - not connected

- [ ] gerer card doesn't indicate popup + dialog not keyboard accessible
- [ ] are screen captures alt texted?
- [ ] need to be able to close dialog with keyboard
- [ ] nos partenaires links empty
- [x] header menu link empty

### Mes cantines

Tab order looks good even with satisfaction + dialog. Stars highlighting when tabbing not super evident - is this a problem ?

- [ ] Bug : if use search bar and get fewer than 5 results, search bar disappears
- [ ] Canteens to be unordered list?

#### Ajouter une cantine

- [ ] SIRET loading dialog breaks tab order
- [ ] Should side menu be skippable ? Do use a navigation element
- [ ] Why does the same city name get added to the city list lots of times?
- [ ] Ajouter un logo, nothing happens on press enter
- [ ] Form labels missing
- [ ] Broken ARIA references on radios
- [ ] Orphaned form label for images
- [ ] Missing fieldset alert on radios 

 Tab order otherwise decent

#### Importer diags/cantines

(when upload file get success message/error table listing)

- [ ] Lots of links to excel sheets/docs
- [ ] Video
- [ ] More tabbing than required in file upload ?
- [ ] Bug : add more space between errors and video

#### Diagnostics

Tab order looks good with ajouter, some diag cards, satisfaction

- [x] Low contrast for year on diag cards

#### Ajouter un diag

- [x] Missing form labels for label specific appro
- [ ] Missing form label for other text box when given with checkbox in list e.g. infos
- [x] XP headers to be actual HTML headers ?
- [x] Info link to comms doesn't have label
- [ ] Waste XP: date orphaned label
- [x] XPs : headings for tabbed TN content contrast errors
- [ ] Bug : UI gives option to teledeclare before saving officially. If attempt to do so, get error message, diag gets saved, teledeclaration does not. Probably should save + teledeclare + success message.

 Alert : XPs have links to PDFs

 Tab order good

#### Modif un diag

(teledeclaration)

#### Publication

- [ ] Preview : broken ARIA reference for graph
- [ ] Preview : alert - redundant title text
- [ ] Preview : should fermer be after preview content?

 Tab order good

#### Gestionnaires

Tab order good

- [ ] Empty button to delete gestionnaire
- [ ] Enter when adding invalid gestionnaire - not sure the error is clear to screenreaders?

#### Supprimer

- [x] Low contrast button text

Tab order good

### Mes achats

Tab order (almost) good

- [ ] Empty table header (should be td not th if needed) - attachment indicator column
- [ ] Bug : refresh with category filter set - breaks
- [ ] Table elements not accessible by keybaord
- [ ] Aria label for attachment is in english (Has invoice file) - should be in French

#### Ajouter + modifier un produit

- [ ] Minor preference for tab to go to facture after date rather than after category
- [ ] Is there a form element on this page?

Tab order good

### Generer mon affiche

- [ ] Tabs to go through all form elements before generer button?
- [ ] Question placement of generer button
- [ ] Redudant title text on logo images. Don't need title and alt?
- [ ] Should QR code be more clearly indicated?

### Mon compte, MDP, supprimer

- [x] missing form label x 10
- [x] No h1
- [x] page title (for tab) not specified

Tab order good

### Mesures phares

- [ ] Page tabs should be nav element?

#### Appro

- [ ] secocnd example graphs have same alt text as previous
- [ ] redundant title text x 9
- [ ] redundant link (probs fine, link to blog twice but far away)
- [ ] redundant alt text
- [ ] PDF link
- [ ] Are the graphs sufficiently represented with title + alt ?

 tab order good

#### Gaspi

- [ ] Bug : both resources are blue ?

#### Diversification

- [ ] Bug : both resources are green ?
- [ ] Suggestion : put resources inline with relevant sections

#### Plastiques

No plastic help?

#### Info

Good

### Nos cantines

(Cartes, filtres)

- [ ] Missing labels for bio and durable filter mins
- [ ] Should cards be a list?
- [ ] Should card titles be headings? For quicker scanning
- [ ] bug on card showing "en 2021" but no data except badges

tab good 

#### Une cantine publiée

(Cantine logo, infos, contactez nous, dans les assiettes, badges, mot du gest, Evolution, galerie, formulaire)

- [ ] Is graph good enough ?
- [ ] Are badges good enough ?
- [ ] is page heading structure good? Mayb

### Blog

best to test prod?
(carte + labels, filter)

- [ ] cards as list ?
- [ ] cards double tab

 tabbing good

#### Article

Seems fine - very content dependent

### Statistiques regionales

- [ ] logos have redudant title text
- [ ] are graphs good enough ?
- [ ] how to improve 'la mesure' links with more descriptive yet still concise text?

tabbing good

### Contactez-nous

good

### Mentions legales

- [ ] missing alt text on cookie (or rather alt="")
- [ ] redundant link?
- [ ] page title (for tab) not specified

### CGU

- [ ] redundant links

### Politique de conf

fine

### Accessibilité

fine

### Not found

- [ ] no heading
- [ ] page title (for tab) not specified

### Auth

- [ ] remove hat logo

#### Log in

- [ ] creer mon compte double tab ?

#### Create account

- [ ] deja mon compte double tab ?
- [ ] crisp not keybaord accessible

etc otherwise fine

## Componants

- [ ] Date not enterable by keyboard?
- [ ] Radio groups appear to have broken ARIA references
- [ ] Ratings have orphaned labels
- [ ] Should ratings have the same structure as radio groups?
- [ ] Videos : Video content with audio must have synchronized captions and a transcript. Audio-only content must have a transcript.
- [ ] How does error/success temp message fair ? Top right hand corner
- [ ] Are form validation errors accessible ?
- [ ] Pagination : should content displayed be a list? Ordered or unordered?

### Header

- [ ] Empty link
- [ ] Broken ARIA menu (sometimes?)

## Questions

What do we need to do for videos ? x2

What to do about downloadable tools in PDF or excel format?

How does it work when we get assessed on a particular state of the website, and then we add/change things ?

**Comment by hfroot** [comment]
CR Réu avec Anne-So 9/6
Presentation programme Accès
Audit de conformité : fait par n'importe qui mais en pratique on paye des gens qui prends 5 jours en le faire
- on identifie des pages clés, verifie 50 mesures sur ces pages
- alors on a un score final qu'on peut utiliser pour la notif d'a11y
- programme acces aide a corriger des choses avant l'audit pour etre plus pret et avoir un mieuller score

Questions de A-S
- Est-ce qu'on a un contraint de temps ? @JenniferStephan pour confirmer
- Les pages pertinante (pas chaque pas cantine publiée par ex, une seulement) ? Nous a la donner
- A-S va presenter un livrable à la fin, avec les choses bonnes, bloquantes, genantes.

**Comment by JenniferStephan** [comment]
Pr la contrainte de temps : à confirmer demain en point de coordination
mais au moins de mettre la mention « partiellement conforme » suite à
l’audit ns permet d’activer une communication plus institutionnelle via la
DICOM du ministère - ce qui est notre objectif à moyen terme pr accroître
visibilité et sensibilisation !

Suite aux livrables de Anne-So du coup on pourra directement prendre des
actions ? Avant l’audit ?

L’audit peut se faire avec un membre de beta gouv ou y’a des organismes
certifiés pr ça ?

**Comment by hfroot** [comment]
@JenniferStephan oui, après les livrables de Anne-So on pourra améliorer le site avant l'audit officiel pour atteindre un meilleur score. L'audit est fait je pense par qqn hors de beta, avec de l'expertise de ça

**Comment by hfroot** [comment]
@alemangui je propose que les suivantes sont les pages pertinantes:

https://ma-cantine-demo.cleverapps.io/accueil
https://ma-cantine-demo.cleverapps.io/statistiques-regionales
https://ma-cantine-demo.cleverapps.io/nos-cantines/?page=1&trier=creationCro
https://ma-cantine-demo.cleverapps.io/nos-cantines/3--%C3%89douard%20Herriot
https://ma-cantine-demo.cleverapps.io/mesures-phares/qualite-des-produits
https://ma-cantine-demo.cleverapps.io/diagnostic (seulement dispo quand pas connectée)

Authentification nécessaire:
https://ma-cantine-demo.cleverapps.io/gestion?cantinePage=1
https://ma-cantine-demo.cleverapps.io/creation-affiche
https://ma-cantine-demo.cleverapps.io/mes-achats?page=1
Modifier ma cantine
Modifier mon diagnostic (pour 2021 pour avoir l'aspect teledeclaration)
Gestionnaires

Tu penses quoi ?

Je pense que les suivantes sont utilisées mais les composants sont tous utilisés dans les pages en-dessus déjà
Mon compte/MDP/Supprimer
Modifier ma cantine -> publication
Ajouter/modifier un achat
Les autres pages mesures phares
BlogsHome
Contactez-nous
Page webinaires
Page recapitualif diagnostic sans connexion

**Comment by hfroot** [comment]
Email envoyé avec ces ajouts, merci :)

**Comment by JenniferStephan** [comment]
Demande de Anne-So : https://docs.google.com/presentation/d/1u292vEbvDydpA5wQTEtgNI_ZWBPUTSdamPKnM0A9yBo/edit#slide=id.g1360c9856cd_0_120

**Comment by hfroot** [comment]
Resultat flash audit : https://hellobokeh.notion.site/MaCantine-9cf4cfaf6e8c4ea1ae9367af71a7d27a
Je vais créer des cartes specifiques alors je ferme cette carte
