### ISSUE TITLE
sur une cantine publiée, qui n'a pas de gestionnaire; afficher "revendiquer cet établissement"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1462]
le fait de créer/publier une coquille vide de cantine et de permettre à n'importe qui de se réclamer "gestionnaire" (un sas qui passerait par nous, nous permettrait de valider ou pas la demande de gestion de l'établissement)
<img width="1012" alt="Capture d’écran 2022-06-02 à 10 31 16" src="https://user-images.githubusercontent.com/36134318/171649465-ba06b808-3f74-4f50-9c6a-644c68fd11d2.png">

Cet établissement n’a pas de gestionnaire associé ? c’est votre établissement ? 
Inscrivez-vous en tant qu’administrateur du restaurant (CHAMP PERSONNALISÉ)

**Comment by hfroot** [comment]
@JenniferStephan Tu penses quoi de :

Quand la personne n'est pas connectée, afficher 

>"Vous êtes un membre de l'équipe de gestionnaires de cette cantine ? Inscrivez- ou connectez-vous pour demander les droits de mettre à jour ses données. <Bouton 'Modifier cet établissement'>"

Le bouton dirige la personne vers la page d'inscription, et après elle est retournée vers cette page où il y a maintenant

>"Vous êtes un membre de l'équipe de gestionnaires de cette cantine ? Demandez accès de mettre ses données à jour <Bouton 'Demandez accès'>"

Ce bouton envoie un demande vers notre équipe comme normal.

Ces additions sont affichées sur toutes les pages de cantines publiées sans gestionnaires. Comme ça qqn pourrait demander accès aux plusieurs cantines si jamais il y a besoin.

D'ailleurs p-e ça serait utile si on sauvegarde sur le compte créé qu'il vient d'une cantine publiée

**Comment by alemangui** [comment]
En prod :)
