### ISSUE TITLE
Blog / espace témoignages

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#150]
exemple editable directement en markdown pour que l'on puisse etre autonomes avec Valerie : https://datagir.ademe.fr/blog

**Comment by JenniferStephan** [comment]
premier article du blog par exemple : 
1. UNE FAQ foire aux questions sur la loi et sur la plateforme : 

- [ ] D'où vient cette loi ? explication du contexte
- [ ] Pourquoi suivre mes achats et mes approvisionnements ? Comment le faire ? A quelle échéance ?
- [ ] Quels labels rentrent dans les 50% ? 
- [ ] Pourquoi le local ne rentre pas dans les 50% de produits durables ? 
- [ ] Pourquoi la plateforme ne s'adresse qu'aux cantines scolaires ? 
- [ ] Comment devenir testeureuses de cette plateforme ?

**Comment by hfroot** [comment]
Coté technique: je pense qu'on peut faire qqch [comme ça](https://stackoverflow.com/questions/54009901/retrieve-content-from-markdown-file-and-convert-it-to-valid-html-code-in-vuejs).

**Comment by hfroot** [comment]
@JenniferStephan est-ce que tu as un fichier markdown avec cette FAQ ?
