### ISSUE TITLE
pour les 2 options "cuisine centrales"; suivant le nb XX de satellites remplis : ouvrir XX lignes avec "secteur" "nb de couvertsmoy" pr chaque satellite

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1510]
<img width="628" alt="Capture d’écran 2022-06-13 à 21 38 38" src="https://user-images.githubusercontent.com/36134318/173431592-01ae1b6f-7799-4acf-9dd6-17737137da8c.png">

**Comment by hfroot** [comment]
Pour la teled de 2021, les cuisines centrales ont l'option de teled. pour ces satellites. Mais les convives sont interessés des données par satellite.
Après, on demandera quelques cuisines centrales et leurs satellites de nous confirmer leurs chiffres pour voir le marge d'erreur d'un split auto basé sur le nb de couverts. Comme ça on verra si on veut mieux soutenir l'affichage de ces données aux convives.
(jan 2023 we will need to change the teledeclaration to be n-2)

- SIRET, secteur (pour avoir une visibilité sur le marge d'erreur du split), nb couverts (tous obligatoires)
- ajout de champ pour SIRET cuisine centrale pr deuxième réponse
- ...

**Comment by hfroot** [comment]
Fait : 
- [x] possible de créer plusieurs satellites depuis la page nouvelle/modifier ma cantine
- [x] possible de voir la liste des satellites depuis la même page 
- [x] champ pour siret de la cuisine centrale pour les satellites

Restant :
- [ ] gestion du cas où le siret rentré existe déjà en tant que cantine dans notre BDD
- [ ] validation de sirets rentrés (pas des dupliqués, pas le même que la cantine centrale)
- [ ] gestion des erreurs (quand les données sont mal rentrées etc)
- [ ] pas d'option d'ajouter la localisation du satellite
- [ ] preremplir les champs nom et localisation du satellite avec le SIRET

![Screenshot from 2022-07-03 21-11-12](https://user-images.githubusercontent.com/9282816/177054171-4f556971-4b94-4591-8ca2-c7e7c735cd9c.png)
![Screenshot from 2022-07-03 21-11-28](https://user-images.githubusercontent.com/9282816/177054169-3cabfb06-1f91-4d4f-9e8a-8ef6a29852e3.png)
