### ISSUE TITLE
(landing) ajouter une section "outils et ressources"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1513]
<img width="855" alt="Capture d’écran 2022-06-13 à 21 45 09" src="https://user-images.githubusercontent.com/36134318/173433160-fa189ddd-1ecb-4b8d-9057-8e31dad2a133.png">

**Comment by hfroot** [comment]
On a déjà la dialog quand on n'est pas connectée (en cliquant sur la carte gestionnaire) - tu veux ça en plus ou pour le remplacer ?
