### ISSUE TITLE
Retours page 'améliorer ma cantine'

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1546]
- [ ] Besoin d'un titre de l'onglet

**Comment by gauthierandre** [comment]
* sur la page de publication, avec l'adaptation des seuils outre-mer : 
Le texte du badge est toujours celui-ci : "Ce qui est servi dans les assiettes est au moins à 20% bio et à 30% de produits durables et de qualité.".  

On pourrait modifier en "Ce qui est servi dans les assiettes respecte les seuils EGAlim adaptés pour les territoires d'Outre-mer" (@valeriemerle, peut-être qu'on peut le dire autrement). Et mettre un lien vers cet article qui détaille tous les seuils et les étapes : https://ma-cantine.beta.gouv.fr/blog/16

**Comment by hfroot** [comment]
@gauthierandre merci, j'ai pas compris que c'est pour la page de publication et pas pour la page améliorer ma cantine. Je vais créer un nouveau issu
