### ISSUE TITLE
Retours en-tête

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1548]
Quand on clique sur mesure phare dans la nav barre ce serait bien d'y voir les cartes mesures plutot que la ligne
Documentation n'ouvre pas une autre page
Je mettrai "stat" à coté de nos cantines
Je séparerai stat de nos données et usage du site, ce sont des info un peu différentes et risque de confusion pour utilisateurs/internaute
Dans FAQ à changer qq réponses à changer (cf mon nouvel envoi fait par mail, le 21/6 je transfere à Helen) : 
L’inscription des gestionnaires, responsables légaux d’un service de restauration (dans les secteurs public et privé) est* va être obligatoire**. par est fortement recommandée

Ils doivent transmettre ces informations à l’administration par ce sont à partir de ces informations, que l'administration...
Ainsi, il est recommandé dans « ma-cantine » que les restaurants satellites *soient** considérés comme des cantines et déclarés comme tels par les cuisines centrales qui les livrent. 

Il faudrait réorganiser les questions (l'ordre d'apparition) plus par thème et par priorité? on pourrait mettre un numéro aux questions pour mieux les repérer?

**Comment by hfroot** [comment]
En plus : pas de lien de déconnexion

**Comment by alemangui** [comment]
Lien de déconnexion ici : fbe64496c914e59090b35a29cf022b548926d129 (sans pop-up de confirmation)

**Comment by alemangui** [comment]
> Je mettrai "stat" à coté de nos cantines

> Je séparerai stat de nos données et usage du site, ce sont des info un peu différentes et risque de confusion pour utilisateurs/internaute

Pas sur d'être d'accord, le fait que les stats sont sous items différents est une différenciation suffisante à mon avis.

**Comment by hfroot** [comment]
Tout à fait @alemangui je pense que ces retours ont été déprioritiser
