### ISSUE TITLE
🐛 Problème d'affichage dans la fonction "rechercher", menu mes cantines.

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1557]
Lorsqu'on utilise la fonction rechercher une cantine dans la page ma cantine (sur staging ou non, même si l'exemple est sur staging ici), la barre de recherche disparait une fois la cantine trouvée.

pour illustrer le bug
https://media.giphy.com/media/qEhxCK1b0w67LMhjhl/giphy.gif

**Comment by hfroot** [comment]
Merci, bien vu. J'ajoute cet issu dans le jardin
