### ISSUE TITLE
Différencier les cuisines centrales et satellites

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1565]
### Discussed in https://github.com/betagouv/ma-cantine/discussions/1556

<div type='discussions-op-text'>

<sup>Originally posted by **gauthierandre** June 27, 2022</sup>
On pourrait différencier, sur la page "mes cantines", les cuisines centrales et satellites avec un code couleur spécifique, ou une image différente. C'est une remarque qui revient régulièrement, et ça me parait d'autant plus pertinent que des personnes vont à la fois mettre leur CC car elle sert des repas, et aussi leur CS.

@JenniferStephan @valeriemerle @hfroot @alemangui </div>

**Comment by alemangui** [comment]
On a mis en place un tag en haut des cartes. Si le besoin évolue on pourra rouvrir cet issue.
