### ISSUE TITLE
ajouter gestion cookies et suivi données

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#157]
https://docs.google.com/document/d/1BLtL1pNkDnMxwtv4oEJK9bariWR9aYJkVaaz5omSq3c/edit#heading=h.drfewtp23zwk

**Comment by alemangui** [comment]
https://github.com/betagouv/ma-cantine/issues/281  <- Après cet issue on n'aura plus besoin de bandeau cookies.
