### ISSUE TITLE
800+ cantines sans région/dép

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1578]
Est-ce qu'on peut les migrer en utilisant le code postal ?
(180 sans code postal du tout)

**Comment by gauthierandre** [comment]
On peut pour ceux qui sont sur ce modèle un code postal = une ville. Car pafois y en a plusieurs villes pour un code postal, faudra regarder. On pourrait relancer ceux sans code postal également

**Comment by gauthierandre** [comment]
J'ai fermé sans faire exprès 🙈

**Comment by hfroot** [comment]
#1837
