### ISSUE TITLE
ajouter des mentions légales

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#158]
https://docs.google.com/document/d/1azR94oxJWChnnNZPzN8XDm32obdvVBN3OoUaHz1COd8/edit?usp=sharing

**Comment by hfroot** [comment]
J'ai noté qu'[un autre startup](https://covoiturage.beta.gouv.fr) utilise gitbook de montrer les mentions légales, est-ce qu'on veut faire le même ?
