### ISSUE TITLE
Bug graphique staging sur les labels

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1580]
Quand je fais passer le bouton à télédéclaration complète, il y a un problème d'affichage avec les labels ci-dessous
<img width="918" alt="Capture d’écran 2022-07-04 à 09 19 15" src="https://user-images.githubusercontent.com/85872944/177102853-55b7b9f0-ecc8-4afa-8bea-1f3f43553413.png">

**Comment by gauthierandre** [comment]
Sur. safari ! C'est ok pour moi sur chrome

**Comment by hfroot** [comment]
@gauthierandre est-ce que tu peux le tester sur safari et chrome ? Ça doit être réglé maintenant

**Comment by gauthierandre** [comment]
re. C'était ok sur Chrome donc ça marche, par contre c'est toujours le cas sur safari, je viens de faire la capture d'écran.

<img width="1363" alt="Capture d’écran 2022-07-08 à 10 42 59" src="https://user-images.githubusercontent.com/85872944/177953811-f0cf0c06-1627-497e-bbc6-5da967cf1d2a.png">

**Comment by hfroot** [comment]
@gauthierandre hmmm, ça marche sur mon safari... p-e les changement n'ont pas été poussés au moment où t'as testé. Essaye encore ?

**Comment by gauthierandre** [comment]
C'est ok de mon côté !
