### ISSUE TITLE
Bugs dans l'import massif

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#1597]
- Enlever les espaces avant et après le contenu des cellules (notamment pour le mode de gestion)
- `Integrity Error` lors de l'import de @YodBetYod 
- Affichage admin des invitations de gestion trop lent (liste de toutes les cantines) et pas de possibilité de chercher

**Comment by hfroot** [comment]
> Enlever les espaces avant et après le contenu des cellules (notamment pour le mode de gestion)
C'est aussi un pb avec l'import massif achats, rémarqué avec la liste de caractéristiques, deuxième element
