### ISSUE TITLE
Envoi d'email automatique aux cuisines centrales 

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1598]
Template à l’attention des cuisines centrales :
both central_serving & central.

CREATION CANTINE :
Scenario 1 :
- Condition : si création d'un compte utilisateur et rien d'autre
effet : une semaine après la création email CREATION CANTINE SATELITTES (ex: vous pouvez ajouter vos X cantines) ;

Scenario 2
- Condition : si une semaine après pas de création de cantine
effet : email de relance 1 CREATION CANTINE SATELITTES (ex : besoin d’aide ? venez à un webinaire dédié)

Pour création du diagnostic, le courriel existe déjà.

**Comment by gauthierandre** [comment]
@JenniferStephan tu en penses quoi ?

**Comment by hfroot** [comment]
Je mets la proposition dans picardie
