### ISSUE TITLE
mettre en evidence le côté beta.gouv

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#162]
- [x] Ajouter bannière beta + texte pour expliquer ce que ça indique ?
- [x] Ajouter "je donne mon avis" ?

**Comment by JenniferStephan** [comment]
propositions :
- dans la navbar, ajouter le logo beta.gouv.fr (plus reconnaissable que juste un bandeau "beta" ?)
- ajouter en dessous de la tagline un petit message : "🚧 Site en expérimentation (devenir testeur)" avec un lien mailto vers contact@egalim ou directement sur la page de formulaire "devenir beta-testeurs" ?
- je suis d'acc avec l'idée d'ajouter le "je donne mon avis"

<img width="886" alt="Capture d’écran 2021-03-29 à 11 51 47" src="https://user-images.githubusercontent.com/36134318/112820160-a64c4b00-9085-11eb-859b-a9b26d96abe8.png">
