### ISSUE TITLE
automatisation fin de diagnostic vers publication des données

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#163]

**Comment by JenniferStephan** [comment]
<img width="805" alt="Capture d’écran 2021-04-20 à 18 48 32" src="https://user-images.githubusercontent.com/36134318/115435148-d365c680-a209-11eb-8d67-0689b1180310.png">

TBD

**Comment by alemangui** [comment]
Cet issue est en _Done_ dans le projet jardin. N'hésitez pas à le rouvrir si besoin.
