### ISSUE TITLE
Améliorer les intitulés des boutons

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1640]
Sur la page “M’auto-évaluer”

![Screenshot 2022-07-12 at 09 56 13](https://user-images.githubusercontent.com/9282816/178439235-8c002ddd-8263-4a49-bf9a-44de23a66e5d.png)

**Comment by alemangui** [comment]
Pas trop compris ce qu'on doit faire. La liste affichée c'est une liste des boutons en générale ? Ou bien des boutons ou il y a un problème de texte ? Pourquoi spécifiquement sur la page "M’auto-évaluer" ?
