### ISSUE TITLE
Le site est compréhensible sans styles

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1641]
https://hellobokeh.notion.site/MaCantine-9cf4cfaf6e8c4ea1ae9367af71a7d27a?v=6ae1d92a13e14536b476d35a5a83a6bf&p=c0853c2640be4233bf325cfa8cfbe9d5

Affiche

- [ ] On a plus de contexte concernant l’aperçu.
- [ ] Les icônes n’ont pas d’alternatives
- [ ] Le formulaire n’a pas toujours les bons libellés

Démarches (stats regionnales)

- [ ] Les éléments du formulaires sont difficilement actionnables
- [ ] On a plus de contexte sur les statistiques

(commentaire : je pense que le composant v-autocomplete est le pb, il existe aussi sur des autres pages)

![Screenshot 2022-07-12 at 09 59 49](https://user-images.githubusercontent.com/9282816/178440032-930def7b-390d-4895-886f-b826418c1439.png)

Cantine publiée

- [ ] Le texte se chevauche
- [ ] Le formulaire n’a plus de sens

![Screenshot 2022-07-12 at 10 02 12](https://user-images.githubusercontent.com/9282816/178440517-a731a951-5574-49f0-a57f-fd6f7f1893fa.png)

**Comment by alemangui** [comment]
Je me permet de fermer cet issue suite à notre discussion. N'hésites pas à le rouvrir si besoin.
