### ISSUE TITLE
creation /stats

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#165]
- [x] Enlever les stats sur les réponses du diag
- [x] Publier notre stats avec tous les autres start ups
- [x] Créer une page dans le site pour démontrer le nombre des visiteurs dans le dernier mois (avec [ce conseil?](https://matomo.org/docs/embed-matomo-reports/#embed-a-matomo-report-in-a-html-page
))

**Comment by JenniferStephan** [comment]
quelques exs de pqges /stats de startup d'etat : 
- https://reserve-civique-metabase.osc-secnum-fr1.scalingo.io/public/dashboard/c25b3d89-d800-4ab7-bdd1-c225328da9ce
- https://datagir.ademe.fr/stats/
- https://mon-entreprise.fr/stats

commencer par juste par : 

- [ ] creer la page stats
- [ ] la mettre ds le footer "statistiques"
- [ ] embed le graphe du nb de visites depuis matomo
- [ ] mettre le lien sur la page de la startup detat beta gouv

<img width="671" alt="Capture d’écran 2021-03-29 à 12 11 22" src="https://user-images.githubusercontent.com/36134318/112822191-e9a7b900-9087-11eb-9591-829fde7b91c5.png">

note pour plus tard, utilisation de infogram pour faire des graphiques + ajouter du texte
