### ISSUE TITLE
changer le justificatif pdf de télédéclaration, une fois que complètée et validée

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1662]
aujourd'hui, on a toujours le pdf avec les champs de la télédécla simple; pensez à mettre ceux de la complète si c'est celle qui est remplie

https://github.com/betagouv/ma-cantine/projects/2#column-18664146
[teledeclaration-2021--ecole-valerie-solanas--2022-07-18.pdf](https://github.com/betagouv/ma-cantine/files/9132743/teledeclaration-2021--ecole-valerie-solanas--2022-07-18.pdf)

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/179743846-ec13dcf9-c62f-4ca3-8ba9-24588d29800d.png)

Fixes dans les commits f6677cb5820d8e2c239c9c1b2c3a403407909c0a et 3cb827a0247df7b9ffff7b1d15bf1321ca4e34bb

**Comment by alemangui** [comment]
Sur staging
