### ISSUE TITLE
télédécla : penser à mettre des contrôles de valeur

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1663]
- si la part de viande / poissons egalim ou provenance france est supérieure à la valeur totale : ERREUR

- si le part de bio + EGAlim hors bio > valeur totale : ERREUR

**Comment by alemangui** [comment]
Je me permet d'ajouter un cas :

- Si l'addition des _total viandes et volailles_ et _total poissons et produits de la mer_ est supérieure au total global, donc erreur
