### ISSUE TITLE
Server Error 500 quand modification du diagnostic

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1700]
J'ai essayé de faire trois modifications de diagnostics à partir de la page du diagnostic et cette erreur apparait.
Sur safari : 
<img width="1332" alt="Capture d’écran 2022-07-29 à 09 17 29" src="https://user-images.githubusercontent.com/85872944/181705212-de52cf31-d18c-4e07-9a37-43d7d4cb1bc7.png">

mais également sur chrome : 
<img width="1273" alt="Capture d’écran 2022-07-29 à 09 23 36" src="https://user-images.githubusercontent.com/85872944/181705952-bf881f1f-ee0d-4ed6-9070-02441af719a8.png">

**Comment by hfroot** [comment]
Merci, le fix est mainenant en revue de code, j'imagine on l'aura en prod fin lundi.
Ça viens d'une erreur dans la logique de validation des nouvelles valeurs appros qui viennent d'être en prod cette semaine. Les utilisateurs ne voient pas l'erreur quand iels changent le diag depuis leurs pages.
