### ISSUE TITLE
Bannière de la page avec compteur de partenaires référencés

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1726]

**Comment by hfroot** [comment]
c'est fait

![Screenshot 2024-09-03 at 17-17-58 ma cantine](https://github.com/user-attachments/assets/34ae61db-7c87-45bf-b494-b972619afcd6)
https://ma-cantine.agriculture.gouv.fr/acteurs-de-l-eco-systeme/?page=1
