### ISSUE TITLE
modélisation d'un "partenaire"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#1727]
<google-sheets-html-origin><style type="text/css"></style>

en FR | nom du champ | typage | description | format | obligatoire
-- | -- | -- | -- | -- | --
répond à un besoin | completedNeed | string | choix multiple parmi "améliorer ma part de bio / durable", "substituer mes plastiques", "donner à une asso locale", "diagnostiquer mon gaspillage", "trouver des conseils nutritions, diét,...", "diversifier mes apports de protéines", "me former ou former mon personnel" | badge/pills à cocher (plusieurs possible) | oui
nom | partnerName | string |   |   | oui
département | partnerDPT | integer | 02, 03, ... plusieurs possibles | à sélectionner sur une carte avec sélection en surbrillance | non si national = oui
national | partnerNational? | boolean |   | toggle | oui si pas de dpt
description | partnerDescription | text | description libre du partenaire | paragraphe de texte | oui
type d'acteur | partnerType | string | choix unique parmi : "association", "expert", "réseau de professionnels", "communauté", "entreprise", "producteur", "outil numérique" | choix en mode dropdown et select | oui
prix | partnerfree? | boolean |   | oui si gratuit en mode toggle à activer label "public et/ou gratuit' | oui
tarif | partnerPricing | text | prix du service, peut être "non renseigné", un entier, une fourchette,... | si non à partnerfree alors oui obligatoire | non
contact | partnerContactMail | mail |   | possible multiple | oui
contact | partnerContactTel | tel |   | possible multiple | non
site web | partnerURL | url |   |   | non
photo | partnerImage | doc |   |   | non
secteur |  |  |   |   | non
montant si aide |  |  |   |   | non
vos atouts |  |  |   |   | non

**Comment by valeriemerle** [comment]
Est ce que l'on peut faire un formulaire directement à partir de ce tableau où est ce que je construit un doc à partir de ces champs que l'on enverra aux partenaires que l'on recherche?

**Comment by JenniferStephan** [comment]
Yes je pense qu’un formulaire c’est pas mal ! Comme ça ça remplira direct
un Excel
Tu valides les champs ? Je peux les mettre après sur un typeform betagouv

Le jeu. 25 août 2022 à 16:48, Valerie Merle ***@***.***> a
écrit :

**Comment by valeriemerle** [comment]
Qq suggestions/questions sur ce qui est proposé: 
" répond à un besoin" : labelliser/faire reconnaitre ma démarche d'amélioration qualité + maitrise des risques sanitaire (sous reserve accord services sanitaires/accompagnement transition alimentaire/diagnostiquer *et réduire* mon gaspillage/ "diversifier mes *sources* de protéines/trouver des recettes vege en RC
"description" : l'idée est de les faire se présenter en qq lignes du genre "qui sommes nous"?
"département"(aire d'influence?) : indiquer l'aire de répartition géographique (présent dans toute la France +/- outre mer / en régionXX) mais pas redondant avec "national"?
Rajouter demander logo? nombre adhérent? indiquer si membre du CNRC?
Prix et tarif c'est quoi la différence?
Je ne me rappelle plus ce que tu voulais mettre dans "montant si aide"
Peut etre revoir l'ordre des champs si on transforme en formulaire?
Pour les types d'acteurs c'est plus complexe, je tente une typologie à partir de la liste des membres du CNRC, je vous la partage avec Frederika et en indiquant un ordre prioritaire pour le déploiement des info sur la page?

**Comment by gauthierandre** [comment]
Je n'ai pas grand-chose à rajouter, seulement quelques éléments qui me sont venus dans un souci de lisibilité de la page : 

* Ok avec Valérie sur les précisions concernant le premier champ : "obtenir des recettes végétariennes" ; "diagnostiquer et réduire mon gaspillage", etc. 

* je rajouterai un champ de tri : "**partnerAction**" : "qualité des produits" ; "gaspillage alimentaire" ; "diversification des menus" ; "interdiction du plastique" ; "information convives" (si besoin). Ça permettrait de classer les partenaires dans des pages différentes pour éviter le côté liste de Noël. Et après, on aurait le "completedNeed" qui permet d'identifier le bon prestataire pour un des axes ce qui me plait le plus : ex dans "diversification des menus", je vais trouver "recettes végétariennes" ; "former mon personnel" ; "conseils en nutrition".  Ça permet de hiérarchiser.

* Pour les départements, il faudrait une limite. Imaginons une start-up présente dans 50 départements, ça peut-être lourd comme information. Peut-être remplacer département par "**régions**" ? 

* Je mettrai bien une limite de caractère pour la description
