### ISSUE TITLE
Stats régionales : attribution de badge appro et valuers moyens

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#1791]
Dans ce cas, une cantine devrait bien avoir le badge appro, pourtant on ne la voit pas dans les stats régionales.

De plus, on a 0% en moyen de durable alors que les cantines ont bien des valeurs durables.

![image](https://user-images.githubusercontent.com/1225929/185398329-728b1fc2-1640-4d34-95c1-bd09dfdddcfd.png)

![image](https://user-images.githubusercontent.com/1225929/185398358-5a06f342-777e-43f3-a40d-70254cc1daea.png)

Merci @YodBetYod

**Comment by YodBetYod** [comment]
Merci pour la création de la carte!
