### ISSUE TITLE
Améliorer le cas où il y a un SIRET dupliqué dans un fichier d'import

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#1897]
Quand @YodBetYod  a essayé d'importer un fichier avec des SIRETs dupliqués, il a reçu les erreurs suivants

![Capture d’écran 2022-09-14 à 11 49 27](https://user-images.githubusercontent.com/9282816/190123178-42953e8c-39f4-4c27-81d1-5172547d74f5.png)

parce que il est un membre de notre équipe, il n'est pas ajouté en tant que gestionnaire quand la cantine serait créée alors il reçoit ce message

Dans ce cas, ça a été un pb d'avoir les dupliqués. Mais dans des autres cas peut-être les dupliqués sont bon (par ex en important les diagnostics).
- afficher un message d'erreur plus clair quand qqn essaye d'importer que des cantines, car une cantine dupliquée est surement un erreur
- reflechir si il y a un façon de verifier si les SIRETs dupliqués sont voulus ou non (e.g. "L'import va créer X cantines et Y diagnostics. Il y a Z lignes qui utilisent le même SIRET. Continuons ? [ bouton de confirmation de l'import ]"

**Comment by YodBetYod** [comment]
Merci pour la création du bug, @hfroot.

**Comment by hfroot** [comment]
on va améliorer ça avec validata je crois - @qloridant je n'arrive pas a voir où on suit le travail sur ça - pourrais-tu mettre le lien ici et fermer cet ancien issu ? Si tu trouves que validata pourrait améliorer ce pb

**Comment by qloridant** [comment]
@hfroot Validata va en effet avoir d'autres messages d'erreur. Pour l'instant la MAJ est pas intégrée dans la planning (right @Tdauvet89 )
Voir [notion](https://www.notion.so/Import-massif-fd049078a993468e8ea5160e14396cd8#1dfd272095ae45e1a2d30c9b65e42954à

**Comment by Tdauvet89** [comment]
Dans le planning du T4 :) c'est l'EPIC import massif
