### ISSUE TITLE
[Bug] pb montant dans la saisie des achats

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#1899]
Apparemment, le problème semble venir du montant (est-il trop élevé ?). Je ne sais pas trop ce qu'il se passe dans le cas de ce monsieur. 
Le bug arrive sur Safari, Google Chrome.

<img width="1266" alt="Capture d’écran 2022-09-15 à 09 34 33" src="https://user-images.githubusercontent.com/85872944/190344176-1d40ad9a-07fa-4580-8ddf-c0c72d343eed.png">

**Comment by hfroot** [comment]
J'imagine c'est parce qu'il y des espaces dans le chiffre. C'est un bug qu'on n'affiche pas un meilleur message d'erreur, et on l'améliora

**Comment by alemangui** [comment]
Je ne comprends pas comment ça se fait que le validateur ne s'allume pas :thinking: 
![image](https://user-images.githubusercontent.com/1225929/191026720-263e4028-5cec-481b-ad37-51d8c03deffe.png)

**Comment by alemangui** [comment]
Ce PR https://github.com/betagouv/ma-cantine/pull/2033 permettra de montrer le message d'erreur
