### ISSUE TITLE
Clé API Exposée

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/ma-cantine#191]
Hello,

Votre token d'accès Sendinblue est exposé via le composant newsletter. Je vous conseille d'utiliser un proxy backend pour l'inscription :)

**Comment by Forster-Groux** [comment]
> Hello,
> 
> Votre token d'accès Sendinblue est exposé via le composant newsletter. Je vous conseille d'utiliser un proxy backend pour l'inscription :)

Exact, on va déplacer cette logique dans le back-end, merci pour la remontée. :)
