### ISSUE TITLE
Invitation de gestion ne fonctionne pas

### ISSUE THREAD

**Issue by YodBetYod** [betagouv/ma-cantine#1915]
Une référente de Département m'a fait remarquer qu'elle avait reçu des demandes de "rejoindre l'établissement" d'intendants de collèges alors que ce ne devrait pas être le cas puisque j'avais créé des invitations de gestion pour ces intendants.

Exemple :
L'utilisatrice (Marie-Christine DELAURENT-GUITTAT) s'est bien créé un compte : cf. PJ 1.
Il y a bien une invitation de gestion qui associe l'adresse électronique de cette utilisatrice et son établissement (Collège du Val de Senouire) : cf. PJ 2.
Mais quand l'utilisatrice accède à son espace Mes Cantines, la cantine de son établissement n'apparaît pas : cf. PJ 3.

@hfroot, @alemangui, savez-vous à quoi c'est dû?

<img width="829" alt="Capture d’écran 2022-09-19 à 11 59 49" src="https://user-images.githubusercontent.com/93709421/190996676-2a22ce1d-2c9f-45d7-a1ad-15da6c20b9c6.png">
<img width="818" alt="Capture d’écran 2022-09-19 à 12 00 00" src="https://user-images.githubusercontent.com/93709421/190996679-a53b9d70-b115-45de-8176-362ff97ca107.png">
<img width="1085" alt="Capture d’écran 2022-09-19 à 12 02 25" src="https://user-images.githubusercontent.com/93709421/190996682-02a7b48c-f667-4a1a-88b3-c0b39de736c2.png">

**Comment by hfroot** [comment]
Ah j'imagine c'est un pb avec le M en majuscule ou minuscule - on pourrait reparer ça

**Comment by YodBetYod** [comment]
Ça doit être ça en effet. Merci!

**Comment by alemangui** [comment]
Le fix est en staging, par contre il faut savoir que sur certain standards (surtour des vieux serveurs) des emails avec des cases différents ne sont pas les mêmes. Par ex, il es possible que [leo@example.com](mailto:leo@example.com) ne soit pas la même adresse que [LEO@example.com](mailto:LEO@example.com)

@hfroot une approche à une situation similaire est dans cette PR : https://github.com/betagouv/ma-cantine/pull/1842

À surveiller pour s'assurer que d'autres problèmes n'arrivent par la suite.

**Comment by hfroot** [comment]
@alemangui j'ai eu l'impresssion que les gros prestataires de mail assurent que leurs adresses sont insensible de cas alors esperons que ça va pas poser pb mais oui, qqch à voir
