### ISSUE TITLE
Publication cuisine centrale et satellites

### ISSUE THREAD

**Issue by valeriemerle** [betagouv/ma-cantine#1947]
Autoriser la publication d'une CC avec diagn ou pas en indiquant leurs satellites, nombre? par lien? Attention certaines CC peuvent avoir plus de 100 satellites.
Publication des satellites : donner l'information sur "desservis par la cuisine centrale" en mettant un lien permettant d'aller voir leur cuisine centrale (qui possede des info alors qu'eux n'en n'ont pas forcement

**Comment by hfroot** [comment]
Changements nécessaires :

### Modification page pour publier

- Garder champ commentaires
- "Les satellites suivantes seront publiées en même temps"
- Liste de satellites sans diag, ces satellites vont avoir les données de la CC affichées sur leurs pages de publication
- Liste de satellites avec leur propre diag, ces satellites vont avoir leur propres données affichées, en plus d'un lien vers la CC qui livre leurs repas

### Création endpoint publication en masse

Aussi utile comme extension de #2018 

Donner une liste des ids de cantines, publier ces cantines

### Modification endpoint satellites pour une cantine

Dans le réponse, ajouter:

- statut de publication
- id du diag pour l'année dernière si il existe (boolean suffit mais id c'est p-e plus intéressant à l'avenir ?)

### Modification page publication CC

Mettre quelque part des liens pour toutes les cantines satellites de la CC

### Modification page publication satellite sans diag

- "Cette cantine reçois des repas livrés par <lien cuisine centrale>"
- Les données suivantes ont été déclarer par <Nom CC>
- Un bordeur p-e pour le contenu (tout après `Que mange-t-on dans les assiettes en 2021 ?` et avant le formulaire contact)

Ça aurait besoin si d'un deuxième appel vers le back pour récuperer les infos CC, ou un modif/ajout d'un endpoint pour inclure les données direct dans le premier appel

### Modification endpoint filtrage nos cantines `/publishedCanteens`

- Changement du view ou serializer pour inclure les cantines satellites sans diag reliées à une CC qui ce retrouve dans les resultats ?
  - Pour quels filtres ?

### Modification carte de cantine publiée

En ce moment, les badges affichés sur la carte cantine publiée sur nos cantines sont calculés sur le front, selon le diag attaché à la cantine.

Mieux refactoriser pour retourner les badges depuis le back? Et avec ça, ajouter des badges selon les données du diag CC.

**D'ailleurs comment décider sur les badges dépendents sur le nb repas ? Donation agreement, diversification plan**

**Comment by hfroot** [comment]
Make satellite opt-out

Can all the measures be deduced from the cuisine centrale?
