### ISSUE TITLE
IndexError on Sentry

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#2069]
https://sentry.incubateur.net/organizations/betagouv/issues/5813/

**Comment by hfroot** [comment]
J'ai pas reussi de recréer l'issu et car l'utilisateur a finalement réussi avec l'import, je pense pas que ça soit un priorité. Regardons si il arrive encore. Pour l'instant j'ai laissé qqs commentaires dans sentry avec ce que j'ai essayé à faire
