### ISSUE TITLE
Page d'actions : filtrer par action

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2089]
Et un lien quick-filter 'Voir les cantines que je peux télédéclarer' à côté du bouton TD en masse

On pourrait imaginer des filtres pour toutes les actions:
Il y a X cantines prêtes à publier : voir les cantines à publier (etc)

**Comment by alemangui** [comment]
@hfroot est-ce qu'il faudrait plutôt le mettre sur Picardie ?

**Comment by hfroot** [comment]
@alemangui vu que c'etait une reflexion perso je vais le fermer pour l'instant.
