### ISSUE TITLE
(retour tests) affiche

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#209]
- [ ] enlever la phrase "Un bon moyen de savoir ce qu'il y a dans votre assiette et d'en discuter avec le personnel de votre restaurant !"
- [ ] permettre à l'utilisateur de télécharger un logo
- [ ] changer le mot "cantine", permettre à l'utilisateur de personnaliser, comme pour le nom
- [ ] remettre les questions sur le commerce équitable ds le formulaire et ds le graphe
- [ ] sur la légende graphe : "produits bio ou en conversion", "produits durables et de qualité (hors bio)", "produits hors EGAlim"

**Comment by alemangui** [comment]
Suite aux changements dans #502 et #507 je ferme cet issue. N'hésitez pas à le rouvrir si besoin.
