### ISSUE TITLE
Annuler les TD si la cantine/le diag est supprimé

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2091]
Pour éviter d'avoir les TD SUBMITTED pas liés aux cantines dans nos stats, et, dans le cas d'un diag supprimé, éviter des bugs de validation quand on fait une TD à nouveau

**Comment by alemangui** [comment]
On peut utiliser SET avec un callback au lieu de SET_NULL : https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.SET
