### ISSUE TITLE
(retours tests) excel

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#210]
- [x] mettre deux formats de telechargements .xls et .ods
- [ ] mettre le durable hors bio sur l'excel (jenn)

**Comment by hfroot** [comment]
Le premier point est relier au #230

**Comment by hfroot** [comment]
https://drive.google.com/drive/u/0/folders/14c6H4ZomF2P1ljiJeCZt17Z1Y0xfjQBz

**Comment by alemangui** [comment]
Vue que la carte projet est archivée et que l'issue en question est mergé et fini, je ferme cet issue. N'hésitez pas à le rouvrir si besoin.
