### ISSUE TITLE
PRIO - 10000 / pur kiffe perso - proposition de nouvelles illus ma cantine

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2125]
bon, c'est du pur kiff perso... je suis en train de me former sur la vectorisation figma pr faire des illus et du coup, pr m'entrainer, j'ai recréée des illus personnalisées "ma cantine"........ pr l'instant j'en ai 4 qui pourraient le taff sur la landing : 

<img width="847" alt="Capture d’écran 2022-11-29 à 14 01 51" src="https://user-images.githubusercontent.com/36134318/204536917-74b03913-3723-4947-a63b-86703baf2fa0.png">

**Comment by alemangui** [comment]
Elles sont très cool, si c'est OK je me permet de fermer cet issue et de le rouvrir si les autres illustrations sont aussi renseignées, pour éviter d'avoir les deux styles en même temps. Je sais aussi qu'Arthur avait évoqué le remplacement de certaines illustrations, ça pourrait valoir la peine de revoir avec lui comment les intégrer.
