### ISSUE TITLE
Quand l'utilisateur essaye d'accèder une page protégée, rediriger l'utilisateur vers la page de connexion

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2128]
E.g.
Personne X clique sur un lien dans un mail pour gerer une équipe de gestion, mais X n'est pas connecté.e au site.

Aujourd'hui : 
- X voit une page "La page que vous recherchez semble introuveable"

Désiré:
- X est redirigé.e vers la page de connexion
- après avoir se connecter, X est redirigé.e vers la page originale

Si c'est trop compliqué un premier étape pourrait d'ajouter un bouton de se connecter sur cette page "404". Et une explication de "Connectez-vous et re-essayez d'ouvrir le lien" ou qqch

**Comment by alemangui** [comment]
Je ne crois pas que ça soit un bug, mais plutôt une amélioration :thinking:
