### ISSUE TITLE
Design - exemple d'une app côté "gestion du compte" avec liste des "milestones" pour gagner des "badges réussites"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2170]
<img width="1656" alt="Capture d’écran 2022-12-19 à 15 22 46" src="https://user-images.githubusercontent.com/36134318/208447826-7e29576b-35f0-46fd-b4d0-7fb51d51e8b1.png">

<img width="1145" alt="Capture d’écran 2022-12-19 à 15 24 21" src="https://user-images.githubusercontent.com/36134318/208448071-03e7ca11-0c1a-4c3f-b81f-9352963320b7.png">

**Comment by hfroot** [comment]
Petit rémarque - ça pourrait remplacer / être basé sur la page dashboard

![Screenshot from 2023-01-06 15-24-20](https://user-images.githubusercontent.com/9282816/211031196-3720ef0c-60fe-4d38-8fb0-60baad55c1a5.png)

**Comment by alemangui** [comment]
Suite au nouveau parcours designé par Arthur qui montre déjà les actions à effectuer dans chaque cantine je me permet de fermer cet issue
