### ISSUE TITLE
(retours blog)

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#218]
- [x] avant la date ajouter "Publié le" et/ou "mis à jour le"
- [ ] ajouter un champs "catégorie" : "témoignages", "bonnes pratiques", "à propos de la loi", "divers" (à affiche comme un petit badge ?)
<img width="369" alt="Capture d’écran 2021-05-10 à 15 43 23" src="https://user-images.githubusercontent.com/36134318/117668684-788b1380-b1a6-11eb-9c30-e12d8c9b2c18.png">

- [x]  remplacer "Découvrez notre espace témoignages" par "Découvrez notre espace blog et témoignages"

- [x] quand on accède au détail d'un article, mettre un bouton "retour" pour retourner à la liste des articles /blog

pour plus tard : 
- [ ] mettre une recherche par mot-clés
- [ ] mettre un filtre par date + par catégories

**Comment by hfroot** [comment]
Comme on a discuté, on va ajouter les champs catégorie plus tard

**Comment by hfroot** [comment]
Aussi Forster a suggéré qu'on peut ajouter le nom de l'auteur, encore je pense que c'est un truc pour l'avenir.

**Comment by alemangui** [comment]
@hfroot @JenniferStephan  Est-ce que la recherche / filtrage dans le blog est toujours d'actualité ? On peux faire quelque chose de similaire à [nos-cantines](https://staging.ma-cantine.beta.gouv.fr/nos-cantines/?page=1)

**Comment by alemangui** [comment]
Je ferme cet issue car on a plutôt décidé de focaliser sur _nos-cantines_ - y compris avec des champs texte libre pour les publications. Si cette fonctionnalité est souhaité dans le futur n'hésitez pas à rouvrir ;)
