### ISSUE TITLE
(mesures-phare) Modif menu végé

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2180]
### Contexte : 
demande de mise à jour de la page mesure-phare sur la diversification des protéines. 
cf mail et message de Val. 

### Où ? 
https://ma-cantine.agriculture.gouv.fr/mesures-phares/diversification-des-menus

Modifs comme suivent sur la capture écran : 

![Capture d’écran 2022-12-19 152846](https://user-images.githubusercontent.com/36134318/210357418-b5072ec7-99a4-4d47-a1c2-f66efb677f11.png)

### A modifier : 

- [ ] ajouter le texte : 

"☝️🌱 À partir du 1er janvier 2023, les restaurants collectifs de l'État, les établissements publics et les entreprises publiques nationales doivent proposer une option végétarienne quotidienne, dès lors qu'ils proposent habituellement un choix multiple de menus. Ces établissements sont les suivants :

🏫 les universités ou enseignements supérieurs publics, administration (RA ou RIA), établissements pénitenciers, restaurants des armées ;
​
🏥🧑‍💼 les établissements publics placés sous la tutelle de l’État, comme par exemple des agences, instituts et centres nationaux (OFB, ANSES, IGNF, INRAE, ...), des établissements publics de santé* (CHR/CHU, CHN, CH, HL, CHS...) ou des établissements publics nationaux (ASP, CdC, CNRS, ...) ;​

🏭 les entreprises publiques : établissements publics industriels et commerciaux, sociétés commerciales (détention majoritaire du capital par l’État)."

**Comment by JenniferStephan** [comment]
ajouter uniquement le texte au dessus sous le texte existant de cette sous-mesure
pas de modif de l'encart et des secteurs concernés

**Comment by hfroot** [comment]
@JenniferStephan le texte existant pour "Option vege quotidienne" c'est

> Les restaurants de l’Etat, ses établissements publics, et les entreprises publiques nationales proposent une option végétarienne quotidienne, dès lors qu'ils proposent habituellement un choix multiple de menus, à partir du 1er janvier 2023.

Qui me paraît trop similaire au nouveau texte proposé pour le garder

> À partir du 1er janvier 2023, les restaurants collectifs de l'État, les établissements publics et les entreprises publiques nationales doivent proposer une option végétarienne quotidienne, dès lors qu'ils proposent habituellement un choix multiple de menus. Ces établissements sont les suivants :

**Comment by hfroot** [comment]
Et c'est quoi le * dans : ?

> des établissements publics de santé* (CHR/CHU, CHN, CH, HL, CHS...)

**Comment by JenniferStephan** [comment]
go en prod @hfroot 
on enlève l'astérix * :)
