### ISSUE TITLE
(suivi d'achats) ajouter un tuto loom pour le suivi d'achats

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2181]
### constat : 
nécessité d'accompagner les utilisateurs sur l'outil de suivi d'achats

### proposition : 
sur la page "Mes Achats" proposer un tuto vidéo
loom : https://www.loom.com/share/c22baca19c6f4df39d426d312da2a33f

on attend le retour de @Greta712 sur le contenu avant de valider :)

### niveau design : 

sous le titre "Mes Achats" et sous le sous-titre; mettre une phrase genre "Besoin d'aide ? regardez notre tutoriel vidéo" avec en lien une ouverture de modale et la vidéo + un bouton "Commencer" en dessous ? 

<img width="1596" alt="Capture d’écran 2023-01-03 à 14 24 22" src="https://user-images.githubusercontent.com/36134318/210366034-a1377323-3e37-4518-9721-0a8b47a3e5b6.png">

**Comment by JenniferStephan** [comment]
validé côté @Greta712 :)

**Comment by hfroot** [comment]
Niveau design, tu penses quoi de ça @JenniferStephan 

J'ai repris les designs de composants pour le vidéo tuto sur [les pages import cantines/diags](https://ma-cantine-staging.cleverapps.io/importer-diagnostics/cantines-seules) et pour le composant [en bas de la page chiffres](https://ma-cantine-staging.cleverapps.io/statistiques-regionales)

![Screenshot from 2023-01-04 17-07-37](https://user-images.githubusercontent.com/9282816/210598279-4a55d968-b802-4588-ab42-6ba2faae97ee.png)
![Screenshot from 2023-01-04 17-07-40](https://user-images.githubusercontent.com/9282816/210598302-d996d284-0082-47aa-9617-2e8a7c40c5e8.png)

**Comment by hfroot** [comment]
D'ailleurs niveau contenu vidéo, j'ai eu l'impression que l'import achats c'est pour ceux qui utilisent un outil suivi, et pas juste pour rendre le saisi moins fastidieux. Car si le site est fastidieux il faut qu'on revoit le design. (Je reprends l'approche d'import cantines/diags recemment discuté)

**Comment by JenniferStephan** [comment]
ca va top comme design !

**Comment by hfroot** [comment]
> hello sur le côté "fastidieux" je pense plutôt à des cuisines centrales qui utilise déjà excel pr leur suivi d'achat mais qui n'ont pas d'outil, en gros ca serait du one shot pr après utiliser au compte goutte notre outil :) je sais pas si ça répond à ta remarque; pcq non ca serait pas pr ceux qui "jugent fastidieux" notre produit (ça serait la raison, alors je suis d'acc c'est à ns de changer ;) )

On a la même idée alors :) je sais pas si c'est clair dans la vidéo par contre que cet import est pour ceux qui ont déjà un outil, et pas que pour ceux qui pensent que ce serait plus facil de rentrer leurs données en excel par main et après importer ce fichier.
