### ISSUE TITLE
(nos-cantines) ds la box pour contacter la cantine, ajouter un msg pour spécifier le contenu de messages et mettre liens vers d'autres fonctionnalités si besoin

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2182]
### Constat : 
Sur les pages publiques des cantines, ns recevons un grand nombre de msgs hors sujet et hors cadre de l'application.
ex : candidature à un poste; des parents qui informent de l'absence de leur enfant à la cantine; des producteurs qui vendent leur pdt à des cantines...

### Proposition : 
Préciser avant la rédaction du message par l'utilisateur, l'objet de la prise de contact avec une cantine. Le rediriger si besoin.

** 
"Vous pouvez par exemple : 
🤔 demander des informations supplémentaires sur la cantine que vous fréquentez; 
🤝 contacter un collègue gestionnaire afin de lui demander un retour d'expérience sur une action mise en place...

il ne s'agit cependant pas de : 
❌ postuler à une offre d'emploi pour une cantine
=> privilégier des contacts de l'établissements hors de ma cantine
❌ informer l'établissement de l'absence/présence de soi ou d'un tiers au repas du jour
=> privilégier un contact avec la "vie scolaire" 
❌ en tant que fournisseur de proposer ses services
=> privilégier votre référencement sur notre page "acteurs de l'éco-système" en demandant votre référencement (lien)

Nota bene : l'équipe de ma-cantine se réserve un droit de modération et décide ou non de valider votre message dans les 3 jours ouvrables. 
Rappel, ne partagez pas d'informations sensibles (par ex. mot de passe, numéro de carte bleue, etc). "
**

### Où ? 

sur la page détaillée d'une cantine sur /nos-cantines 
en dessous de l'adresse email et avant le message pour être certain que cela soit lu ? 

<img width="1463" alt="Capture d’écran 2023-01-03 à 13 13 59" src="https://user-images.githubusercontent.com/36134318/210355302-37426c45-3471-4cd6-9509-149478850aac.png">

### Penser à : 

- [x]  mettre le tps de réponse, un délai; pour dissuader les demandes temporelles type "mon enfant sera absent aujd"
- [x] fusionner avec le texte actuel précisant de ne pas mettre de données confidentielles
- [x] renvoyer vers les fonctionnalités "partenaires" si c'est un producteur/fournisseur/entreprise
- [x] rappeler que ns n'avons pas vocation à gérer la vie scolaire si c'est un parent 

en suspens (pas agir maintenant) : 
comment agir sur les candidatures / gestion RH ? contexte : bcp de gens postulent à des cantines... Or j'ai l'impression que c'est un secteur assez tendu au niveau de l'embauche et donc que les cantines sont bcp en demandes de personnel. 
est-ce que ce serait un besoin d'être une plateforme centralisatrice des ressources humaines ? genre un welcome to the jungle de la restau co ? 
je lance une discussion github sur le sujet ;)

**Comment by hfroot** [comment]
Proposition petites modifs design et text

![Screenshot from 2023-01-04 18-49-23](https://user-images.githubusercontent.com/9282816/210620481-fcf60175-4999-4b5e-9f11-eca3ab707d94.png)
