### ISSUE TITLE
(SUIVI D'ACHATS) ajouter au tableau récapitulatif de tous les achats l'affichage d'une ou plusieurs caractéristiques entre la famille et la cantine concernée

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2191]
dans le tableau récap de tous les achats, ajouter "Caractéristique(s)" entre "famille" de pdt et "cantine" concernée par l'achat

ici : 
<img width="1230" alt="Capture d’écran 2023-01-05 à 16 23 44" src="https://user-images.githubusercontent.com/36134318/210816439-f58da998-3e09-4972-b010-21fa5fea7932.png">

objectif : identifier directement ses achats EGAlim

cas particulier : 
si aucune caractéristique n'est renseigné; ne rien mettre ou "non-EGAlim"

**Comment by hfroot** [comment]
@JenniferStephan est-ce que tu peux clarifier cette suggestion ? On a déjà un filtre Characteristiques
