### ISSUE TITLE
(STATS REGIONALES) changer la composition de la partie "badge" et atteinte des objectifs

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2196]
<img width="1196" alt="Capture d’écran 2023-01-05 à 17 59 41" src="https://user-images.githubusercontent.com/36134318/210838335-11f341fc-8248-42b8-b1c2-6f54acea3bcf.png">

**constats :** 

- les règles d'obtention des "badges" qui sont ds la liste déroulante "? comment atteindre les objectifs" arrive trop tard dans la page

-> expliciter les règles d'obtention des badges directement au niveau des badges ? 

- "29 % lutte contre le gaspillage" remplacer les textes par : 
-> XX% ont obtenu un badge "XXXX" ?

**Comment by hfroot** [comment]
entre temps je me permets de créer le label `stats` pour appliquer aux retours stats. Comme ça on peut facilement retrouver les retours ici quand on refait les pages

**Comment by hfroot** [comment]
ajouté dans notion
