### ISSUE TITLE
(télédéclaration 2023) modifs à faire pour la prochaine campagne

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2204]
hello 👋
la campagne de remontée des données de l'année 2022 à faire en 2023 (entre janvier et 31 mars - certainement prolongée mais on a pas encore l'info) nécessite que l'on modifie quelques éléments.)

Sur les dates : parti pris équipe : ok pour prolonger, mais date à donner en amont : fin avril, bien car tombe après la clôture des budgets

MODELE DE DONNEES CANTINES : 

- [x]  sur le formulaire de création de la cantine, ajouter un champ "code postal" obligatoire - on laisse le remplissage automatique du code INSEE qui servira aux stats
- [x]  changer les définitions des types de production (remplacer par les propositions sur mattermost de @hfroot)
- [x]  si je me suis trompée et que je passe d'une cuisine centrale avec un nb de sat rempli; et que je passe en cuisine site : alors le champ "nb de sat" se grise mais le chiffre reste en base de données. A modifier : effacer le nb de sat ds la BDD. mettre un msg de confirmation à la validation des modifs ? "vous avez changé votre type de production ? confirmer oui / non"
- [x] #2315
- [x] "Secteur économique" à changer pr le mettre en champ facultatif

(grosse story) 
- [x] GÉRER LA COMPLEXITÉ DES "Secteurs d'activité" pour la cuisine centrale qui par définition en ont souvent plusieurs
pouvoir proposer à l'utilisateur qui a choisi "type de prod" CC et plusieurs secteurs d'acti; de renseigner le nb d'établissements (donc nb de satt) qui correspondent à un secteur d'acti précis
un genre de tableau à deux entrées où la somme totale de la colonne "nb d'établissements" est égale à la somme des sat remplis par l'utilisateur / en 1ère colonne : la liste des secteurs d'acti choisis par l'utilisateur CC

- [x] si je suis une cuisine site ou une cuisine sat : rendre impossible le fait de pouvoir sélectionner plusieurs secteurs d'activité

DIAGNOSTIC / TD 2022 : 

<img width="1669" alt="Capture d’écran 2023-01-09 à 10 04 06" src="https://user-images.githubusercontent.com/36134318/211282467-13f626ff-7335-49c9-8463-8095ece41cad.png">

(cf capture) 
- [x]   ajouter ds le label du champ "SIQO" ds la parenthèse: ajouter "label rouge" (il y est en logo mais pas ds la liste des labels détaillés)

- [x] #2259

- [x] pour chacun de ces champs en saisie simplifiée : ajouter une option "je ne sais pas" (actuellement, on gère la non-complétion du champ comme un "je ne sais pas" mais on le transforme en 0 ds la base de données; compliqué ds le traitement des données : il faudrait réussir à distinguer les 2 infos : le "je ne sais pas" et "ma valeur est 0")
par ex, ajouter en dessous du champ un "checkpoint" je ne sais pas ? et ca grise le champ de la valeur et ca le remplit avec un contenu identifiable ? genre un "-1" ? 

- [x]  pour le typage des champs de valeur (tous les champs de valeurs dans toutes les saisies) : ne pas permettre les entiers négatifs (actuellement, si tu remplit avec tes fleches de direction tu peux défiler et mettre et valider une valeur négative

- [x] n'autoriser que les entiers (sans virgule) (ou le transformer nous même en entier en arrondissant ?)

- [x]  ds la saisie simplifiée, changer le label du champ "La valeur (en HT) de mes achats prenant en compte les coûts imputés aux externalités environnementales ou acquis sur la base de leurs performances en matière environnementale" par "Critères d'achat : La valeur (en HT) de mes achats prenant en compte les coûts imputés aux externalités environnementales ou acquis sur la base de leurs performances en matière environnementale" 

- [x] ds la saisie simplifiée, changer l'ordre d'affichage des champs de valeurs : mettre à la fin le champ des "valeurs d'achats coûts imputés..."; i.e. inverser ça et "La valeur (en HT) des autres achats EGAlim"

<img width="706" alt="Capture d’écran 2023-01-09 à 11 13 31" src="https://user-images.githubusercontent.com/36134318/211285240-04d4e310-561f-422e-b28e-1326a6ebc199.png">

- [x]  sur le champ, "Critère d'achats : la valeur (en HT) de mes achats prenant en compte les coûts imputés aux externalités environnementales ou acquis sur la base de leurs performances en matière environnementale" ajouter à la fin du label du champ, une info bulle avec affichage en hover du texte présent sur la page mesure-phare : 

<img width="1039" alt="Capture d’écran 2023-01-09 à 11 16 46" src="https://user-images.githubusercontent.com/36134318/211286065-a3f53854-216f-4e0c-a6a1-8b9719011291.png">

"Produit acquis suivant des modalités prenant en compte les coûts imputés aux externalités environnementales liées au produit pendant son cycle de vie (production, transformation, conditionnement, transport, stockage, utilisation) - L'article 2152-10 du code de la commande publique dispose que, pour l'évaluation du coût du cycle de vie des produits, les acheteurs s'appuient sur une méthode accessible à tous, fondée sur des critères non-discriminatoires et vérifiables de manière objective et qui n'implique, pour les soumissionnaires, qu'un effort raisonnable dans la fourniture des données demandées. Ni la loi EGALIM, ni le code de la commande publique n'imposent de soumettre la méthodologie de calcul du coût des externalités environnementales liées aux produits à une validation de l'administration. Dès lors qu'ils respectent les exigences du code de la commande publique, les acheteurs ayant recours à ce mode de sélection sont libres de définir les modalités qui leur semblent les plus pertinentes sous leur responsabilité. Certaines démarches collectives et/ou certains fournisseurs accompagnent déjà les acheteurs dans la mise en place d'une méthode."

"Produits acquis principalement sur la base de leurs performances en matière environnementale et d’approvisionnements directs (précisions à venir)"

**Comment by alemangui** [comment]
:thinking: on ne transforme pas les valeurs vides en zéro dans la base de données, ils apparaissent comme _null_

>  pour chacun de ces champs en saisie simplifiée : ajouter une option "je ne sais pas" (actuellement, on gère la non-complétion du champ comme un "je ne sais pas" mais on le transforme en 0 ds la base de données;

**Comment by alemangui** [comment]
Le code postale est déjà rempli automatiquement dans la base avec le code INSEE non ?

>  sur le formulaire de création de la cantine, ajouter un champ "code postal" obligatoire - on laisse le remplissage automatique du code INSEE qui servira aux stats

**Comment by alemangui** [comment]
Pourquoi les numéros avec des centimes gênent ? Je demande car il faudra aussi modifier le remplissage automatique à partir des achats - ce n'est pas grave mais ça prendra un peu du temps et je ne suis pas sur de comprendre le besoin.

> n'autoriser que les entiers (sans virgule) ou le transformer nous même en entier en arrondissant ?

**Comment by alemangui** [comment]
Utilisation du DSFRCurrencyField ([PR ici](https://github.com/betagouv/ma-cantine/pull/2216)) pour empêcher la saisie d'une valeur négative

>  pour le typage des champs de valeur (tous les champs de valeurs dans toutes les saisies) : ne pas permettre les entiers négatifs (actuellement, si tu remplit avec tes fleches de direction tu peux défiler et mettre et valider une valeur négative)

**Comment by alemangui** [comment]
> sur le formulaire de création de la cantine, ajouter un champ "code postal" obligatoire - on laisse le remplissage automatique du code INSEE qui servira aux stats

Le formulaire aujourd'hui rempli déjà un champ _code postale_ dans la base de données. Les cantines sans données géographiques viennent probablement de l'import massif ou ont été créées avant. Après discussion avec @valeriemerle on créera une requête Metabase pour les identifier et décider d'une stratégie pour les mitiger.

**Comment by alemangui** [comment]
> pour chacun de ces champs en saisie simplifiée : ajouter une option "je ne sais pas" (actuellement, on gère la non-complétion du champ comme un "je ne sais pas" mais on le transforme en 0 ds la base de données; compliqué ds le traitement des données : il faudrait réussir à distinguer les 2 infos : le "je ne sais pas" et "ma valeur est 0")
par ex, ajouter en dessous du champ un "checkpoint" je ne sais pas ? et ca grise le champ de la valeur et ca le remplit avec un contenu identifiable ? genre un "-1" ?

Après discussion avec @valeriemerle on a remarqué qu'il y a bien une différence en base entre "je ne sais pas" (valeur vide `null`) et zéro (valeur `0`). Par contre, on veut que l'utilisateur soit bien conscient qu'iel communique à l'administration "Je ne sais pas / je n'ai pas assez d'information" lors qu'un champ est laissé vide - et on est d'accord que le placeholder actuel ne suffit pas toujours.

Donc, deux propositions sont lévées :
- Dans le modal de confirmation de la télédéclaration (et dans le justificatif PDF) on doit remplacer les tirets qui dénotent une manque d'information par du texte claire "Je ne sais pas répondre à cette question" ou quelque chose comme ça - et éventuellement de changer la couleur ou ajouter un icône pour que ça soit clair,
- Ajouter un texte dans le formulaire et dans le guide de saisie : aprox "Tout champ laissé vide sera interprété comme une manque d'information de votre part".

![image](https://user-images.githubusercontent.com/1225929/212086487-f99d26e8-8b63-4b41-9fca-2cae1a705d7d.png)

**Comment by alemangui** [comment]
Concernant les champs qui sont figés dans le temps à l'intérieur de l'objet _télédéclaration_, il faut en ajouter :
- Couverts moyen par jour
- Nombre total de couverts à l'année

**Comment by alemangui** [comment]
> n'autoriser que les entiers (sans virgule) (ou le transformer nous même en entier en arrondissant ?)

On laissera les centimes pour ne pas modifier le moteur de pré-remplissage des achats, mais les export de la base de données on pourra faire en sorte que les valeurs soient arrondis au nombre entier le plus proche pour éviter des soucis d'import de CSV sur Excel.

@valeriemerle

**Comment by alemangui** [comment]
PR : https://github.com/betagouv/ma-cantine/pull/2219 commence les améliorations décrites ici : https://github.com/betagouv/ma-cantine/issues/2204#issuecomment-1380403617

**Comment by JenniferStephan** [comment]
> 🤔 on ne transforme pas les valeurs vides en zéro dans la base de données, ils apparaissent comme _null_
> 
> > pour chacun de ces champs en saisie simplifiée : ajouter une option "je ne sais pas" (actuellement, on gère la non-complétion du champ comme un "je ne sais pas" mais on le transforme en 0 ds la base de données;

ok ça doit être ds la requête metabase alors. parce que lorsque l'on télécharge un fichier csv depuis metabase, j'ai l'impression que les null se transforment en 0 sur le doc. à vérifier

**Comment by alemangui** [comment]
Par rapport aux _Secteurs d'activité_ on créera une autre carte sur ce sujet.

**Comment by alemangui** [comment]
_"Secteur économique" à changer pr le mettre en champ facultatif"_ c'est déjà le cas dans la base et le formulaire. Je ferai le changement pour l'import massif

**Comment by alemangui** [comment]
_" changer les définitions des types de production (remplacer par les propositions sur mattermost de @hfroot)"_ sera traité ici : https://github.com/betagouv/ma-cantine/issues/2255

**Comment by valeriemerle** [comment]
Aprés teledéclaration, est ce possible d'afficher pour le teledeclarant des informations qui lui permettent (et nous permettent par la suite dans l'anlayse) de vérifier la qualité des informations saisies. 
Par exemple : votre déclaration permet de calculer une valeur X en euros du repas. Si cette donnée est incorrecte, veuillez vérifier vos données d'achat
Par exemple les informations apportées sur le nombre de repas annuel et moyen par jour indique que votre cantine fonctionne X jours par an. Si cette donnée est incorrecte, veuillez vérifier vos données sur le nombre de repas

**Comment by valeriemerle** [comment]
Autres données nécessaires à rendre obligatoire dans le profil de cantine : 
Secteur d'activité
Mode de gestion (directe ou concédée)

**Comment by hfroot** [comment]
@JenniferStephan 

> si je me suis trompée et que je passe d'une cuisine centrale avec un nb de sat rempli; et que je passe en cuisine site : alors le champ "nb de sat" se grise mais le chiffre reste en base de données. A modifier : effacer le nb de sat ds la BDD. mettre un msg de confirmation à la validation des modifs ? "vous avez changé votre type de production ? confirmer oui / non"

pq est-ce que c'est un pb ? Quel type de requêtes est-ce que tu fais pour avoir un problème avec ça ?

**Comment by alemangui** [comment]
>  si je me suis trompée et que je passe d'une cuisine centrale avec un nb de sat rempli; et que je passe en cuisine site : alors le champ "nb de sat" se grise mais le chiffre reste en base de données. A modifier : effacer le nb de sat ds la BDD. mettre un msg de confirmation à la validation des modifs ? "vous avez changé votre type de production ? confirmer oui / non"

Ceci sera géré par les données fixées à l'intérieur de la TD

**Comment by hfroot** [comment]
Je ferme cet issu car on a decoupé les tâches restantes autre part
