### ISSUE TITLE
(MESURES-PHARES) modifs mesure PLASTIQUE

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2212]

**Comment by valeriemerle** [comment]
Aprés echange avec Maiwenn : Modifications à faire sur la page du site ma cantine sur la mesure "interdiction plastique" et sur la mesure gaspillage voir docs joints
[modif_site_mesuresEGAlim_plastique.docx](https://github.com/betagouv/ma-cantine/files/10517846/modif_site_mesuresEGAlim_plastique.docx)
[Uploading modif_site_mesuresEGAlim_gaspillage.docx…]()

**Comment by hfroot** [comment]
https://github.com/betagouv/ma-cantine/commit/6dcbb6c9324ea358efc9e9a9f2e8b7e80c4ee9f5
