### ISSUE TITLE
(landing page) mettre à jour le livret présentation de la loi

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2213]
[2208_Mesures-LoiEgalim_BRO_V3.pdf](https://github.com/betagouv/ma-cantine/files/10372405/2208_Mesures-LoiEgalim_BRO_V3.pdf)

<img width="1669" alt="Capture d’écran 2023-01-09 à 10 04 06" src="https://user-images.githubusercontent.com/36134318/211289985-37da6596-2b71-4ff7-a8a3-0aa4c9a8d165.png">

**Comment by alemangui** [comment]
Done :+1:
