### ISSUE TITLE
(API) demande d'infos

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2214]
- [ ] est-ce qu'il y a déjà des utilisateurs de l'API ? cb ? qui ? 
- [ ]  où en est-on des discussions avec logiciels

CARTE POUR CENTRALISER ET NIVELLER TOUTES NOS INFOS RESPECTIFS, À LA FOIS CÔTÉ DÉPLOIEMENT, PRODUIT ET DÉV :)

**Comment by hfroot** [comment]
Est-ce qu'on pourrait fermer cet issu vu qu'on a le trello maintenant ?
