### ISSUE TITLE
(extractions metabase) envoyer extractions pour les 2 expés à Maiwenn et Erwann

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2215]
lien query expé gaspi : https://ma-cantine-metabase.cleverapps.io/question/152

lien query expé végé :  https://ma-cantine-metabase.cleverapps.io/question/428

**Comment by gauthierandre** [comment]
J'ai mis un lien pour l'exp végé https://ma-cantine-metabase.cleverapps.io/question/428

**Comment by alemangui** [comment]
Suite aux différents échanges avec Maiwenn et Erwan je me permet de fermer cet issue
