### ISSUE TITLE
retours staging

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#224]
MAIL DE CONNEXION :

- [x] changer la phrase : "Vous avez demander vous connecter avec le site ma cantine. Pour completer votre demande, cliquez sur le bouton" par "Bonjour, vous avez demandé à vous connecter sur le site de ma cantine. Afin de valider votre demande, cliquez sur le bouton"
- [x] CTA : "Confirmer la connexion"

TABLEAU DE BORD SUITE A LA CONNEXION :

- [x] mettre plus en avant le fait que les données ont été sauvegardées; un encart/flash alert sous le titre tableau de bord. avec en texte "Les données que vous avez renseignées précédemment ont été sauvegardées. Vous pouvez les modifier en effectuant à nouveau l'auto-diagnostic "savoir où j'en suis". Votre tableau de bord sera mis à jour automatiquement."
- [x] Pour la publication des données, actuellement juste le CTA "publier les données" sans contexte. J'ajouterais en préambule. "Vous pouvez choisir de valoriser les démarches entreprises dans votre établissement en décidant de rendre publique vos données. Les informations que vous avez renseignées dans l'auto-diagnostic seront donc visible sur notre page /nos-cantines (mettre lien). C'est une page que vous pouvez partager avec vos élu.e.s, convives, personnels..."
- [x] pour l'encart "information sur ma cantine", changer de design : soit reprendre le formulaire de generation d'affiche avec les input soulignées sans encart gris (inspi : https://www.pretto.fr/); soit reprendre l'encart d'inscription d'Helene. 
- [x] pour l'encart "information sur ma cantine", ajouter en sous-titre : Mieux vous connaître. Dîtes-nous en un peu plus sur votre établissement. Cela permettra d'identifier facilement votre cantine parmi celles qui ont fait le choix de publier."

AUTODIAG/PUBLICATION : 

- [x] changer les encarts gris et les inputs rectangulaires, idem en prenant les memes que ceux de l'inscription ? border orange ?
- [x] changer la couleur du gris et meme pas sure qu'il y ait besoin de mettre en evidence, p-e juste blanc
- [x] si possible pour la mesure appro; mettre un tableau avec 2019 et 2020 en colonne et en ligne les questions "valeur total HT"; "valeur bio HT", "valeur durable HT", "valeur commerce equitable"
- [ ] Lutte contre le gaspillage alimentaire et dons alimentaires : ajouter un champ libre "Commentaires" ds cette section
- [x] pour la partie validation de publication, proposition design : 
<img width="339" alt="Capture d’écran 2021-05-14 à 17 43 03" src="https://user-images.githubusercontent.com/36134318/118295235-e81d3d80-b4db-11eb-8356-1e123244be78.png">
tick sur flaticon
+ ajouter en effet la phrase de opt-in "j'accepte" en enlevant le "tout le monde" juste "soient visibles".

Normal qu'en ayant effectué le parcours complet sous connexion, et en validant ma publication, je ne vois pas mon encart sur /nos-cantines ?? 

- [x] mettre "nos cantines" dans la navbar

**Comment by JenniferStephan** [comment]
- [ ] Quand on remplit les questions d'un bloc "je m'évalue" sur l'autodiagnostic, mettre en évidence sur le bouton que des réponses ont été enregistrées. De type, remplir le bouton ?

**Comment by JenniferStephan** [comment]
proposition icone: https://icones8.fr/icons/set/list

proposition de texte : 

"Vous avez rempli votre auto-diagnostic et les données ont bien été enregistrée. Vous pouvez à présent décider de rendre publiques ces données afin d'accroître la transparence pour vos convives, les élu.e.s de votre collectivité... 
Le cas échéant, un encart dédié à votre établissement apparaitra sur la page /nos-cantines. Seront mis en avant vos initiatives, indicateurs et démarches entreprises pour une alimentation plus saine et durable. 
C'est aussi un bon moyen de répondre à l'obligation réglementaire de télédéclaration des parts de produits bio et durables qui sera en vigueur dès fin 2022. (lien vers la mesure)

J'accepte... tick"

CTA

**Comment by hfroot** [comment]
J'ajoute "Lutte contre le gaspillage alimentaire et dons alimentaires : ajouter un champ libre "Commentaires" ds cette section" dans le jardin backlog pour l'avenir comme on a discuté.

**Comment by hfroot** [comment]
Le champ libre "Commentaires" est relier au #234
