### ISSUE TITLE
Page partenaire : ajout de la charte + texte

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2241]
Pour faire suite à ce qui a été décidé lors de notre séminaire : 

Pouvez-vous intégrer ce document sur la page partenaire. Il serait téléchargeable en cliquant sur le texte suivant : 
"Cliquez ici pour télécharger notre charte de référencement sur ma cantine"

[charte_referecement_Version01_janvier2023.pdf](https://github.com/betagouv/ma-cantine/files/10450230/charte_referecement_Version01_janvier2023.pdf)

On pourrait ajouter à l'endroit entouré : 
"Ces acteurs de la restauration collective au service des gestionnaires sont prêts pour vous aider à atteindre les objectifs de votre cantine. **Cette page n’engage pas l’administration ou l'équipe ma cantine ; elle constitue une proposition à l'attention des responsables légaux de restaurants collectifs. Les structures sont seules responsables de la véracité des informations qu’elles communiquent sur la page partenaire**."

**Comment by JenniferStephan** [comment]
Helen Root
[3:29 PM](https://mattermost.incubateur.net/betagouv/pl/i9ucs7tp13d3zdceiacc5om3ch)
@André est-ce que tu peux me donner plus de contexte de quel problème (et pour qui est-ce que c'est un pb) on resoudre avec le charte de referencement des acteurs de l'écosystème ? https://github.com/betagouv/ma-cantine/issues/2241 J'essaye d'ecrire qqch pour presenter le lien vers le telechargement du fichier dans un manière rapidement comprehensible.

GitHub
Page partenaire : ajout de la charte + texte · Issue #2241 · betagouv/ma-cantine
Pour faire suite à ce qui a été décidé lors de notre séminaire : Pouvez-vous intégrer ce document sur la page partenaire. Il serait téléchargeable en cliquant sur le texte suivant : "Cliquez i...

Page partenaire : ajout de la charte + texte · Issue #2241 · betagouv/ma-cantine
	
André
[3:37 PM](https://mattermost.incubateur.net/betagouv/pl/tdbgxjgmf3bn9f4owkpjusimrr)
La problème que résout la charte c'est comment on se positionne sur les personnes qui veulent être référencées sur la plateforme, et qu'elle est notre responsabilité envers eux. 

[3:38 PM](https://mattermost.incubateur.net/betagouv/pl/5kjyu3bid7fzicf7q4e8shr4uw)
En gros, je pourrais dire "Vous pouvez connaître la procédure relativement au référencement des prestataires en téléchargeant la charte de référencement"

[3:38 PM](https://mattermost.incubateur.net/betagouv/pl/m6mm16x38tnu9mottudfwop41w)
est-ce que ça te répond ?

	
Helen Root
[6:45 PM](https://mattermost.incubateur.net/betagouv/pl/hyy5gw5y8br5ixb6pifiw8n6xh)
Alors c’est un fichier axé acteur de l’écosystème plutôt que gestionnaire qui cherche les services ?

	
André
[8:56 PM](https://mattermost.incubateur.net/betagouv/pl/a7k8wbcbo3rq3j77e7g3ybzxcy)



Alors, c'est un peu les deux. En effet, il est plus à destination des acteurices mais il touche aussi les gestionnaires pour être transparent sur nos critères. tu le voyais comment toi ?

**Comment by JenniferStephan** [comment]
Perso j'aime bien le texte qu'André propose en début de charte plutôt. En texte rapide pour présenter le lien, j'aime bien : 

"En savoir plus sur les critères de référencement sur la charte ma cantine"

**Comment by gauthierandre** [comment]
@hfroot et @alemangui @JenniferStephan je n'ai pas mis à jour cette carte suite au point de coordination de mi-janvier sur la page partenaire : mais l'action liée à la charte a été stoppée ; du coup, il est peut-être trop tôt pour la mettre sur le site. Est-ce possible de l'enlever avec le texte qui en fait mention et qui indique notre absence de responsabilité ?

On pourrait garder cette partie et enlever le reste "Ces acteurs de la restauration collective au service des gestionnaires sont prêts pour vous aider à atteindre les objectifs de votre cantine. Cette page n’engage pas l’administration ou l'équipe ma cantine ; elle constitue une proposition à l'attention des responsables légaux de restaurants collectifs. " ?
