### ISSUE TITLE
Gestion de secteurs pour les cantines satellites

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#2242]

**Comment by JenniferStephan** [comment]
proposition sur la page de création de cantines : 

<img width="339" alt="Capture d’écran 2023-01-23 à 14 16 55" src="https://user-images.githubusercontent.com/36134318/214049570-4222c546-6637-4bfe-8597-afce4ed603dc.png">

problème : comment on gère les satellites qui ont plusieurs secteurs ?

**Comment by alemangui** [comment]
C'est déjà possible d'avoir l'information par secteur car les cuisines centrales rentrent leurs satellites. C'est donc faisable via SQL d'obtenir la répartition par secteur.

**Comment by valeriemerle** [comment]
Les satellites n'ont qu'un secteur par définition

**Comment by valeriemerle** [comment]
On pourrait pour les cuisines centrales demander d'indiquer le secteur majoritaire de production et les secteurs secondaires? Ce qui permettrait d'analyser les réponses de TD des CC en les rattachant à une secteur (ce n'a pas été le cas en 2022). A terme, les données seront ventilées par satellites donc on n'aura plus de pb de multi secteurs.

**Comment by valeriemerle** [comment]
Il faudrait rendre obligatoire aussi les informations apportées par une CC à ses satellites et rajouter le nombre de couvert par an (de façon id aux informations saisies quand on est une cuisine centrale)
![Capture d’écran 2023-01-30 093130](https://user-images.githubusercontent.com/73835224/215426500-c8ade219-5d75-49a5-b889-b97177abdbbd.png)
