### ISSUE TITLE
(CREATION / MODIF CANTINE) CHANGER LES LIBELLÉS DES TYPES DE PRODUCTION

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2255]
contexte : les termes "cuisines centrales" et "satellites" que nous employons sur ma-cantine dans les types de production correspondent à des réalités terrain différentes. du coup, les users ne se sentent pas concernés par ces termes. 

proposition de @hfroot sur mattermost suite à un atelier "cuisine centrale" : 

remplacer : 
<img width="657" alt="Capture d’écran 2023-01-23 à 14 22 51" src="https://user-images.githubusercontent.com/36134318/214050290-3eda4196-f75b-4bc6-a141-4fad4284230f.png">

par : 
![choice-canteen-type-proposition](https://user-images.githubusercontent.com/36134318/214050871-789a1779-c604-423a-ab33-6b3f0dd53553.png)

**Comment by hfroot** [comment]
To be done after https://github.com/betagouv/ma-cantine/pull/2289 is merged
