### ISSUE TITLE
dans la saisie simplifiée, rendre tous les champs obligatoires au remplissage; i.e. valeur totale; valeur bio; La valeur (en HT) de mes achats SIQO ("label rouge", AOP/AOC, IGP, STG); La valeur (en HT) de mes achats prenant en compte les coûts imputés aux externalités environnementales ou acquis sur la base de leurs performances en matière environnementale; La valeur (en HT) des autres achats EGAlim

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2259]

**Comment by JenniferStephan** [comment]
hello @alemangui et @hfroot 
on en est ou ? juste pour savoir si c'est déjà le cas :) 

+ je veux bien un tableau recap des champs comme ds les explications pr les imports

**Comment by hfroot** [comment]
que le total est obligatoire. Est-ce qu'on ne donne plus l'option aux utilisateurs alors de declarer "Je ne sais pas" ?

**Comment by JenniferStephan** [comment]
si pr le "je ne sais pas"
c'est une demande de rendre les champs obligatoires en gerant aussi le "je ne sais pas"
discuté entre alex et val qd j'étais en formation suite à la création de cette carte : https://github.com/betagouv/ma-cantine/issues/2204

**Comment by hfroot** [comment]
AMA vu qu'on n'a pas évoqué ce retour depuis un moment, on le gère et alors on n'a pas besoin de faire du travail là-dessus. Je tag @qloridant - si tu n'es pas d'acc avec moi n'hesites pas réouvrir la discussion
