### ISSUE TITLE
🐛(bug) (PUBLI) Les images publiées ne s'affichent pas en grand quand on clique dessus

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2264]
Les images publiées dans les fiches établissements ne s'agrandisse pas quand on clique dessus. 

Capture d'écran réalisée sur safari / firefox / chrome

<img width="1097" alt="Capture d’écran 2023-01-25 à 20 36 07" src="https://user-images.githubusercontent.com/85872944/214670412-c217626b-f0a6-4c8d-8c1a-af7c680d4a59.png">

**Comment by alemangui** [comment]
Il parait que les deux directives du carrousel ne sont plus reconnues :thinking: 
![image](https://user-images.githubusercontent.com/1225929/214872528-d677335d-dcd2-4aaf-a9d9-5359f59cbeab.png)
