### ISSUE TITLE
💡 (PAGE PARTENAIRES) AJOUT DU SECTEUR DANS LES CHAMPS SUR ADMIN

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2265]
Sur typeform, nous demandons aux futurs partenaires de renseigner leur territoire d'action ainsi que **leur secteur privilégié**. Dans les demandes actuelles, quelques-uns ne travaillent pas avec l'ensemble de la restau'co mais avec quelques-uns seulement. 

<img width="850" alt="Capture d’écran 2023-01-25 à 20 45 28" src="https://user-images.githubusercontent.com/85872944/214672417-124ad1f5-46ed-4e5b-b1cd-c373f962ab93.png">

Objectif : donner plus de visibilité à l'user suivant son secteur, pour avoir accès à des offres spécifiques et pertinentes. 

Proposition : ajouter une ligne avec des cases à cocher dans le formulaire sur admin, à la manière des "besoins comblés" : 
<img width="1059" alt="Capture d’écran 2023-01-25 à 20 44 47" src="https://user-images.githubusercontent.com/85872944/214673140-10fe9990-835c-4ad0-bdd6-1f5923f1142b.png">

**Comment by JenniferStephan** [comment]
Ça marche si on met et ds le typeform et ds l’admin la liste des sector.name
qu’on a en base de données ?
@andre et @alej

Le mer. 25 janv. 2023 à 20:50, gauthierandre ***@***.***> a
écrit :

**Comment by gauthierandre** [comment]
Avec les vacances, je n'ai pas vu passer cet échange. Est-ce que vous êtes ok pour en discuter @hfroot ?
