### ISSUE TITLE
Affichage des informations sur ma cantine

### ISSUE THREAD

**Issue by valeriemerle** [betagouv/ma-cantine#2282]
Actuellement deux pages permettent d'avoir des informations sur les informations des cantines : mesure de notre impact et nos données
parfois ces pages portent des informations proches 
Nombre total de cantines inscrites sur la plateforme : 21677 (page impact) /
mais parfois avec des données chiffrées différentes
16839 cantines si on considère la répartition par type sur un total de 21677 (manque ceux sans réponse)
Faut il ces deux types de page?

**Comment by valeriemerle** [comment]
Publication des données : Décalage entre le nombre de cantines sur le site dans la page "ma collectivité" et dans les autres pages "chiffres"
A discuter : ne faudrait il pas retenir en terme de publication uniquement les données TD pour eviter de mélanger des sources d'info "fiables" car validées par l'utilisateur aprés TD de celles saisies dans un diagn non TD?

**Comment by hfroot** [comment]
ajouté dans notion
