### ISSUE TITLE
(Stats) modifier indicateurs impact / centraliserr

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2284]
[Campagne de télédération 2023.docx](https://github.com/betagouv/ma-cantine/files/10544339/Campagne.de.telederation.2023.docx)

**Comment by JenniferStephan** [comment]
fichier envoyé mercredi 1er fev par Val pr la dgal en mode info
je veux bien qu'on liste les choses déjà faites et à faire d'ici fin de semaine, à 3 @hfroot et @alemangui si ok pr vs ? 
histoire qu'on ait le même niveau d'infos

**Comment by hfroot** [comment]
Le lien guide de saisie gitbook sera cette page après une MAJ ? https://ma-cantine-1.gitbook.io/ma-cantine-egalim/infos-generales-sur-contexte-r%C3%A9glementaire/master/procedure-campagne-de-remontee-des-donnees-2022 @JenniferStephan

**Comment by JenniferStephan** [comment]
@hfroot je viens de renommer la page et mis la version de cette année du guide (à modifier avec les captures écrans actuelles) 
le lien du coup sur la doc : https://ma-cantine-1.gitbook.io/ma-cantine-egalim/infos-generales-sur-contexte-r%C3%A9glementaire/master/procedure-campagne-de-remontee-des-donnees-2023

**Comment by JenniferStephan** [comment]
on peut meme mettre celui ci : https://app.gitbook.com/o/-MUSPOHqjcxjZrvcnPVR/s/-MSCF7Mdc8yfeIjMxMZr/infos-generales-sur-contexte-réglementaire/master/procedure-campagne-de-remontee-des-donnees-annuelle comme ca plus besoin d'avoir l'année ds l'url

**Comment by hfroot** [comment]
ajouté dans notion
