### ISSUE TITLE
changer les mails auto et tous les references de mail contact -> nouveau adresse support

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2286]
suite au séminaire du 1er février, j'ai créé l'adresse mail "support-egalim@beta.gouv.fr"; avec pr l'instant Val, Guillaume, Greta, Pauline et André
envoi d'un email test ce jour et attente de leur réception à toustes

**Comment by hfroot** [comment]
Note pour le moi de l'avenir : j'ai fait ça sur démo mais vu ce bug #2303 - je pense que c'est qqch avec la liste mais pas encore debuggé

**Comment by hfroot** [comment]
En attente d'aide de la communauté

**Comment by qloridant** [comment]
Obsolète
