### ISSUE TITLE
TD : ajouter texte pr pdts ayant plusieurs labels

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2287]
Suivant le niveau d'information disponible, vous pouvez choisir entre ces deux types de déclaration. Pour les achats des années 2021 et 2022, toutes les déclarations peuvent être remplies avec la "saisie simplifiée". Pour les données d'achats 2023, la "saisie simplifiée" sera accessible uniquement aux établissements de moins de 200 couverts/jour. 

Produit ayant plusieurs labels : la valeur d’achat de ce produit ne pourra être compté que dans une seule des 4 catégories ci-dessous. Par exemple, un produit à la fois biologique et label rouge ne sera comptabilisé que dans la catégorie 'bio'.

<img width="1465" alt="Capture d’écran 2023-02-02 à 10 45 05" src="https://user-images.githubusercontent.com/36134318/216289805-cc527e91-aef4-4653-8b06-7afbd47aecee.png">

**Comment by hfroot** [comment]
Comment c'est fait:

Pour simplifiée:

![Screenshot 2023-02-10 at 16 34 28](https://user-images.githubusercontent.com/9282816/218131438-46c05037-4ba9-4992-86b3-815d94cb4746.png)

Pour détaillée:
![Screenshot 2023-02-10 at 16 35 23](https://user-images.githubusercontent.com/9282816/218131648-798b08d3-469e-4e1c-bd07-8fe5b811f642.png)

**Comment by hfroot** [comment]
fait depuis cet issu : https://github.com/betagouv/ma-cantine/issues/2284
