### ISSUE TITLE
TD : en tant que cuisine centrale sur le form de création de satellites; ajouter les champs : SIRET sat, secteur (unique), couverts par jour, ET COUVERTS ANNUELLES en obligatoire

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2290]
<img width="1011" alt="Capture d’écran 2023-02-02 à 15 35 52" src="https://user-images.githubusercontent.com/36134318/216354197-de036fc8-30a5-4852-ac10-dbb357d3a2e6.png">

**Comment by hfroot** [comment]
Je crois que c'est fait
![Screenshot 2023-04-24 at 18 20 25](https://user-images.githubusercontent.com/9282816/234056915-70d290b6-fb56-4cf0-b9a9-a5ac51ab3fd2.png)
