### ISSUE TITLE
Permettre les montants achats e.g. XX.05

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2327]
Retour utilisateur par mail le 10 fev

Lorsque j’enregistre mes achats (espace de gestion/mes achats/ ajouter un produit) la case prix HT ne me permet pas de mettre un 0 après la virgule. Par exemple : 20.05 se transforme en 205

La virgule et le 0 sont automatiquement supprimés.

Mon navigateur est Firefox version 109.0.1 (64bits) et je suis sur un pc virtuel

**Comment by alemangui** [comment]
Je viens de tester sur Firefox 109.0.1 (64bits) et je n'arrive pas à reproduire le problème :thinking:
