### ISSUE TITLE
retours sur l'autodiag

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#234]
doc source : https://drive.google.com/file/d/1CP8GjweYGg4OVC3RipDM52uGoJ0K_D87/view?usp=sharing de Valerie :)

**encart question appro :** 

- [x] ajouter produits durable et de qualité (hors bio)
- [x] ajouter 'alimentaire" qd il manque
- [ ] ajouter 'je connais les valeurs' avant chaque texte
- [ ] ajouter une question : 
Je ne connais pas mes valeurs 1) 2019 ou 2) 2020
- [ ] ajouter un texte qui explique que le commerce équitable ne rentre pas dans les 50%

**gaspillage :** 

- [ ] il manque l'année
- [x] remplacer "plan d'action" par "démarche de lutte contre le gaspillage"
- [x] ajouter : "Les actions ci-dessous sont des exemples, vous pouvez indiquer si ce sont des actions que vous avez mises en place ou préciser ou ajouter ou d’autres actions :" avant la liste des exs d'actions
- [x] ajouter un champ libre "commentaires additionnels"
- [x] sur le don, ajouter : "Si ma cantine fabrique plus de 3 000 repas/j en moyenne, je propose une ou des conventions de dons à des associations habilitées d’aide alimentaire "

//// pas prio
- [x] avoir des indicateurs chiffrés : 
Je propose, de toutes façons, une ou des conventions de dons à des associations habilitées d’aide alimentaire 

Fréquence de dons (nombre de dons/an)
Quantité de denrées données par an
Type de denrées données :

**diversification :** 

- [x] ajouter le critère des cantines concernées par la loi : "Si ma cantine fabrique plus de 200 repas/j en moyenne, j'ai mis en place un plan pluriannuel de diversification des protéines incluant des alternatives à base de protéines végétales"

pas prio
- [x] Mon menu végétarien est à base :
De plats prêts à l’emploi
De légumes secs et céréales

- [ ] champ libre pour "commentaires"

**substitution :** 

- [x] ajouter "alimentaires" ds l'option : "Je n’utilise plus de contenants alimentaires de service en plastique"

**info convives :** 

- [x] question boolean : "J’informe mes convives sur la part de produits de qualité et durables, entrant dans la composition des repas servis, et sur les démarches d’acquisition de produits issus du commerce équitable"
- [x] ajouter un champ libre apres la liste des exs de communication convives
- [ ]  enlever le champ "mettre un lien", le remplacer par de l'upload de documents (type affiches, type gazette, capture ecran de l'intranet de l'ecole, site de la mairie..."
- [ ] ajouter des sous-titres : 
1. Information sur la qualité des approvisionnements :
2. Information sur la qualité nutritionnelle des repas : (avant la dernière querstion sur le plan alimentaire)

**TABLEAU DE BORD**

- [ ] ajouter le bloc beta-testeur apres le tableau de bord
- [x] enlever la croix rouge pr remplacer par un pouce vers le bas

**Comment by hfroot** [comment]
Questions : 

Jenn, est-ce que le design de la page diagnostic va être refait ? Je pense des retours comme "Difficile de naviguer entre en savoir plus et le formulaire de l’autodiag".

Est-ce que tu peux me donner plus de détail pour "ajouter un texte qui explique que le commerce équitable ne rentre pas dans les 50%" ? Quel texte, et où ?

Gaspillage : 

Pour l'année (et pour les autre diagnostics en générale) on maintenant utilise 2020. Est-ce que ça suffit d'ajouter "Pour l'année 2020..." avant les questions de gaspillage, diversification, plastiques, infos ou est-ce que Val veut un champ pour gaspillage pour choisir l'an ?

Pour clarifier : est-ce que la question "J'ai mis en place un plan d’actions adapté au diagnostic réalisé" doit être changée au "Mise en place d'un démarche de lutte contre le gaspillage" ?

Info convives : 

Est-ce que la question proposée "J’informe mes convives sur la part de produits de qualité et durables, entrant dans la composition des repas servis, et sur les démarches d’acquisition de produits issus du commerce équitable" remplace la question existante "Je communique sur la mise en place d'un plan alimentaire" ou elle est une question nouvelle ?

Est-ce que tu peux clarifier ce que ça veut dire "ajouter le bloc beta-testeur apres le tableau de bord" ? Il me semble que le bloc est là déjà, si on est sur le lien `/measures-phares` après le diag.

**Comment by alemangui** [comment]
> Jenn, est-ce que le design de la page diagnostic va être refait ? Je pense des retours comme "Difficile de naviguer entre en savoir plus et le formulaire de l’autodiag"

Just my two cents par rapport à l'autodiag : Je pense qu'on va rapidement s'attaquer à la refonte de cette page donc des modifs structurelles dessus ne seraient pas super rentables. Après bien sur on peut le faire s'il y a un besoin produit immédiat.

> Est-ce que tu peux clarifier ce que ça veut dire "ajouter le bloc beta-testeur apres le tableau de bord" ? Il me semble que le bloc est là déjà, si on est sur le lien /measures-phares après le diag.

Je pense que l'idée c'est de bouger ce formulaire dans _/mon-compte_, mais du coup j'aurais la même suggestion que pour l'auto-diag (d'attendre un peu la refonte si possible) :)

**Comment by alemangui** [comment]
Page modifiée avec l'espace "mes cantines"
