### ISSUE TITLE
S'assurer un min données satellites

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2342]
- difficult for CC to have to fill out lots of data in order to TD
- if satellites TD, could have difference in data between what the CC entered and what the satellite TDs
- How will the satellite info in CC list be used?

**Comment by alemangui** [comment]
À rajouter dans le formulaire d'ajout de la cantine satellite :
- nombre de repas par an

Normalement le ministère ne serait pas nécessaire (à vérifier)

**Comment by alemangui** [comment]
Je mets cette carte à "Done" suite à la discussion avec Jenn
