### ISSUE TITLE
Design affichage

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2388]
Je trouve le vocabulaire de l'affiche pas assez simple, et il y a des elements qui ne servent pas grande chose, alors je propose :

h1 : Qualité d'achats 2022
Suivi par une partie en savoir plus de l'établissement
h2: `Nom d'établissement`
Cet établissement `mode de production phrase` (e.g. "Cet établissement produit les repas sur place" ou "Cet établissement livre des repas à `10` cantines")
`100` repas servis sur place par jour
`localisation icon` `Nom de ville`

à droite: remplace l'image du cafe avec le logo cantine si renseigné, je vois pas la valeur d'avoir les deux en même temps (est-ce qu'il y a de valeur du tout de cet image ?)

h2: `Répartition des achats par catégorie EGAlim`
caption: En valeur d'achat

<camemberts>

h3: Comment identifier un produit de qualité et durable ?

<logos>

h3: Un mot du gestionnaire

<paragraphe rentré par l'utilisateur. Cette partie est conditionnel>

h3: Pourquoi je vois cet affiche ?

<paragraphe tel-quel avec code QR à droite>

**Comment by hfroot** [comment]
![Screenshot from 2023-02-24 10-56-03](https://user-images.githubusercontent.com/9282816/221152747-90934dc3-0dfb-407d-b589-0aac6b3c18f9.png)

**Comment by JenniferStephan** [comment]
je suis d'acc avec toutes tes propositions, je rajouterais bien un : 

- [ ] `PAT (Projet Alimentaire de Territoires)` en toutes lettres pour éviter le jargon
- [ ] un encart "Nos démarches :" comme sur /nos-cantines

<img width="653" alt="Capture d’écran 2023-02-27 à 12 42 08" src="https://user-images.githubusercontent.com/36134318/221555211-8e722249-7f41-4390-9452-45aae57eb843.png">

**Comment by paulineeyherabide** [comment]
Affichage de l'année en cours

**Comment by Greta712** [comment]
je valide tes propositions Helen, j'ai eu des demandes sur
-la possibilité de mettre le logo de la cantine (et aussi celui de ma cantine ? nan?  ça c'est moi)
-mettre en valeur les chiffres EGAlim  ( par exemple en 2022, x% en bio et X% en durable) et cela en gras dans un endroit bien visible
voila une proposition qui avait été faite 
![image](https://user-images.githubusercontent.com/93720869/221612589-47b6ea97-4dc5-4da0-97d8-2ac83c91a8bb.png)

**Comment by gauthierandre** [comment]
Il y a un bug sur l'affichage que j'avais documenté ici : https://github.com/betagouv/ma-cantine/issues/1212 
Pas de valeur pour moi d'avoir cette image quand pas de logo. 
- j'aime bien l'idée de Jenn' de reprendre les logos
- est-ce que le QR code renvoit à l'affiche ?
- Des utilisateurs m'avaient fait remarquer que le camembert laisse supposer que tout n'a pas été (car il y a une partie grisée) donc pour répondre à cette suggestion je mettrai comme sur la publication, le pourcentage tout seul avec les labels
