### ISSUE TITLE
🐛 bug sur les nombres décimaux dans l'outil de suivi d'achat et du diagnostic

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2401]
Suite à une conversation avec un utilisateur, nous avons remarqué que : 

* il est impossible de saisir un nombre décimal avec un 0 après le virgule (je ne peux pas le montrer car c'est automatiquement corrigé par un nombre entier : ex si j'essaie de mettre 670,06, la plateforme me corrige sur 670 dès que je tape un 0 après la virgule)

* de ce problème, un autre bug apparait : impossible de valider un total (pourtant exact) quand la somme des éléments est égale à un nombre avec un 0 après la virgule. Exemple ci-dessous : 

Le total est bien égal à 670,06 (c'est d'ailleurs le montant suggéré) mais l'erreur persiste. Par ailleurs, il est impossible de saisir manuellement 670,06 sur les cases du diagnostic non plus. 

<img width="863" alt="Capture d’écran 2023-02-28 à 15 22 34" src="https://user-images.githubusercontent.com/85872944/221883025-f829b9e1-4583-4d4d-847c-48f6716e570e.png">

Le problème est reconductible peu importe la cantine.

**Comment by alemangui** [comment]
Il paraît que cela arrive seulement sur Safari

**Comment by alemangui** [comment]
Super intéressant. Safari traite les modifications des champs `type="number"` différemment de tous les autres navigateurs.

Safari décide de ignorer la nouvelle valeur si elle est égale à la précédente, alors que les autres navigateurs ignorent l'ancienne valeur. Donc par exemple, _5_ et _5.0_ sont numériquement identiques. Donc c'est impossible sur Safari de mettre 5.05, car au moment d'arriver à 5.0, Safari voit que c'est pareil que 5. et remet la valeur antérieure.

Aujourd'hui, le `type=number` nous donne les petites flèches pour rentrer les chiffres. Ces flèches ne sont pas utilisées et d'après @gauthierandre sont plutôt gênantes. Donc on peut dans un premier temps utiliser seulement `v-model:number` pour nos champs numériques.

D'autres librairies ont eu le même souci : https://github.com/directus/directus/issues/10243
