### ISSUE TITLE
SUJET DONNEES - BILAN STATISTIQUE - ajout de stats sur le tableau de bord metabase "campagne #2"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2452]
### contexte : 
j'ai créé le tableau de bord "Campagne #2 de télédéclaration - achats de l'année 2022 déclarés en 2023" pour aider le traitement statistique de Val et Jonathan qui avait pr la première campagne, à l'aide d'une extraction, fait un travail manuel sur excel de filtrage, suppressions des doublons, analyse stats et tableaux croisés

### quoi : 

https://ma-cantine-metabase.cleverapps.io/dashboard/18
le but : avoir des indicateurs fiables, tps réel pour les remontées régulières
avoir une extraction pour fiabilisation des remplissages avec possibilité d'extraction des données brutes (question 450)

#### PRIO 1 🔥

- [ ] sur cette query, pr permettre l'extraction brute des données, ex : https://ma-cantine-metabase.cleverapps.io/question/450; modifier : 
          - [ ] "déplier"/cast/parse (je sais pas le terme) declared data pour avoir toutes les valeurs TD
          - [ ] ajouter le type de diag (complet et simple)

- [ ] sur le compte des % bio : ajouter les TDs complètes / idem sur le compte des % EGAlim (hors bio)
ici : https://ma-cantine-metabase.cleverapps.io/question/465
ici : https://ma-cantine-metabase.cleverapps.io/question/466
ici : https://ma-cantine-metabase.cleverapps.io/question/505
ici : https://ma-cantine-metabase.cleverapps.io/question/507

- [ ] ajouter la stat : "nb de cantines représentées par les TDs"; i.e. le nb de cantines centrales et sat qui ont une valeur totale (pas uniquement au sens de la CC)
ex : je suis une cuisine qui livre 4 satellites. je compte comme 1 TDs dans la question https://ma-cantine-metabase.cleverapps.io/question/449; je voudrais avoir aussi le chiffre total de "5 cantines représentées"

#### PRIO 2 🌤

- [ ] répartition TD simples versus complètes

#### PRIO 3 ❄️

- [ ] pour tous les graphes du tableaux, enlever le décompte de nos cantines tests (marginal car on a max 1 ou 2 cantines ayant TD en prod, mais pr être certaines, on peut ajouter un filtre à toutes les queries pr "is staff" = "false" sur le user manager)

**Comment by JenniferStephan** [comment]
questions à Helen : 

- ds les TD 2022, pr les complete; pq de tps en tps on a les value bio remplies avec le total et de tps en tps non ? https://ma-cantine-metabase.cleverapps.io/question/450
- comment gérer les variables avec des tableaux, type les siret des cuisines centrales ou les fréquences des menus végé
-

**Comment by qloridant** [comment]
Obsolète
