### ISSUE TITLE
SUJET DONNÉES - Extractions données brutes pour publication data.gouv.fr

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2453]
#### contexte : 
pour la transparence et la réutilisation des données
parce que condition données pour le FAST dans l'obtention du budget
on se doit de pouvoir publier les données brutes qui ont été traitées pour le bilan statistique

#### où ? 
https://www.data.gouv.fr/fr/datasets/?q=alimentation

#### quoi ? 

pour l'année 2021 : 

- [ ] SIRET cantine ayant TD et SIRET des sat concernées si CC a TD pr ses sat
- [ ] type de gestion (concédée / direct)
- [ ] type de production 
- [ ] nb de couverts à l'année
- [ ] nb de couverts moy par jour
- [ ] région de la cantine qui a TD
- [ ] département de la cantine qui a TD
- [ ] code insee de la cantine qui a TD
- [ ] % bio (calculé à partir de valeur bio / valeur totale) pr les simples et complètes
- [ ] % EGAlim hors bio 

#### autre usage : 
pourra être utilisé et communiqué aux chef(fe)s de pôle DRAAF en région (iels pourront trier par région)

**Comment by qloridant** [comment]
@JenniferStephan Est-ce qu'on bien accès au [compte du Ministère de l'Agriculture](https://www.data.gouv.fr/fr/organizations/ministere-de-l-agriculture-de-l-agroalimentaire-et-de-la-foret/) sur data.gouv.fr pour la publication ?

Il est aussi préférable de mettre en place dès le début un pipeline qui permet de rafraîchir les données régulièrement pour éviter d'avoir des données obsolètes. Je vais étudier cela

**Comment by qloridant** [comment]
Se pose la question d'ajouter également le montant des achats (en € ou en %)

**Comment by hfroot** [comment]
@qloridant on pourrait maintenant fermer cet issu ?
