### ISSUE TITLE
SUJET DONNÉES - CHIFFRES COLLECTIVITÉS - remplacer les chiffres des diags par les chiffres TD pr les % appros

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2454]
#### contexte : 
mal compris sur la page "chiffres ds ma collectivité", que l'on donne les chiffres des diags commencés. 

#### proposition : 

<img width="1545" alt="Capture d’écran 2023-03-20 à 17 14 07" src="https://user-images.githubusercontent.com/36134318/226403093-4d66dde4-3929-493f-9993-700c04a07009.png">

pour la partie appro, mettre uniquement le nb de cantines ayant TDs et le calcul du % de bio et de % EGAlim hors bio des TDs

pour la partie "autres mesures" on peut garder les données diag

**Comment by qloridant** [comment]
Ref dans Picardie
