### ISSUE TITLE
Modifs textes demandées par Val

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2456]
https://docs.google.com/document/d/1qBI7Pac5vT6G2sRcPiovPEufoqSOyFh0/edit#

- [x] Modification de la phrase soulignée : à supprimer
- [ ] « France continentale » (veut dire hors Corse) à changer pour « France métropolitaine » et aussi sur la page « les mesures Egalim » (on a fait exprès de pas dire "métropole" pcq ce n'est pas très fair pr les DROM-COM / hexagonale mieux pr toi @valeriemerle ?
- [x] « et a décidé sur une ou plus actions à faire » à changer pour « Et a mis en œuvre une ou des actions de lutte contre le gaspillage alimentaire »
- [x] « la cantine sert 3000 repas ou plus) à changer pour « Si la cantine sert au moins 3000 repas en moyenne par jour »
- [x] « un repas végétarien par jour pour les autres secteurs » à changer pour « et depuis janvier 2023, un repas végétarien par jour pour les restaurants collectifs de l'État, les établissements publics et les entreprises publiques nationales (s'ils proposent habituellement un choix multiple de menus) »
- [x] Page « nos cantines » : quand on affiche les informations d’une cantine
- [x] Pour informer l'établissement de l'absence de votre enfant à la pension du midi, utilisez votre site de « vie scolaire »
- [x] Quand on veut créer une cantine avec un numéro Siret qui existe dejà, on voit ce message
A corriger, coquille orthographique : vous pouvez cependant demander l’accès aux gestionnaires de …

**Comment by alemangui** [comment]
@JenniferStephan OK si on ferme cet issue ?

**Comment by hfroot** [comment]
Phrase tjs dans `BadgesExplanation` - à voir si on a besoin de MAJ le texte suite au changement de wording #4495
