### ISSUE TITLE
Emails automatiques pour la télédéclaration 

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2466]
Dans le cadre de la campagne de télé-déclaration, nous pourrions automatiser les campagnes pour booster la télé-déclaration pour les personnes qui ont statut "brouillon" de leur télé-déclaration 2022.

A) Envoi initial : 
- **Conditions** : 1) avoir réalisé un diagnostic 2022 avec des 2) valeurs HT : le total HT total, le total HT de bio. D'autres ? Moins ?
- **Exécution** : envoi du mail à J+7 une fois les conditions réunies (avoir un diagnostic 2022 + des données rentrées sur quelques champs de la TD)

B) Envoi de relance : 
- **Condition** : 1) ne pas avoir validé son diagnostic après 14J suivant le premier courriel. 

Les modèles sont sur sendinblue, sous les noms : 
- A) [J'ai créé un diagnostic mais je ne l'ai pas TD](https://my.sendinblue.com/camp/template/72/message-setup)
- B) [J'ai créé un diagnostic mais je ne l'ai pas TD_relance](https://my.sendinblue.com/camp/template/73/message-setup) 

Dans le template j'ai mis "nom de l'établissement" comme sur d'autres campagnes, mais je sais que c'est un champ personnalisé.

**Comment by hfroot** [comment]
@Greta712 @paulineeyherabide vous trouvez ça tjs utile pour la prochaine campagne ?

**Comment by Greta712** [comment]
Oui, ça serait pertinent de mettre en place l'automatisation pour ceux qui ont commencé à faire leur bilan. Car dans le cadre de l'enquête qu'on a mené auprès de ceux qui n'ont pas TD cette année, certains on juste oublié de TD alors qu'ils avaient leurs données.

**Comment by hfroot** [comment]
merci Greta - @Tdauvet89 comment tu veux qu'on suit cet addition - ici ou avec picardie ?

**Comment by Tdauvet89** [comment]
@hfroot je préfère suivre dans Picardie.
@alemangui est-ce qu'on pousse dans Brevo le statut de la TD ? Si oui, alors @Greta712 il n'y a pas de dev de notre coté. 
Si non, quelle estimation ?

Si non, alors amélioration Picardie à prendre en compte dans le trimestre qui rentre dans l'objectif Optimisation de l'équipe de déploiement pour la campagne de TD 💪

**Comment by hfroot** [comment]
ça marche ! Tu crées le ticket Picardie @Tdauvet89 ? Je ferme l'issu
