### ISSUE TITLE
bug : le logo n'apparait pas ds le téléchargement de l'affiche (mais existe bien ds l'aperçu)

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2486]
https://ma-cantine.agriculture.gouv.fr/modifier-ma-cantine/22480--ECOLE%20PRIMAIRE%20PUBLIQUE/modifier?etape=informations-cantine

<img width="1286" alt="Capture d’écran 2023-03-29 à 14 50 24" src="https://user-images.githubusercontent.com/36134318/228541422-b5c8dd92-949f-40f2-93a7-2079ab610dae.png">

<img width="1522" alt="Capture d’écran 2023-03-29 à 14 50 15" src="https://user-images.githubusercontent.com/36134318/228541499-97df2f21-ea00-461b-be16-a9b172e700b5.png">

**Comment by hfroot** [comment]
https://github.com/kempsteven/vue-html2pdf/issues/51
https://www.clever-cloud.com/doc/deploy/addon/cellar/#cors-configuration

![Screenshot 2023-03-29 at 21 08 22](https://user-images.githubusercontent.com/9282816/228642643-ccc4093e-3b68-4381-9582-9e17d345e0d1.png)

**Comment by hfroot** [comment]
C'est resolu
