### ISSUE TITLE
Bug ajout d'une cuisine centrale dans le nombre des cantines satellites.

### ISSUE THREAD

**Issue by Greta712** [betagouv/ma-cantine#2487]
le  responsable d’une cuisine centrale (SIRET :24420080400031) qui livre 11 satellites mais n’a pas de lieu en propre. Il a donc renseigné au niveau de sa cuisine centrale 11 satellites, il en a référencé 11 dans les satellites. Mais quand il souhaite télédéclarer, ça bloque car il est précisé qu’il n’a déclaré que 11/ 12 satellites.
Lorsque l’on regarde la liste des cantines satellites, la CC est comptabilisée. Est-ce normal?

**Comment by hfroot** [comment]
Merci - la raison c'est parce que la CC a renseigné son propre siret comme le siret de la CC aussi : https://ma-cantine-metabase.cleverapps.io/question/558

J'imagine à un moment la CC a declaré qu'elle reçois des repas et renseigné le SIRET, et après changé mode de production mais le central_producer_siret, le SIRET de la CC a resté dans le BDD.

Pour cet utilisateur tu peux aller dans l'admin de la CC et enlever le SIRET du champ "Siret de la cuisine centrale (si cuisine satellite) :".

Depuis la création de cette cantine on a mis en place le règle pour ne pas accepter le même SIRET dans les deux champs alors on devrait pas voir trop de ce pb.

Mais on pourrait carrément aussi améliorer la logique pour éviter ça à l'avenir

**Comment by hfroot** [comment]
https://ma-cantine-metabase.cleverapps.io/question/559
