### ISSUE TITLE
FAQ retours Val

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2499]
https://ma-cantine-staging.cleverapps.io/faq

**Comment by valeriemerle** [comment]
**Question à déplacer :**
Quels intérêts pour une SRC… : A mettre après je suis en gestion concédée…
Pourquoi, dans mon diagnostic, fournir les valeurs d’achat … : A mettre dans le paragraphe sur la loi
A qui les données d’achat sont-elles fournies… : A mettre dans le paragraphe sur la loi

**J’enlèverai la question pourquoi s’inscrire? puisque la question suivante est : est-ce obligatoire ?**
Je fusionne et ça donne : L’inscription sur la plateforme est-elle obligatoire ?
L’inscription des gestionnaires, responsables légaux d’un service de restauration (dans les secteurs public et privé) est obligatoire. Le décret du 23 avril 2019, pris en application de la loi EGAlim du 30 octobre 2018, prévoit la réalisation d’un bilan statistique de la mise en œuvre des obligations prévues par la loi, sur la base des éléments transmis, dans des conditions fixées par l'arrêté ministériel du 14 septembre 2022. Ce dernier précise la nature des informations à déclarer et le moyen de le faire par « ma cantine ». La plateforme permet également de bénéficier d'un accompagnement à la mise en place des mesures réglementaires des lois EGAlim et Climat et Résilience et de répondre aux obligations d’information des convives. 

**Je fusionnerai les questions sur le siret** et ça donnerait : Le SIRET st il obligatoire pour créer ma cantine ?
Oui. Il est possible de le trouver ici : https://annuaire-entreprises.data.gouv.fr/. Concernant les cantines scolaires, vous pouvez retrouver le SIRET de l’établissement rattaché à la cantine sur l’Annuaire de l’éducation : https://annuaire-education.fr/. Attention, il n’est pas possible d’ajouter plusieurs cantines sous un seul et même SIRET. Dans la plupart des cas, chaque cantine dispose de son numéro de SIRET propre. Dans certains cas, il est possible que certaines cantines n’aient pas de SIRET : dans ce cas uniquement, il est possible d’indiquer le numéro de SIRET de la collectivité desservant ces cantines. S’il existe déjà ou a été créé par une entité, je peux demander à rejoindre ma cantine.

**J’enlèverai la question ci-dessous** : 
Je représente une commune mais ne gère pas la restauration

Texte de questions à modifier
Comment sont vérifiées les obligations sur l’atteinte des taux EGAlim en restauration collective ?
A ce jour, la loi ne prévoit pas de sanctions, ni de contrôles pour ce qui concerne l'atteinte des taux EGAlim. Cependant la loi EGAlim et plus récemment la Climat et Résilience, prévoient un renforcement de la transparence vis-à-vis des convives avec notamment l’obligation d’une information des convives sur leur lieu de repas, des objectifs atteints en matière de produits durables et de qualité entrant dans la composition des repas (Art. L. 230-5-3 du code rural) et d’une information des citoyens au travers un bilan statistique annuel de l’application de ces objectifs, remis au Parlement par le Gouvernement et rendu public (Article L. 230-5-1 du code rural).

**Je rajouterai un nouveau paragraphe** : Transmission des données par ma cantine
Questions à y mettre :
Pourquoi dans mon diagnostic, fournir les valeurs..
A qui les données relatives aux achats…
J’utilise un outil de suivi des achats…
**Je rajouterai une nouvelle question** : je ne dispose pas d’outil pour le suivi de mes achats comment faire ?
Ma cantine propose un outil de suivi de ses achats, gratuit, en ligne et qui permet de restituer ses informations dans un tableau de bord et de procéder simplement à la télédéclaration annuelle de ses achats
Pour l’utiliser il faut se créer un compte.

**Coquilles :**
A moyen terme, les informations devront être attribuées à chaque **cuisines satellites**.

**Comment by Greta712** [comment]
Je rajouterai une réponse à la question : **que devons-nous renseigner dans le nombre de repas moyen par jour et à l'année ?** Il s'agit bien des repas qui sont fabriqués et servis mais pas du nombre de convives (par exemple :résidents, élèves, ou agents) et cela peut couvrir les services du midi et du soir. @valeriemerle qu'en penses-tu?

**Comment by Greta712** [comment]
La question est-ce que le pain rentre en compte? Les viandes, oeufs origine france rentre dans EGAlim? @valeriemerle  pertinent dans la FAQ?
