### ISSUE TITLE
Améliorations ajout satellite

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2508]
- pre remplir nom, localisation avec API
- améliorer messages pbs SIRET
- s'assurer qu'on demande tous les données obligatoires dans le petit formulaire

**Comment by hfroot** [comment]
Je propose qu'on decoupe en deux : lien avec l'API et check siret

**Comment by hfroot** [comment]
Tjs à faire :

- [ ] Si on gère le satellite, ajout-le direct ?
- [ ] Si le satellite est déjà lié, améliorer le message / n'affiche pas un message SIRET mais un pop up (comme les messages erreur/succès)

**Comment by alemangui** [comment]
Tous les éléments de cet issue sont faits :+1:
