### ISSUE TITLE
Verification de l'impact sur l'analyse de données

### ISSUE THREAD

**Issue by valeriemerle** [betagouv/ma-cantine#2510]
Il est possible que certaines cantines aient changé leur statut (passage de CC avec lieu de repas à CC sans lieu de repas). Une info a été donnée dans l premier cas sur le nombre de repas sur place. aprés changement de statu vers CC sans lie de repas, vérifier si les données prises en compte dans les requetes pour les indicateurs tiennent compte ou pas des changements. A vérifier aussi si des données d'achat ont été saisies par un satellite après qu'il ait été "revendiqués par une CC" qui a elle même saisie des données pour toute la CC.

**Comment by alemangui** [comment]
@valeriemerle suite au travail sur les stats, est-ce que cet issue est toujours d'actualité ou peut-on le fermer?
