### ISSUE TITLE
retours nouveau site

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#253]
https://ma-cantine-django.cleverapps.io/

<img width="341" alt="Capture d’écran 2021-06-09 à 11 49 02" src="https://user-images.githubusercontent.com/36134318/121333210-e303b080-c918-11eb-8d91-5cb70776b435.png">

- [x] ajouter le logo ministère agriculture en haut à gauche
- [x] ajouter le logo beta.gouv
- [x] ajouter la phrase et lien vers le formulaire de beta test "Site en expérimentation, devenez beta-testeur !"

<img width="448" alt="Capture d’écran 2021-06-09 à 11 50 37" src="https://user-images.githubusercontent.com/36134318/121333261-ef880900-c918-11eb-9cfc-2936b4821e3e.png">

- [x] on perd les logos quand on navigue ds le site; les remettre
<img width="476" alt="Capture d’écran 2021-06-09 à 11 51 29" src="https://user-images.githubusercontent.com/36134318/121333393-12b2b880-c919-11eb-95ad-ec9521190acf.png">

BARRE DE NAVIGATION

- [x] ajouter liens directs en mode menu déroulant comme pr le profil avec en dropdown actions : 
- Les mesures-phares
- Autodiagnostic
- Nos cantines
- Blog
- Documentation ressources

<img width="1085" alt="Capture d’écran 2021-06-09 à 11 54 53" src="https://user-images.githubusercontent.com/36134318/121333958-8c4aa680-c919-11eb-8a7b-0f7c9f4f6527.png">

- [ ] pour naviguer entre les mesures, quand un titre est sélectionné et hoover, le mettre en vert clair plutot que gris, qu'en penses-tu ? 

- [x] mettre le bouton "je donne mon avis" sur toutes les pages et en bas à droite (actuellement en bas à gauche et pas sur toutes les pages pr moi) 

<img width="487" alt="Capture d’écran 2021-06-09 à 11 56 45" src="https://user-images.githubusercontent.com/36134318/121334251-c9af3400-c919-11eb-961b-4010fb42e680.png">

TABLEAU DE BORD 

- [x] remplacer texte "Données d'approvisionnements en produits durables et de qualité" par "Données d'approvisionnement en produits de qualité et durables"
- [x] est-ce qu'on peut déjà ajouter les données appro prospectives 2021 et 2022 affichées si elles sont remplies apr l'utilisateur
- [ ] encart : "Diversification des menus" ajouter le lien vers le guide plan pluriannuel : https://ma-cantine-1.gitbook.io/ma-cantine-egalim/diversification-des-sources-de-proteines-et-menus-vegetariens/untitled
- [ ] encart appro : "Améliorer votre approvisionnement en produits de qualité et durable en recherchant par labels sur le moteur de recherche INAO" ds l'encart ressource de l'INAO
- [x] on peut mettre d'autres pouces ? 👍 👎

- [ ] encart gaspillage : rajouter la section qui renvoie vers le tableau Ademe optigede 
https://ma-cantine-1.gitbook.io/ma-cantine-egalim/lutte-contre-le-gaspillage-alimentaire-et-dons-alimentaires/tableau-de-diagnostic-optigede

**Comment by JenniferStephan** [comment]
création de compte

- [ ] demander le secteur de la cantine : 
<img width="345" alt="Capture d’écran 2021-06-09 à 12 07 54" src="https://user-images.githubusercontent.com/36134318/121335990-62927f00-c91b-11eb-9eb1-8d9c5e8951f5.png">

- [ ] enlever le contrôle "champ obligatoire" pr le SIRET

- [ ] basculer le bloc "nom utilisateur et mdp" après le bloc email et avant le bloc sur les infos cantine
<img width="325" alt="Capture d’écran 2021-06-09 à 12 08 50" src="https://user-images.githubusercontent.com/36134318/121336176-8e156980-c91b-11eb-844a-1418e2c8d8df.png">

- [ ]  sur la 404, pr le bouton, mettre plutot un bouton "retour" qui amène vers la page précédente
- [ ] ajouter une image sur la 404 👯 
https://unsplash.com/photos/OzAeZPNsLXk ?
https://unsplash.com/photos/E9kVmtiqqGE ? 
https://unsplash.com/photos/TKgOIwPVmkg ?

**Comment by JenniferStephan** [comment]
Page nos cantines : 

- sur les encarts, ajouter les graphes des diags 2020 ici : 
<img width="1037" alt="Capture d’écran 2021-06-09 à 12 23 22" src="https://user-images.githubusercontent.com/36134318/121338247-9cfd1b80-c91d-11eb-9c85-5af2230c5154.png">

page de publication

<img width="1014" alt="Capture d’écran 2021-06-09 à 12 25 07" src="https://user-images.githubusercontent.com/36134318/121338383-bef69e00-c91d-11eb-917c-eece8d491379.png">

- [ ] ajouter ds la phrase "Seront mis en avant vos initiatives, indicateurs et démarches entreprises pour une alimentation plus saine et durable." : "Seront mis en avant le résultat de votre auto-diagnostic; les initiatives mises en place, indicateurs et démarches entreprises pour une alimentation plus saine et durable."

**Comment by JenniferStephan** [comment]
ajouter ds la barre menu "profil"

- [ ] Générer mon affiche

**Comment by alemangui** [comment]
OK si l'ajout des nouveaux encarts est faite le sprint prochain ?

**Comment by JenniferStephan** [comment]
hello @alemangui @hfroot, dernière ajout de modif (sur ce batch de retours) : 

dans la partie autodiag pour les achats et appro : 

- [ ] ajouter la phrase : "Si vous ne connaissez pas une valeur, laissez le champ vide"

- [ ] entre les champs pour 2019 et les projections 2021 et 2022, ajouter un sous-titre : "Indiquez ci-après les montants estimés de produits durables et de qualité sur la base des actions mises en œuvre ou prévues (ex : renouvellement de marchés, modification de contrats d’approvisionnements, rationalisation des consommations évolution des grammages, etc."

<img width="705" alt="Capture d’écran 2021-06-10 à 16 34 21" src="https://user-images.githubusercontent.com/36134318/121544675-3275d980-ca0a-11eb-8a83-3d8b83534556.png">

**Comment by JenniferStephan** [comment]
la partie formulaire de la génération de l'affiche est petit par rapport à l'affiche

<img width="1339" alt="Capture d’écran 2021-06-11 à 10 23 01" src="https://user-images.githubusercontent.com/36134318/121657236-86330200-caa0-11eb-945d-383c31aefd56.png">

les cantines précédemment publiées n'ont pas migrées
