### ISSUE TITLE
ETQ gestionnaire, j'utilise l'outil de suivi achats comme un outil de simulation d'aide à la décision tout au long de l'année

### ISSUE THREAD

**Issue by arthurkleindesign** [betagouv/ma-cantine#2530]

**Comment by JenniferStephan** [comment]
les users stories associées à discuter et prioriser : 
ETQ gestionnaire,
- [ ] je veux avoir un aperçu d'où j'en suis de mes achats à un instant t sur : coût denrées total de l'année en cours; coût denrées total par famille de produits, coût denrées total par caractéristiques (bio, local, label rouge...)
- [ ] je veux pouvoir faire des tests/projections d'achats pour corriger/amender mes commandes à venir
- [ ] je veux avoir des recommandations sur les prix denrées des familles de produit que j'achète à mes fournisseurs 
sur ce sujet, on peut utiliser les grilles/tarifs publiés par FranceAgrimer pour aider à ne pas subir l'inflation et donner un ordre d'idée de cb "valent" les familles de produits = https://ma-cantine-1.gitbook.io/ma-cantine-egalim/au-moins-50-de-produits-de-qualite-et-durables-dont-20-de-bio/les-guides-marches-publics/referentiel-des-indices-de-prix-pour-les-marches-publics
j'ai en tête une visualisation du type "se loger" qui compare le loyer d'un bien à ceux équivalents : 
<img width="653" alt="Capture d’écran 2023-04-17 à 14 09 03" src="https://user-images.githubusercontent.com/36134318/232480218-206e9001-57f5-4a6d-95d3-213a5a273067.png">

- [ ] je veux pouvoir avoir un ordre d'idée de l'impact environnemental de mes achats
utilisation possible de agribalyse et la startup ecobalyse : ex de ce qu'iels ont fait sur le textile : https://api.gouv.fr/les-api/api-ecobalyse (en cours pr l'alimentaire) et jouer avec la BDD : https://agribalyse.ademe.fr/app

**Comment by arthurkleindesign** [comment]
[#2556](https://github.com/betagouv/ma-cantine/issues/2556)
