### ISSUE TITLE
ETQ tous, je reconnais l'identité visuelle de la marque 'ma cantine' dans tous ses territoires d'expression

### ISSUE THREAD

**Issue by arthurkleindesign** [betagouv/ma-cantine#2535]
Refonte du logo + création d'un petit set d'illustrations

**Comment by JenniferStephan** [comment]
constat : identité visuelle de ma-cantine fouillie et pas du tout homogènes; assez artisanale

**objectif : homogénéiser l'identité visuelle, accroître la cohérence graphique; pour avoir davantage d'impact et de légitimité institutionnelle pr un site en agriculture.gouv.fr**

**en termes d'assets :** 
- le logo "ma cantine" est une toque vectorisée sur [figma](https://www.figma.com/file/y9C3jpfHO0maP0kKr1zFNS/ma-cantine---design-kit-team-library?node-id=0-1&t=dXkMBvJAqwQ3wiy9-0) et une typo simple (ARCHIVO bold) mais certainement fois on réutilise l'ancien logo; une toque, mais pas la même évidemment
- la bannière linkedin
- les illus sur le site qui ont été prises sur une banque d'image mais qui ne fonctionne p-e plus très bien avec le sujet - gagneraient à être plus personnalisées 
évolution possible : un groupe de gestionnaire de cantines; un groupe de convives; des graphes pour évoquer le suivi d'achats + des ptits pictos ?
- les supports de présentation ont été à un moment uniformisés; est-ce que cela vaut le coup de lancer le chantier d'une trame unique ? 

**en termes de wording, nos taglines/motto/msgs-clés :** 
"mieux manger de la crèche à l'EHPAD"
"accélérer la transition alimentaire dans la restauration collective"
"de la transparence dans les assiettes"

**Comment by qloridant** [comment]
Done (logo, bannière linkedin...)
