### ISSUE TITLE
ETQ gestionnaire, je visualise l'avancée de mon point d'étape / diagnostic / bilan, et constate que la sauvegarde se fait en continu

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2550]
<img width="1019" alt="Capture d’écran 2023-04-17 à 16 05 02" src="https://user-images.githubusercontent.com/36134318/232508539-7d171c21-6a02-49c6-94f5-364735f974f3.png">

ajouter une type de gamification ? avec une liste d'actions à faire pour obtenir un % de complétion de l'espace de gestion

**Comment by JenniferStephan** [comment]
proposition de différentes étapes pour la jauge de complétion : 

0-10% = champs users compléter
10-30% = champs cantines (tous sauf les images) complétées
30-60% = champs appro complétés : 
       30-40% au moins : valeur totale + valeur bio 
       40-50% au moins une valeur ou un champ rempli ds les autres champs EGAlim ? 
       50-60% en plus de tout : valeur totale de viandes/volailles + valeur EGAlim pr cette famille
60-70% = au moins une autre mesure cochée sur les autres pilliers de la loi 
70%-80% = validation du point d'étape
puis publication yihoo 100%

**Comment by arthurkleindesign** [comment]
Attention 
- undo : https://alistapart.com/article/neveruseawarning/
- gestion des incohérences entre les champs

**Comment by hfroot** [comment]
On va pas avoir le sauvegarde en continu
