### ISSUE TITLE
Simplification de HeaderDropdownList.vue  avec data

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#256]
Nous pourrions avoir un template plus lisible en iterant sur un tableau de `data`, par exemple :  

```javascript
data() {
  return {
    buttons: [{
      text: "",
      icon: "",
      href: "",
      to: "",
    }, {
      text: "",
      icon: "",
      href: "",
      to: "",
    },
    ...
   ]
  }
}
```

**Comment by hfroot** [comment]
Et changer l'icone et texte pour le `mailto:contact@...`

**Comment by alemangui** [comment]
@hfroot  là dessus je pensais garder l'icône et le texte mais rediriger vers le lien de "Je donne mon avis" (pour que ça soit cohérent)
