### ISSUE TITLE
Design — Changement de wording pour la déclaration des satellites 

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2578]
Contexte : aujourd'hui, une cuisine centrale peut déclarer ces achats pour ces satellites pour une partie du diagnostic ou la totalité.
Une fois la déclaration faite, voici ce qui apparaît dans l'espace de gestion : 

<img width="1328" alt="Capture d’écran 2023-04-28 à 10 34 09" src="https://user-images.githubusercontent.com/85872944/235112510-9f1d27bd-a2f3-4ee1-a311-8ad9837af425.png">

Problème pour l'user : 
Cas 1) Si on peut comprendre pourquoi le "non-télédéclarée" apparaît quand la CC n'a fait que le diagnostic achat, ça reste confusant pour une personne en gestionnaire en cuisine centrale car ça laisse penser que le diag n'a pas été déclaré alors que c'est le cas. Plusieurs remontées ont été faites de personnes se demandant si tout était bien validé.

Par ailleurs, comme la déclaration ne concerne que les appro', est-ce qu'on peut laisser les personnes déclarer les autres données ? À débat donc, ça dépend du point de vue.

2) Toutefois, même quand la cuisine centrale fait un diagnostic complet, on a le même affichage. Et quand je clique pour faire ma déclaration, voilà ce qui apparaît : 

<img width="1344" alt="Capture d’écran 2023-04-28 à 10 33 58" src="https://user-images.githubusercontent.com/85872944/235113034-2051bbde-d177-4f28-92f7-22b06d056392.png">

Je pense que pour ce second cas, il faudrait changer le wording et mettre "télédéclaré" pour le satellite. Car pour le coup, il n'y a rien d'autre à réaliser.

**Comment by alemangui** [comment]
Merci @gauthierandre, très bonne remarque.

Déjà dans un premier temps je propose de ne pas afficher la pastille "Télédeclaration" pour les satellites pour qui la CC a fait un diagnostic. Ça évite le coté trompeur de la UI.

On pourra peaufiner plus tard pour prendre en considération les diagnostics partiels etc.
