### ISSUE TITLE
[Question] raccordement ville / département pour les cuisines satellites

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2659]
Depuis quelques jours, j'ai repris pas mal de cantines avec gestionnaires sur admin, car sans département. Pendant ce travail, j'ai remarqué qu'il y avait, en tout cas en 2023, quelque chose d'assez systématique. 

J'observe que bcp de cuisines satellites qui ont été importées par une CC n'ont pas de département, ni ville, ni code insee. Pour autant, il me semble qu'il y a ce champ exigé pour l'import. 
Comme peut-on faire pour s'assurer que ça apparaisse bien ? 

La cuisine centrale, quant à elle, est bien liée à un département. 
Je peux vous partager des SIRET en cas de besoin.

**Comment by hfroot** [comment]
@alemangui est-ce qu'on pourrait fermer cet issu ?
