### ISSUE TITLE
Recommendations / suggestions personalisées pour les cantines

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#2683]

**Comment by hfroot** [comment]
Les ressources qu'on a déjà :

- blog
- webinaires enregistrés
- webinaires à venir
- groupe facebook
- page acteurs de l'éco-système
- cantines publiées
- stats d'un territoire
- generateur affiche
- bcp dans gitbook
- FAQ

**Comment by hfroot** [comment]
Catégorie de ressource :

- nouvelle utilisatrice (comment créer/importer des cantines/achats/diags)
  - vidéo: comment créer/importer des cantines (si aucune)
  - vidéo: comment créer/importer des achats (si aucun)
- appro
- gaspi
- diversification
- plastiques
- infos
- coût ?
- obligations
  - vidéos des obligations differents pour des types de cantine differents

**Comment by hfroot** [comment]
Analyse diagnostic : https://docs.google.com/presentation/d/1NS5PkX1Rx-ACuSMoFacp2x1aFcffFrv6GVd6-W6dRwc/edit?usp=sharing

**Comment by qloridant** [comment]
Travail en cours (voir [notion](https://www.notion.so/Ressources-v2-0-3ca9f4c8129f4e9db90da7dcedb740bf))
