### ISSUE TITLE
nos-cantines : ajouter un filtre "commune" ou EPCI

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#2702]
ETQ Mme X élue de la commune Bègles, je voudrais voir si mes établissements sont inscrits

**Comment by alemangui** [comment]
Possibles pistes : 
https://geo.api.gouv.fr/decoupage-administratif/communes
https://geo.api.gouv.fr/decoupage-administratif/epcis

Très probablement besoin d'un autocomplete backend car nombre trop important de communces/EPCIs

**Comment by alemangui** [comment]
_" je voudrais voir si mes établissements sont inscrits"_ D'ailleurs un filtre ne l'aidera probablement pas car les cantines inscrites non-publiées ne s'afficheront pas

**Comment by qloridant** [comment]
Au final qu'est ce que qui avait été fait pour cette issue ?
On peut fermer ?

**Comment by hfroot** [comment]
On a maintenant un filtre par commune alors je ferme l'issu
