### ISSUE TITLE
AttributeError: 'UnicodeDecodeError' object has no attribute 'message'

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#2736]
https://github.com/betagouv/ma-cantine/blob/be35170aad5dfb8c20848bb538ec82825eeae76b/api/views/diagnosticimport.py#L63C13-L63C32

https://github.com/betagouv/ma-cantine/blob/be35170aad5dfb8c20848bb538ec82825eeae76b/api/views/purchaseimport.py#L45

Sur cette ligne, `message` n'est pas un attribut de `UncodeDecodeError`.

`File "/home/bas/..././api/views/diagnosticimport.py", line 67, in post#012    message = e.message#012AttributeError: 'UnicodeDecodeError' object has no attribute 'message' `

**Comment by qloridant** [comment]
Bug corrigé
