### ISSUE TITLE
Import de masse cuisine centrale / satellites

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#2749]
## Import CSV spécifique CC/Satellite

Après discussion avec des éditeurs logiciel, nous avons identifié un cas d'usage pour un import de masse concernant les cuisines centrales et ses satellites dans le même fichier. Ceci permettrait :
- Maintenir à jour le nombre de satellites et leurs infos avec un seul fichier (par ex., si le nombre de satellites change d'année en année - avec certains qui s'en vont et d'autres qu'arrivent)
- Ajouter les données d'appro au niveau de la cuisine centrale avec le même fichier

#### Structure CSV

Une possibilité de structure serait : 
| Type         | Siret | nom de la cantine | ... | ... |
|--------------|:-----:|-----------:|-----------:|-----------:|
| Cuisine centrale | siret      | name        | ...        | données appro        |
| Satellite 1 | siret      | name        | ...        |         |
| Satellite 2 | siret      | name        | ...        |         |
| Satellite 3 | siret      | name        | ...        |         |

L'idée étant de vérifier que le nombre de satellites indiqués au niveau de la cuisine centrale corresponde bien au nombre de lignes des satellites. 
- Les satellites non présents seraient enlevés de la cuisine centrale
- Les cantines ou CCs non existantes seraient créées
- Les cantines ou CCs existantes seraient mises à jour

#### Questions
- Est-ce qu'on envisage un fichier par CC ? Ou souhaite-on pouvoir importer plusieurs CCs et satellites avec le même fichier ? (à voir si c'est plus simple commencer par le premier cas et puis évoluer vers le second)
- Est-ce souhaitable de garder les mêmes trois modalités que pour les cantines site ? (établissements seuls, données d'appro simplifiées, données d'appro complètes)

#### Tâches techniques
- [x] Pages UI avec la documentation
- [x] Fichiers modèle
- [x] Fichiers pour tests
- [x] Test backend
- [x] Endpoint API / DRF View / Appel JS 
- [x] Endpoint API

**Comment by gauthierandre** [comment]
Aujourd'hui, avec le fichier d'import actuel, on peut prendre la structure que tu proposes.

Ex : la ligne 1 est la CC, les autres les CS. La seule différence est dans le mode de production, et que dans les CS le SIRET de la CC apparaît dans CC SIRET.

Est-ce que dans ton exemple, il faudra ajouter une colonne "satellite count" à remplir que pour la CC, mais qui agirait sur l'ensemble du fichier comme tu l'énonces ? Je pense que dans ce cas, oui il faudrait que d'office : 

- Les cantines ou CCs non existantes seraient créées

- Les cantines ou CCs existantes seraient mises à jour

Pour "effacer les satellites non présents" : est-ce qu'une fenêtre pourrait s'ouvrir avant validation pour dire quelque chose du genre "vous avez renseigné X SIRET sur X attendus ou sur X présents sur ma cantine, voulez-vous que nous effacions de ma cantine ceux absent de votre import ?"  
Généralement les fichiers d'import sont complets mais on sait jamais.

**Comment by alemangui** [comment]
Merci pour ces clarifications @gauthierandre !

Concernant _effacer les satellites non présents_, je me suis mal exprimé. Nous ne les effacerons pas de la base de données, simplement on enlèverait leur `central_producer_siret` - mais l'établissement sera encore là. De plus, on peut ajouter un log pour pouvoir monitorer quand ce cas arrive.

D'accord avec toi pour dire que l'import des établissements seuls n'est pas très intéressant (et déjà possible avec l'autre import CSV). Ce qui n'est pas possible aujourd'hui c'est d'ajouter les données d'appro seulement pour la cuisine centrale et non pas pour les autres.
