### ISSUE TITLE
Améliorer l'import en masse d'achats pour mieux gérer des gros fichiers

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2761]
- n'utilise pas `file.read()` pour éviter lire tout le fichier en memory https://docs.djangoproject.com/en/4.2/ref/files/uploads/
- utilise `bulk_create` pour reduire les operations SQL https://betterprogramming.pub/3-techniques-for-importing-large-csv-files-into-a-django-app-2b6e5e47dba0
- pour le hash, https://stackoverflow.com/a/1131255
- créer un index sur le SIRET des cantines
- cache les cantines (aujourd'hui pour chaque achats on fait un `get` sur le siret de la cantine, mais j'imagine un import concerne que quelques cantines)
- rendre l'endpoint asynchro ? p-e c'est difficile avec la gestion d'erreurs. Pour ça on aurait besoin de faire qqch plus sophistiqué comme un view avec l'historique d'imports etc mais je sais pas si c'est une fonctionnalité qu'on veut prioriser.

```
        file_chunks = file.chunks() # uses default chunk size of 64 KB
        for chunk in file_chunks:
             m.update(chunk)
```

**Comment by qloridant** [comment]
Pour la partie asynchrone : avec un collègue on a implémenté cela pour le projet [Validata Json](https://git.opendatafrance.net/validata/validata-json)
On valide des gros fichiers JSON en utilisant celery pour gérer les tasks. 

Clairement ca va compliquer le système. On pourra éventuellement mesurer le temps en synchrone avec les chunks et puis décider ?

**Comment by qloridant** [comment]
Si jamais on passe en chunk, on ne pourra pas checker l'unicité du fichier sans processer tout les chunks.
Nous avons donc deux choix : 
* Faire ce check après les traitement. En effet, une fois tout le traitement effectué, la vérification permet encore de ne pas surcharger l'API inutilement.
* Faire une première passe pour calculer le hash. Lancer `treat_csv_file` dans un deuxième temps, que si le check est valide. Cela implique de parcourir le fichier deux fois.

**Comment by qloridant** [comment]
Après discussion avec @alemangui : préf pour le choix 1) pour maximiser les cas où les utilisateurs déposent bien des fichiers différents.
