### ISSUE TITLE
[fonctionnalité] randomisation de l'apparition des cartes "acteurices" dans la page "acteurices de l'éco-système"

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2763]
La note produite pour le sponsor affirme qu'il n'y a presque aucun risque pour l'administration liés à l'existence d'une page "partenaires". Pour rassurer, nous avons présenté la possibilité de "randomiser" le mode d'apparition des partenaires.

En "randomisant", les partenaires n'apparaissent plus, comme aujourd'hui, par nom, ni même par dates d'ajout, mais **quasi-aléatoirement**.

**Comment by alemangui** [comment]
Suite à notre discussion, on a repéré un potentiel souci d'UX avec l'approche randomisée.

Si l'utilisateur commence à regarder un par un les partenaires, et à chaque fois qu'iel revient en arrière l'ordre est changé (voir les partenaires affichés sont autres), ça peut être assez frustrant.

C'est un peu comme si vous cherchez quelque chose sur Google, vous cliquez sur le premier lien, puis revenez en arrière, et là les résultats sont complètement différents.

Une possible solution à ça c'est que le front-end créé une clé de randomisation par session - ça donnerait une stabilité lors d'une même session. Mais le problème persisterait s'iel ferme le navigateur ou change d'ordi. Par ex, si une personne voit un partenaire intéressant et le lendemain veut le montrer à son équipe, cette personne ne le trouverait plus en utilisant les même filtres.

En résumé, cette feature me semble un peu contre-intuitive et en opposition au [principe de moindre suprise (UX)](https://fr.wikipedia.org/wiki/Principe_de_moindre_surprise). On peut arbitrer à quel point c'est nécessaire et à quel point une stabilité par session serait souhaitable.

**Comment by hfroot** [comment]
On a discuté ce sujet et on pourrait faire un seed de randomisation selon l'id utilisateur - comme ça un.e utilisateurice va toujours voir le même ordre, mais parmi utilisateurices tout le monde va voir un ordre different

**Comment by hfroot** [comment]
https://stackoverflow.com/questions/4022535/how-to-have-a-random-order-on-a-set-of-objects-with-paging-in-django
