### ISSUE TITLE
Nouveau paragraphe sur la page "acteurs de l'éco-système" + chartes

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2775]
Contexte : pour faire suite à la validation du service par le BPAL comme expérimentation sur six mois, il est important de porter cette information à l'attention des utilisateurices. Cet avertissement doit apparaître en haut de la page, à la manière des informations pendant la campagne de TD dans l'espace de gestion.

Voici le paragraphe proposé par Valérie : 

"Cette page correspond à un service proposé par l’équipe « ma cantine » qui va être expérimenté de nouveau pendant 6 mois. L’objectif est de permettre aux gestionnaires de restauration collective de trouver une aide et des ressources pour atteindre les obligations et leurs objectifs en ce qui concerne la durabilité de la transition alimentaire dans leurs cantines grâce à un catalogue d’acteurs qui se sont référencés en respectant les critères de référencement décris dans la charte (lien).

Cette page n’engage pas l’administration ou l'équipe ma cantine ; elle constitue une proposition à l'attention des responsables légaux de restaurants collectifs."

Exemple : 

<img width="1173" alt="Capture d’écran 2023-07-19 à 16 05 37" src="https://github.com/betagouv/ma-cantine/assets/85872944/1b327e47-1e87-4243-b973-6539444e1ced">

La charte en version PDF : 

[charte referencement.pdf](https://github.com/betagouv/ma-cantine/files/12095978/charte.referencement.pdf)

**Comment by alemangui** [comment]
Le paragraphe me semble très long, surtout pour des écrans plus petites. On peut essayer de le raccourcir : 

> Cette page correspond à un service proposé par l’équipe « ma cantine » qui va être expérimenté de nouveau pendant 6 mois. L’objectif est de permettre aux gestionnaires de restauration collective de trouver une aide et des ressources pour atteindre les obligations et leurs objectifs en ce qui concerne la durabilité de la transition alimentaire dans leurs cantines grâce à un catalogue d’acteurs qui se sont référencés en respectant les critères de référencement décris dans la charte (lien).

Plutôt :

> Ce service est expérimental. Les acteurs ci-dessous se sont référencés eux mêmes en respectant notre charte (lien).

**Comment by gauthierandre** [comment]
Je te rejoins, c'est un peu long. On pourrait ajouter la date de l'EXP.

"Ce service est en expérimentation jusqu'à décembre 2023. Les acteurs ci-dessous se sont référencés eux mêmes en respectant notre charte (lien)."

**Comment by hfroot** [comment]
@gauthierandre pour info p-e on a besoin de mettre à jour la charte car il y a un lien vers le formulaire typeform ?

**Comment by gauthierandre** [comment]
Ok @hfroot merci ! j'en parle demain à Valérie car peut-être qu'il faudrait ajouter le fait que c'est une expérimentation, aussi. je maj demain dès que j'ai un retour

**Comment by gauthierandre** [comment]
"Ce service est en expérimentation pendant six mois. Les acteurs ci-dessous se sont référencés eux mêmes en respectant notre charte (lien).

Cette page n’engage pas l’administration ou l'équipe ma cantine ; elle constitue une proposition à l'attention des responsables légaux de restaurants collectifs."

**Comment by gauthierandre** [comment]
@alemangui paragraphe plus court et la dernière phrase est obligatoire.
