### ISSUE TITLE
Possibilité de télédéclarer à enlever

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#2776]
Je faisais un test en partage d'écran avec une utilisatrice (qui veux comprendre pourquoi tous ces achats n'ont pas été pris en compte). Je m'aperçois qu'il y a encore une option qui propose de télédéclarer (ça expliquerait pq le chiffre à bouger ces derniers jours).

**Écran 1 :** 

<img width="791" alt="Capture d’écran 2023-07-19 à 17 02 33" src="https://github.com/betagouv/ma-cantine/assets/85872944/6f1d7049-30b7-4b3d-8c2e-935e7ddfef77">

**Écran 2 :** 

<img width="975" alt="Capture d’écran 2023-07-19 à 17 04 06" src="https://github.com/betagouv/ma-cantine/assets/85872944/dd7e8ad1-c1c8-4ba6-b6e6-9019d19a500d">

**Écran 3 :** 

<img width="427" alt="Capture d’écran 2023-07-19 à 17 04 41" src="https://github.com/betagouv/ma-cantine/assets/85872944/58b08509-76fa-4f9d-836d-8c02d39ffd77">

**Écran 4 :** 
Je ne peux pas annuler la TD (SO SORRY 😭)

<img width="1236" alt="Capture d’écran 2023-07-19 à 17 06 10" src="https://github.com/betagouv/ma-cantine/assets/85872944/965e0581-9c0c-46e6-9b89-b29b9424e8f8">

**Comment by qloridant** [comment]
La TD crée pour l'exemple est valide ou on la supprime en BDD ?
Je  vais fermé le ticket car nous ferons la modification ici #2777
