### ISSUE TITLE
Pb telechargement PDF

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2790]
Remonte par @paulineeyherabide 

:grimacing: J'ai l'user... qui n'arrive pas dld les contenus pdf sur ma cantine depuis avril/mai : les fenêtres ne s'ouvrent pas et quand elle fait son clic droit, le dld se fait sous format page web. Elle a essayé sous Mozilla et Chrome. Elle a deux logiciels pdf Adobe et Foxit. Elle a essayé de dld sur d'autres sites et ça fonctionne. Elle a un pare-feu sur son pro. Des idées ?

**Comment by alemangui** [comment]
S'il s'agit du contenu gitbook ce serait hors scope de notre application (dans le sens de ce repo). On peut voir avec l'utilisatrice ses paramètres (pare-feu, navigateur, etc), mais ce ne serait pas un issue de ce repo.
