### ISSUE TITLE
P03 1.1 icon X fermature de notification

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#2839]
(J'imagine c'est les deux icones dans NotificationSnackbar.vue)

Corrections à apporter au niveau des balises <svg> des croix de fermeture des notifications "toasts" :

1. Supprimer aria-hidden="true".
2. Ajouter un attribut aria-label="Fermer".

Pour obtenir concrètement :

`<svg role="img" aria-label="Fermer"></svg>`

**Comment by hfroot** [comment]
Relié P03 13.1

```
Actuellement les notifications de type "toasts" disparaissent automatiquement après quelques secondes. Ce qui n'est pas conforme.

Pour y remédier supprimer la disparition automatique et laisser la possibilité de fermer ces "toasts" via la croix de fermeture.
```

**Comment by alemangui** [comment]
Est-ce grave si ces éléments sont dans le `span` parent et non pas sur le svg lui même ?
![image](https://github.com/betagouv/ma-cantine/assets/1225929/d8d76e0c-e429-404f-a647-efe7c57b8bdf)
