### ISSUE TITLE
Découper les secteurs en secteur principaux et secondaires

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#2930]
Les cuisines centrales ont généralement un secteur principal et un ou des secteurs secondaires.
Il serait possible de représenter cela en base afin d'avoir une meilleur représentation de cette réalité.

Les cuisines non centrales ne peuvent avoir qu'un secteur. Il serait possible d'ajouter un blocage pour ne pas en renseigner plusieurs.

**Comment by alemangui** [comment]
J'ai l'impression que ce sujet revient sans cesse depuis un an à peu près, mais plusieurs fois on a décidé de ne pas le faire car :
- Il y a en effet des établissements qui ont plus d'un secteur et des cantines qui n'arrivent pas à définir un secteur principal,
- La raison derrière est statistique, c'est une contrainte de plus qui n'a pas de valeur ajouté pour l'utilisateur,
- C'est une pente qui mène à encore plus de complexité : ce serait quoi le secteur secondaire ? et le tertiaire ?...

Dans l'idéal on peut définir ce que cette évolution cherche à combler comme besoin pour pouvoir envisager une solution plus adaptée
