### ISSUE TITLE
Versionner nos release

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#2939]
# Contexte
Aujourd'hui nous prévenons le reste de l'équipe des nouveautés sur mattermost.

# Problème
Il est difficile de retrouver l'historique des nouveautés.

# Solutionner
Mettre en oeuvre des release et un changelog. Voir doc [github](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

**Comment by alemangui** [comment]
@qloridant suite à ta création de https://github.com/betagouv/ma-cantine/releases/tag/2023-09-01-2 je me permets de fermer
