### ISSUE TITLE
Mélange incorrect des informations de publication pour une cantine satellite

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#2940]
Liée à #2909 
Lors qu'une cantine satellite a un diagnostic propre à elle et en même temps un diagnostic venant de sa cuisine centrale, la UI mélange les valeurs des deux. 

Exemple : 
- Cuisine satellite publiée ayant un diagnostic avec **10% bio**, **10% de qualité et durables**
- Cuisine centrale ayant **100% bio**, **0% de qualité et durables**

Dans la publication, on s'attend à voir le diagnostic de la cuisine centrale, çad 100% bio, 0% qualité et durable. Pourtant, on a :

![image](https://github.com/betagouv/ma-cantine/assets/1225929/3d18a0d0-27ac-4c18-a40f-852b65e9a7b1)

**Comment by qloridant** [comment]
@alemangui pourquoi on s'attend à voir le diagnostic de la cuisine centrale ? Pourquoi pas le diagnostic du satellite ou les deux ?

**Comment by alemangui** [comment]
@qloridant La cuisine centrale peut choisir de faire le diagnostic pour ses satellites. En effet, sur certains cas (comme celui décrit dans cet issue) on a aussi un diagnostic préexistant de la cantine satellite et donc deux informations potentiellement en conflit l'une avec l'autre.

La décision produit était de mettre la priorité sur le diag de la cuisine centrale. Le problème était qu'on ne faisait pas ça proprement - on mélangait certaines infos du satellite et certaines de la cuisine centrale.
