### ISSUE TITLE
Widget vitrine : Établir une fenêtre de temps pour le nombre de visites et le rendre clair à l'utilisateur

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3037]

**Comment by hfroot** [comment]
@arthurkleindesign on s'est dit que ça serait cool de montrer à l'utilisateur la fenêtre de temps utilisée pour le nombre de visiteurs - genre `Nombre de visiteurs (dernière 6 mois)`. T'as un préference sur comment on rajoute ce petit morceau de texte dans le widget ?

**Comment by arthurkleindesign** [comment]
Oui bien vu ! C'est ajouté dans les maquettes :)
