### ISSUE TITLE
Quoi faire avec la partie mes ressources dans lot 1 ?

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3066]
- L'enlever
- Deplacer les ressouces de mes cantines ici (alors pas de personnalisation mais les ressources sont là)

![Screenshot 2023-10-12 at 12-31-47 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/28a3e58c-009f-4ecf-a17a-000ac10687cc)

**Comment by alemangui** [comment]
Pour la v1 je l’enlèverais car on n'a pas de ressources personalisées
