### ISSUE TITLE
Aggregation valeurs achats pour TD détaillées

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#3124]
# Contexte
Les télédéclarations détaillées ont plus de colonnes que les télédéclarations simples.
Voici par exemple les valeurs d'achats pour le bio en fonction de types de télédéclaration : 

* TD Simple : `teledeclaration.value_bio_ht`
* TD Détaillée : `teledeclaration.value_meat_bio_ht`, `teledeclaration.value_fish_bio_ht`....

Les TD détaillées ont également la colonne `teledeclaration.value_bio_ht`, mais celle-ci n'est pas remplie automatiquement

# Problème
Dans la plupart des analyses et traitements, nous utilions la valeur globale `teledeclaration.value_bio_ht`. Celle-ci n'étant pas rempli en base de donnée, il faut systématiquement effectuer un traitement d'aggrégation.

# Solution
Aggréger automatiquement les valeurs des TD détaillées afin d'avoir au moins autant de données que les TD simples.
Cette aggrégation peut se faire soit : 
* Au moment de la création des diagnostics
* Via une tâche asynchrone

**Comment by hfroot** [comment]
On n'a pas mis ces valeurs dans la TD pour indiquer que les données dans la TD c'est que les données rentrées par l'utilisateur (et non pas des données aggrégées ajoutées par notre code).
Est-ce que c'est possible de faire l'aggregation côté analyse de données ? @qloridant

**Comment by qloridant** [comment]
Oui pas de soucis pour faire cela.

**Comment by qloridant** [comment]
Remplacé par qqchose de plus local : #3144
