### ISSUE TITLE
P1 - Ajouter la fonctionnalité "plusieurs gestionnaires sur une même cantine"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#325]

**Comment by hfroot** [comment]
Questions a voir dans la planif : 

- pour le premier instant, ça ira si tous les gestionnaires ont le même permissions ? Par exemple, elles/ils sont tous capable de publier, modifier, créer des cantines et diagnostics, et ajouter encore plus de gestionnaires ?
- est-ce qu'on peut penser de l’enlèvement des gestionnaires plus tard ?

Parcours : 

Je suis une gestionnaire d'une cantine -> je veux ajouter un autre gestionnaire pour une cantine, alors je cherche (par nom, par email?)
-> le compte pour le gestionnaire existe déjà, il est ajouté et maintenant peut gérer la cantine. Il reçois un email ?
-> le compte n'existe pas encore
-----> on crée un compte, envoi un email au nouveau gestionnaire pour confirmer l'adresse email et ajouter des autres infos (nom etc) ?
