### ISSUE TITLE
P10 - refonte de la page /nos-cantines avec ajout des camemberts, 1 encart par année, texte libre

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#326]
https://www.figma.com/file/Wy0JohuTd3zP9fTGERs5qq/Egalim-nouveauparcours?node-id=12%3A123

**Comment by alemangui** [comment]
Possibilité de division en stories indépendantes :
- Ajout des filtres par région, département, type de gestion, secteur et nombre de repas par an (filtres coté API backend)
- Recherche par nom d'établissement
- Ajout des champs texte libre dans la DB et dans le formulaire pour les diagnostics
- Refonte du camemberts vers les graphes en colonnes pour les approvisionnements (possibilité de diviser les éléments dénotant une progression à une story séparée si besoin)
- Refonte cartes nos-cantines  
- Ajout des badges
- v1 : Refonte de la page individuel d'une cantine publiée en utilisant les infos déjà là (séparation du téléversement des images pour une autre story)

Discussions
- Association vers des articles de blog : toujours nécessaire malgré les champs libres ? Si c'est le cas, quel type de relation (1:n, n:n, etc) ?
- Information indisponible pour certains widgets dans le figma (nombre de repas végé par semaine 1-5, détail de types de produits, etc). À traiter au cas par cas.
- Boutons "partager" et "télécharger les données", à voir les formats et moyens de partage
