### ISSUE TITLE
P9 - publication : ajout d'un sas de publication, je clique sur publier, l'autodiag passe chez ns pour modération

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#327]

**Comment by hfroot** [comment]
@alemangui Proposition :

Supprimer/rénommer `published` -> `publication_requested`

**Comment by hfroot** [comment]
@alemangui Proposition :

Couper cet issue en deux : le broullion et le ajout du contact

Supprimer/rénommer published -> publication_requested
`CanteenEditor/index.vue` :
- ajouter un troisième option pour la section `Publication` dans le formulaire "Un membre de notre équipe va valider votre demande de publication bientôt. Quand vos données sont publiées, nous vous envoyerons un email. Vous pouvez toujours modifier vos données."

`api/views.py, UpdateUserCanteenView` :
- envoyer un email à nous quand `publication_requested` change d'être `True` `Demande de publication : <canteen name>` avec un lien vers `/admin/data/canteen/<id>`
- n'envoyer pas pour l'instant un email si `publication_requested` change d'être `False`

Après un demand, à la main :
- qqn peut vérifier les données et cocher `Données publiques` quand iel veut.

`admin/canteen.py`
- implementer `save_model` pour envoyer un email aux `canteen.managers` quand la cantine est publié.

**Comment by hfroot** [comment]
@JenniferStephan j'ai créé https://github.com/betagouv/ma-cantine/issues/359 parce que les deux fonctionnalités sont assez differents - j'espère que ça va
