### ISSUE TITLE
[P1] ETQ acheteur.se autogérée de cantine scolaire, je veux comprendre les enjeux de la loi afin d'être sensibilisé aux actions que l'on me demande

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#33]
https://github.com/betagouv/ma-cantine/issues/32

**Comment by alemangui** [comment]
@JenniferStephan est-ce que c'est encore d'actualité ? (le issue lié est déjà fermé)

**Comment by alemangui** [comment]
La carte dans le jardin a déjà été archivée et l'issue lié est fini, je ferme donc cet issue. N'hésitez pas à le rouvrir si besoin.
