### ISSUE TITLE
Pour une CC, forcer la sélection d'une option de TD avant de commencer le tunnel

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3305]
**Problème rencontré :** 
Une cuisine centrale peut faire la TD sans sélectionner d'option de TD de ses CS. 
OR l'objectif est de leur permettre de faire cela. 

**Solution à mettre en place**
- Obligé l'utilisateur de sélectionner l'une des 2 options. 

**Comment on fait ?** 
 Si les 2 booléens sont null
 ET que l'utilisateur clique sur le bouton compléter mes données
 ALORS highlight les 2 options en mode erreur avec le message suivant : Vous devez choisir l'une des deux options
 
<img width="1251" alt="image" src="https://github.com/betagouv/ma-cantine/assets/145361544/8fb90d89-3ac7-416b-b8ca-709a7c85d8d2">

**Comment by hfroot** [comment]
Je propose qu'on met la première option par défaut comme c'est fait dans le diag aujourd'hui, pour éviter la frustration d'un message d'erreur. Ça te va ?

**Comment by Tdauvet89** [comment]
Oui très bien, je souhaite qu'on soit iso avec la prod dans un premier temps. Après on fera des améliorations
