### ISSUE TITLE
Post TD, la C.C avec site ne remonte pas dans les cantines publiées

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3306]
https://www.loom.com/share/29c3e79d42d1453799c8d92f98d8cd40?sid=7230d337-b39e-42d0-8ac9-79107dc88ffe

**Solution à mettre en place :** 
Faire remonter la Cuisine dans les cuisines publiées afin de pouvoir voir sa vitrine

**Comment by hfroot** [comment]
Comme discuté dans mattermost, je propose qu'on ajoute le widget "Ma vitrine en ligne" pour les CC avec site et ajouter la fonctionnalité d'auto-publication avec la TD dans lot 2.

**Comment by hfroot** [comment]
Pour ne pas oublier le travail pour lot 2 : #3327
