### ISSUE TITLE
[Wording] Changer le wording de la création de cpt sur le SIRET

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3307]
Bienvenue ! Renseignez les champs ci-dessous pour créer un compte gestionnaire de cantine. Munissez-vous de votre numéro SIRET pour la prochaine étape : la création de votre ou vos cantines.

**changer par**

Renseignez les champs ci-dessous pour créer un compte gestionnaire de cantine. Munissez-vous du numéro SIRET de votre ou de vos établissement(s) de restauration pour la prochaine étape : la création de votre ou de vos cantine(s).

**Comment by hfroot** [comment]
@Tdauvet89 le double `:` est fait exprès ? Je suis pas familier avec ça

**Comment by Tdauvet89** [comment]
@hfroot Non pas du tout, c'est une coquille de ma part 😅
