### ISSUE TITLE
[WORDING] Textes cartes ma progression pour lot 1

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3313]
Problème : 
Le wording du widget plastique est un copié collé du widget convive. 

Changer par : 
Et si vous disiez au revoir aux ustensiles à usage unique ?

![image](https://github.com/betagouv/ma-cantine/assets/145361544/1530684c-0f0c-4cd5-848a-825a0366f19c)

**Comment by hfroot** [comment]
Ah, c'est un très bon point - on n'a pas remplacé les textes qui sont relié au niveau, qu'on va construire en lot 2. Est-ce que tu pourrais proposer le texte à utiliser pour chaque mesure jusqu'au lot 2 ?

**Comment by Tdauvet89** [comment]
@hfroot @arthurkleindesign voici ma proposition pour les wordings du lot 1. 
Ensuite en lot2 on fera des wordings personnalisés

`**LOT 1 : Wording non personnalisés**`
- **Qualité des produits** :   Renseignez la valeur (en HT) de vos achats alimentaires total et au moins un autre champ par label de produit pour voir la synthèse de vos données. 

- **Lutte contre le gaspillage alimentaire et dons alimentaires** : Votre établissement est soumis à l’obligation de mettre en place des démarches de lutte contre le gaspillage alimentaire. Veuillez déclarer vos actions entreprises.

- **Diversification des sources de protéines et menus végétariens** : Votre établissement est soumis à un certain nombre d’obligations végétarienne. Veuillez déclarer vos actions entreprises.

- **Interdiction du plastique** : Votre établissement est soumis à un certain nombre d’obligations pour réduire l'utilisation du plastique. Veuillez déclarer vos actions entreprises.

- **Information des usagers et convives** : Votre établissement doit informer ses convives sur la qualité alimentaire (au sens EGAlim) et nutritionnelle des repas servis. Veuillez déclarer vos actions entreprises.

**Comment by hfroot** [comment]
Je réfléchis comment on pourrait ajouter de la valeur avec ces textes, même si on va les changer bientôt. Tu penses quoi d'offrir des petit rappels des mesures ? J'utilise les titres courts en bas, qui s'affichent sur les cartes :

    Qualité des produits : cibler des repas de 50 % de qualité et durables, dont 20 % bio, pour un offre plus saine et écolo.

NB : les pourcentages sont personnalisés selon la localisation de la cantine.

    Lutte contre le gaspillage : faire un analyse, utiliser une solution de réservation de repas, et donner les restes aux associations.

    Diversification des menus : proposer un menu végétarien et concevoir un plan pluriannuel pour compléter un offre durable.

    Interdiction du plastique : supprimer toutes les matières en plastique dans votre cuisine et cantine pour protéger notre environnement.

    Information des convives : tous les ans, informer les convives de la qualité alimentaire et nutritionnelle des repas.

Dites-moi qu'est-ce que vous en pensez :)
    
Réflexion annexe : Ça serait cool de mettre plus en avant les raisons devant les mesures. Perso je sais que je suis plus partante pour suivre une obligation si je comprends pourquoi j'ai besoin de le suivre. Vous partagez mon sentiment ?

![Screenshot 2023-12-15 at 16-13-22 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/f76425a9-abef-4ab1-9d20-6861391d25fa)

**Comment by arthurkleindesign** [comment]
Trop bonne idée les phrases je trouve. Je propose quelques modifs 

> Qualité des produits : composer des repas avec au moins 50% de produits de qualité et durables, dont 20% de bio, pour proposer un alimentation plus saine et écologique à vos convives.
> 
> Lutte contre le gaspillage : analyser votre situation, mettre en place des solutions comme la réservation de repas, et valoriser les restes par des dons aux associations.
> 
> Diversification des menus : proposer des choix végétariens dans les menus et construire un plan pluriannuel en faveur d'une offre plus durable.
> 
> Interdiction du plastique : limiter les matières plastiques dans votre cuisine et dans votre cantine pour réduire vos déchets et protéger l'environnement.
> 
> Information des convives : tous les ans, informer les convives et leurs proches de la qualité alimentaire et nutritionnelle des repas servis dans votre établissement.
