### ISSUE TITLE
[Wording] Sur le bandeau Votre bilan a bien été télédéclaré, sortir la seconde partie du titre

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3314]
Problème. 
Dans le titre on dit que le bilan n'est plus modifiable alors qu'il est possible de le modifier jusqua la date de fin de TD. 

Solution à mettre en place : 
Sortir "et ne peut plus être modifié"
![image](https://github.com/betagouv/ma-cantine/assets/145361544/9fe262f9-a0f9-4156-bd21-1acffd7b80f4)

**Comment by hfroot** [comment]
C'est clarifié dans la deuxième ligne "... vous pouvez annuler votre télé... et modifier vos données jusqu'au 31 mars 2024"
Quand il y a une TD active, on n'a pas accès au tunnel pour modifier les données.
Est-ce que tu veux qu'on supprime cette partie de la phrase quand même ?

**Comment by Tdauvet89** [comment]
Oui je veux bien qu'on supprime cette partie @hfroot
