### ISSUE TITLE
[P2] En tant qu'acheteur autogérée de cantine, je veux comprendre les mesures de la loi, afin de les respecter et de planifier mes appro/achats en fonction

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#34]
https://github.com/betagouv/ma-cantine/issues/32

**Comment by alemangui** [comment]
@JenniferStephan vu que l'issue en commentaire a été fermé, est-ce que celui-ci est encore d’actualité ?

**Comment by alemangui** [comment]
Vu que la carte sur le projet est archivée et que l'issue lié est fini, je vais fermer cet issue. N'hésitez pas à le rouvrir si besoin.
