### ISSUE TITLE
MAJ logo en tête

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3407]

**Comment by hfroot** [comment]
@arthurkleindesign on donne les gestionnaires le possibilité d'intégerer un widget sur leur site de leur cantine publié. Tu pourrais trouvé le lien sur la vitrine d'une cantine que tu gères
![Screenshot 2024-01-09 at 16-21-34 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/6bae3d79-6a52-4bc5-ad38-3c42991272aa)

Je tente une MAJ du logo dans le widget aussi, je propose :

![Screenshot 2024-01-09 at 16-18-50 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/27a1967e-7dd1-4daa-b919-1b56da6467c6)

T'as des retours ?

**Comment by arthurkleindesign** [comment]
ça me semble bien ! Je dirais qu'il faut espacer un peu la marianne et le logo, et grossir le logo de manière à ce que les extrémités verticales du plateau bleu soient alignées avec les bords haut et bas de la Marianne (désolé si c'est pas clair, dis-moi)

**Comment by hfroot** [comment]
![Screenshot 2024-01-09 at 16-40-27 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/b77336ee-e088-45f4-a334-eb9fba51f22b)

@arthurkleindesign

**Comment by arthurkleindesign** [comment]
Nickel merci !! Super cette cantine MDR haha

**Comment by Tdauvet89** [comment]
Ok sur staging, GO pour Prod
