### ISSUE TITLE
Améliorer l'UX de choix de secteur

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3415]
Conception de selecteur de secteurs qui garde l'option de selectionner plusieurs secteurs & decoupe la selection de catégorie et après secteur. Contraints : espace sur l'écran; vuetify; dsfr...

P-e https://v2.vuetifyjs.com/en/components/chips/#in-selects ?

Les tags existe dans le DSFR : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/tag

Pour un autre projet j'ai créé quelque chose qui pourrait marcher pour ce cas : https://aldo-carbone.ademe.fr/

![Screenshot 2024-01-09 at 17-51-43 ALDO](https://github.com/betagouv/ma-cantine/assets/9282816/a9f76dd3-f844-4b96-a5d5-6c033d0e5457)

**Comment by hfroot** [comment]
Vous pensez quoi @arthurkleindesign @alemangui ?

**Comment by Tdauvet89** [comment]
Ok sur staging, GO to prod ✅
