### ISSUE TITLE
coquilles à corriger

### ISSUE THREAD

**Issue by arthurkleindesign** [betagouv/ma-cantine#3430]

**Comment by arthurkleindesign** [comment]
Coquilles identifiées côté Valérie
[Quelques coquilles de texte sur plateforme.docx](https://github.com/betagouv/ma-cantine/files/13905793/Quelques.coquilles.de.texte.sur.plateforme.docx)

**Comment by arthurkleindesign** [comment]
Dans le tunnel : 
typiquement ici : 

mettre "(en € HT)" plutôt que "(en HT)"
"de mes" plutôt que "des mes"
enlever le mot "total" à la fin ou le mettre au début "La valeur totale"

<img width="828" alt="image" src="https://github.com/betagouv/ma-cantine/assets/126891687/c4bc8674-1e8a-4ed4-bd92-0f70f52a26dc">

**Comment by hfroot** [comment]
@arthurkleindesign est-ce que pour "La valeur (en € HT) de mes achats alimentaires total" ça doit être "La valeur (en € HT) de mes achats alimentaires" aussi ?
