### ISSUE TITLE
Import cantines : accepter d'autres encodages

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3431]
https://github.com/chardet/chardet

Je crois que le defaut des logiciels français c'est ASCII, p-e au moins on pourrait soutenir ça ?

https://softwareengineering.stackexchange.com/questions/97247/what-is-the-advantage-of-choosing-ascii-encoding-over-utf-8

**Comment by alemangui** [comment]
Fermé par https://github.com/betagouv/ma-cantine/pull/3620
