### ISSUE TITLE
La validation n'est pas déclenchée après avoir cliqué sur un PurchaseHint

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#3446]
Si on a des données d'achats, et qu'on clique sur le PurchaseHint de la première étape du tunnel, la validation du formulaire n'est pas déclenchée et donc les boutons restent grisés - bloquant l'utilisateur.ice dans cette étape.

Faire un `focus` puis `blur` débloque la situation.

Vu en call avec @Tdauvet89

**Comment by Tdauvet89** [comment]
Top merci Alex
