### ISSUE TITLE
Dans la TD détaillé griser les champs qui sont inutiles

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3478]
https://www.notion.so/Dans-la-TD-d-taill-pour-la-famille-charcuterie-ou-l-gumes-griser-les-champs-qui-sont-inutiles-feb670affacd485e845c1e6c7248fb5f?d=b9ee63a2c1364160bafae117106a2b10

- tunnel
- page ajout achat
- API
- behaviour of purchases filling? By one-click and per-field

**Comment by Tdauvet89** [comment]
OK pour moi sur staging, GO to prod ✅
