### ISSUE TITLE
Ajouter guide de saisie pour le tunnel appro

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3500]
[Antisèche ma cantine - light.pdf](https://github.com/betagouv/ma-cantine/files/14126216/Antiseche.ma.cantine.-.light.pdf)

Merci @arthurkleindesign pour le guide

**Comment by arthurkleindesign** [comment]
You're welcome !

**Comment by Tdauvet89** [comment]
@hfroot est-ce que le télechargement de ce doc sera traçable sur matomo ?

**Comment by hfroot** [comment]
@Tdauvet89 oui, on pourrait suivre les [téléchargements sur matomo](https://stats.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=78&period=day&date=yesterday#?idSite=78&period=day&date=yesterday&category=General_Actions&subcategory=General_Downloads)
