### ISSUE TITLE
Dupliquer un achat déjà existant

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3517]
https://www.notion.so/Feuille-de-route-ma-cantine-281d9e99ef454058b4a8946e8fb7eaaa?p=bfcdaade30374eb5bdc8e4a2a3d80824&pm=s

**Comment by Tdauvet89** [comment]
Trop bien merci Helen. 
J'ai un retour, post duplication est-il possible de pré-remplir la date à la date du jour stp.

**Comment by hfroot** [comment]
Pour documenter la décision : on s'est dit qu'on va laisser le champ date vide, avec la raisonnement que le plupart d'utilisateurs ne remplissent pas leurs achats le date où ils passent le commande. On va voir si on a des retours d'utilisateurs si on veut revoir ça.
