### ISSUE TITLE
je veux pouvoir payer sur l'appli

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#366]

**Comment by alemangui** [comment]
@JenniferStephan pas sur de comprendre cet issue :smile:  Qu'est-ce que l'utilisateur cherche à acheter ? On compte vendre des choses sur le site ?

**Comment by JenniferStephan** [comment]
ahaha non @alemangui je faisais une mini formation "product backlog" c'etait un ex de user story, je close; sorry 😇
non je n'essaye pas de me faire de l'argent sur le dos de notre site aha

**Comment by alemangui** [comment]
Ahaha pas de souci, notre fortune en bitcoins devra attendre :P
