### ISSUE TITLE
Open data pas à jour

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3667]
Open data (registre national des cantines) n'est plus à jour depuis le 17 février

Post mep, vérifier que le filtre EPCI comprends bien les libellés

**Comment by qloridant** [comment]
Done. 
Je crée un [ticket lié](https://github.com/betagouv/ma-cantine/issues/3669) qui permettra de mettre à jour explore.data.gouv automatiquement sans casser les updates.
