### ISSUE TITLE
Impossibilité de TD depuis actions en attente

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#3788]
# Contexte
Un utilisateur, gestionnaires de plusieurs centaines de cantines, a importé ses bilans et cantines par fichiers.
Depuis la page `actions-en-attente`, il souhaite valider la TD de ses cantines.

# Problème
Au moment d'appuyer sur le boutons 'Télédéclarer mes XXX cantines`, il ne se passe rien.
Dans la console, pas de log ni pas d'appels réseaux

# Solution
?

**Comment by alemangui** [comment]
Le fix est sur trois PRs : 
- https://github.com/betagouv/ma-cantine/pull/3797
- https://github.com/betagouv/ma-cantine/pull/3796
- https://github.com/betagouv/ma-cantine/pull/3798

Le bug principale était #3797 : on prenait une variable erronée qui nous lançait une erreur frontend.

Par contre, la sensation qu'il ne se passe rien venait d'un problème de perf qui subsiste toujours, mais qui a été un peu adressé avec les PRs #3796 (qui réduit la taille du payload pour la liste d'actions) et #3798 (qui ajoute un spinner pour un call qui ne l'avait pas, donnant l'impression que l'application était bloquée).

**Comment by qloridant** [comment]
Merci @alemangui . Je ferme ce bug
