### ISSUE TITLE
Éviter la publication de certaines cantines

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3815]
Maintenant qu'il y a des cantines déjà publiées p-e il faut mettre en place un bloque sur les endpoints PublishedCanteensView et PublishedCanteenSingleView

Penser à utiliser un variable d'environnement et le reutiliser entre la nouvelle logique et `extract_open_data`

**Comment by hfroot** [comment]
En attente confirmation quels secteurs (open data c'est que 22, je pense il faut 24 aussi).

**Comment by qloridant** [comment]
Le filtre a utiliser n'est pas sur le secteur mais sur le Ministère de rattachement (`line_ministry`)

**Comment by hfroot** [comment]
Ça sera reparé par la nouvelle fonctionnalité de publication par defaut.
