### ISSUE TITLE
TD : ajouter un champ libre commentaires "raison de annulation"

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3843]
Ouvert que à notre équipe dans le backoffice. L'idée c'est que si un utilisateur a fait une erreur avec sa télédéclaration et si la campagne est finit, il peut nous contacter pour annuler la TD. Si notre équipe décide que la TD doit bien être annulée, on pourrait la retrouver dans le backoffice, l'annuler et ajouter une raison pour l'annulation pour qu'on puisse avoir une historique.

Discuté pendant la seminaire 24 avril.

**Comment by hfroot** [comment]
@Tdauvet89 c'est visible sur la page "historique" https://ma-cantine-staging.cleverapps.io/admin/data/teledeclaration/113/history/

**Comment by Tdauvet89** [comment]
Ah ok parfait alors.
