### ISSUE TITLE
Formulaire contact améliorations

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#385]
- [x] Suivre l'envoie de message sur Matomo
- [x] CC : contact@egalim
- [x] From : email dans formulaire
- [x] Ajouter du texte sur le formulaire genre "Ne partage pas des données personnels"
- [x] Ameliorer le style des emails
- [x] Vérifier les bases des URLs dans les emails (j'ai vu clevercloud quelque part)

**Comment by alemangui** [comment]
> Vérifier les bases des URLs dans les emails (j'ai vu clevercloud quelque part)

Erreur de variable d'environnement. Fixé en clevercloud.

**Comment by alemangui** [comment]
> From : email dans formulaire

Not great bc it will look like phishing. I would rather add a reply-to.

**Comment by alemangui** [comment]
>  Ameliorer le style des emails

La souci venait du fait qu'on envoie le message HTML avec un type text et viceversa.
