### ISSUE TITLE
 Affiche, appro : ajouter les objectifs % par produit de famille pour l'année 2024 et +

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3889]

**Comment by hfroot** [comment]
@Tdauvet89 est-ce que les objectifs pour les viandes et poissons EGAlim et France sont differents pour les régions outre-mer ?

**Comment by Tdauvet89** [comment]
Après confirmation avec Val, il n'y a pas de différence de % pour la France et les Outres mers pour les viandes et poissons EGAlim
