### ISSUE TITLE
Publier les cantines

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#3932]
Plusieurs méthodes possibles :

* Bypass le publication_status
* Enlever le publication_status
* Modifier le publication_status

Proposition : Dans un premier temps, on by pass le publication_status puis on le supprimera. 

A faire : 
* Créer variable environnement PUBLISHED_BY_DEFAULT (pour mise en prod plus simple)
* Enlever le filtre du queryset 'publication_status' dans la view (et serializer ?)

**Comment by hfroot** [comment]
En deuxième temps : https://github.com/betagouv/ma-cantine/issues/3883

**Comment by Tdauvet89** [comment]
A priori c'est good, il y a 391 cantines visibles sur la page nos cantines publiées. 
Sur django, il y a 392 cantines dans la table
1 cantine non publiée, qui est rattachée au ministère des armées
