### ISSUE TITLE
Tableau de bord : lien pour permettre les CC de modifier leur affiche en ligne

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3940]

**Comment by Tdauvet89** [comment]
@hfroot quel est la différence avec le bouton éditer mon affiche ? 
<img width="1440" alt="image" src="https://github.com/betagouv/ma-cantine/assets/145361544/23e128eb-a54d-4159-980c-e3f8db32ece8">

**Comment by hfroot** [comment]
@Tdauvet89 le difference c'est pour les CC sans site. Avant, elles pourraient pas publier leur établissement, alors il y avait pas le widget "Mon affiche" pour eux. Maintenant, c'est possible alors ça devrait être visible.

![Screenshot 2024-06-13 at 11-09-51 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/851889b1-c225-4ca1-b7ac-3b89a7022551)

**Comment by Tdauvet89** [comment]
nickel, go pour prod alors
