### ISSUE TITLE
Bug : afficher le notice CC pour les satellites

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3948]
Composant : CentralKitchenInfo

On n'a plus `centralKitchenDiagnostics`. Faut utiliser si l'ID de la cantine sur l'objet du diagnostic en question est la même que la cantine

**Comment by hfroot** [comment]
@Tdauvet89 plus d'info

Cette PR répare un bug qui a été remonté par Val via mattermost. Ça revient au comportement original pour montrer le message avec les infos CC en PJ quand une CC a déclaré les données appro pour au moins une année. 

![Screenshot 2024-06-13 at 11-14-34 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/43fb44c2-17a4-43ac-ab8f-6b280d62a215)

**Comment by Tdauvet89** [comment]
Ok merci pour ces précisions. All good, go pour prod alors
