### ISSUE TITLE
(design dsfr) Sur le composant qui permet d'afficher les années les unes à la suite des autres, le hover n'est pas bleu.

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#3975]
Vu sur l'affiche en ligne , le hover est gris au lieu d'être bleu 
<img width="396" alt="image" src="https://github.com/betagouv/ma-cantine/assets/145361544/5d9819e4-2d67-4a00-a62c-4b89a198d0aa">

**Comment by hfroot** [comment]
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/controle-segmente
L'hover est gris dans le DSFR pour ce composant

**Comment by Tdauvet89** [comment]
Ah ok, je kill le ticket dans ce cas
