### ISSUE TITLE
MAJ design cartes

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3995]
https://www.figma.com/design/t4kFF08mjjXprQNF134ssu/ma-cantine?node-id=3712-173561&t=KtG3jIXfAUX8kgXC-0

image
badges plus larges
chip CC/satellite
titre en bleu
icons indicateurs
enlever les `/` entre indicateurs : faire justify space between
mettre année et %s sur la même ligne

**Comment by Tdauvet89** [comment]
hello @hfroot il y un bug sur l'affichage des logos dans la page cantines publiées. 
Egalement pouvons-nous en profiter pour mettre un image par défaut quand la cantine n'a pas de logo ? 

Vidéo explicative du problème https://www.loom.com/share/189844e90a2d4691bc8f77f529c5c0dc?sid=e804c3a9-12f8-4be9-a663-8171d231c63b

**Comment by hfroot** [comment]
@Tdauvet89 c'est reparé, merci ! Comme pour le widget sur la page tableau de bord établissement, on n'utilise pas le logo mais plutôt la première image téléchargée. On a un image par défaut pour ça depuis un moment.

On n'a pas déjà prévu une image quand il y a pas de logo. Tu proposes quoi ? Peut-être en tout cas on pourrait traiter ça comme une amélioration et créer une suggestion picardie ou nouveau issu github, plutôt de le traiter maintenant avec ce release.

**Comment by Tdauvet89** [comment]
Je suis d'accord avec toi sur le fait que ce n'est pas bloquant pour la
mise en ligne à partir du moment où le bug est réparé.
Je regarde ce que je trouve comme solution et je reviens vers toi.

Du coup, go pour release et amélioration pour une image par défaut
