### ISSUE TITLE
Ajouter un ministère

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4014]
Dans la liste des ministères de tutelle, nous avons besoin de rajouter l'item suivant : 

Préfecture - Administration Territoriale de l'État (ATE)

Rattacher cet item dans la catégorie Autre 
![image](https://github.com/betagouv/ma-cantine/assets/145361544/f4057409-0ce0-4990-8132-0dcd96777235)

**Comment by Tdauvet89** [comment]
hello la team dev @alemangui @hfroot @qloridant , pour info nous avons besoin de cet item. 
Est-ce que quelqu'un peut l'ajouter dans le code svp 🙏

**Comment by hfroot** [comment]
Salut @Tdauvet89 - les ministères ne sont pas rattachés aux catégories. C'est le secteur qui décide si on a besoin de demander un ministère du tutelle, c'est gérable depuis l'admin. Pour vérifier alors, est-ce que "Préfecture - Administration Territoriale de l'État (ATE)" est un ministère du tutelle, ou un secteur dans la catégorie "Autre" ?
![Screenshot 2024-06-06 at 13-02-47 Modification de secteur d'activité Ma Cantine EGALIM - None](https://github.com/betagouv/ma-cantine/assets/9282816/13235f18-e8ce-4669-bf3f-aac3e1caf354)

**Comment by Tdauvet89** [comment]
Merci pour ces précisions, comme je voyais les catégories devant les
ministères j'ai cru que c'était organiser comme ça.

Alors c'est juste un ministère de plus
