### ISSUE TITLE
Bug sur le tableau de board, le switch d'année ne marche pas

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4066]
Vidéo du bug https://www.loom.com/share/34f1fb472bfe4351b21c6708a43f5aef?sid=11ccec7f-4736-4931-9c9b-1ab9f22cb7cf

**Comment by Tdauvet89** [comment]
hello @hfroot j'ai trouvé ce bug sur staging en testant les autres tickets

**Comment by hfroot** [comment]
@Tdauvet89 
merci ! je le mets comme à faire, mais pas bloquant pour ce release

**Comment by Tdauvet89** [comment]
Ok ça marche

**Comment by Tdauvet89** [comment]
Good sur staging, go pour prod
