### ISSUE TITLE
Clarifier la suppresion des cantines depuis admin->user

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4084]
### Ton prénom

Pauline

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/admin/data/user/19716

### Quel type d'utilisateur est concerné ?

- [ ] Gestionnaire
- [X] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Je veux supprimer les cantines associées à un user

### Qu'est-ce que t'as bloqué ?

Je pensais pouvoir le faire depuis la page user, en sélectionnant les cantines et en cliquant sur "supprimer". 
Cela a supprimé l'user et non pas les cantines.

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by qloridant** [comment]
![Screenshot from 2024-06-25 12-02-26](https://github.com/betagouv/ma-cantine/assets/14170613/152ea241-5beb-4409-9e55-dba43bb1f8d9)

**Comment by Tdauvet89** [comment]
Nouveau wording : Retirer ce user

**Comment by hfroot** [comment]
Il me paraît que ce texte n'est pas facilement modifiable
[Docs TabularInline](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#inlinemodeladmin-options)
Je vois dans le code du django (venv/lib/python3.10/site-packages/django/contrib/admin/templates/admin/edit_inline/tabular.html)
`     {% if inline_admin_formset.formset.can_delete and inline_admin_formset.has_delete_permission %}<th>{% translate "Delete?" %}</th>{% endif %}`
Alors c'est pas modifiable par vue.

Je propose une autre solution : on enlève l'option d'enlever l'utilisateur des gestionnaires de la cantine depuis cette vue. Je vais demander aux bizdevs si elles utilisent cette fonctionnalité

**Comment by hfroot** [comment]
https://mattermost.incubateur.net/betagouv/pl/631ueyczkifdfcsf5ksu7ci54w

**Comment by hfroot** [comment]
Après avoir confirmé avec @paulineeyherabide on va pas faire un changement pour le moment
