### ISSUE TITLE
[Bug]: Recherche de cantines par commune

### ISSUE THREAD

**Issue by paulineeyherabide** [betagouv/ma-cantine#4085]
### Ton prénom

Pauline

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/nos-cantines/?page=2&commune=49063&trier=creationCro / https://ma-cantine.agriculture.gouv.fr/nos-cantines/?page=1&commune=49063&trier=creationCro&recherche=Chalonnes%20sur%20Loire

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [X] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Retrouver des cantines sur la même commune

### Qu'est-ce que t'as bloqué ?

J'ai des résultats différents quand je cherche des cantines pour une commune spécifique.
Dans le 1er cas, j'en ai 10, dans l'autre, j'en ai 3.

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
@paulineeyherabide dans le deuxième cas il y a du texte dans la barre de recherche, et dans le premier il n'y en a pas. C'est pour ça que le nombre de résultats est different
