### ISSUE TITLE
[Bug]: il existe des bilans de CCs qui n'ont pas une réponse pour "Pour mes cantines satellites, je saisis :"

### ISSUE THREAD

**Issue by paulineeyherabide** [betagouv/ma-cantine#4095]
### Ton prénom

Pauline

### C'est de quel prio ?

{"label"=>"Bloquant, pas urgent (sprint prochain idéalement)"}

### Le(s) url(s) où tu vois le bug

Données privées

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [X] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Que les données de sa CC soient réimpactés sur sa CS et que les données apparaissent sur la vitrine en ligne

### Qu'est-ce que t'as bloqué ?

Je ne peux pas modifier le lien entre CC et CS pour que les chiffres apparaissent

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
> Quand un gestionnaire entre dans le tunnel et qu'il ne choisit pas "Quelles données sont télédéclarées par la centrale" (juste les appros ou toutes les données), alors les données ne se répercutent pas sur les CS.
Aujourd'hui, cocher la case n'est pas une obligation et les gestionnaires la zappent, ce qui peut les impacter pour la suite.

> Par ex : une gestionnaire de CC n'a pas coché la case et les données n'ont pas été réimpactées sur ses CS.

**Comment by hfroot** [comment]
Normalement depuis [decembre 2023](https://github.com/betagouv/ma-cantine/pull/3321) c'est pas possible de ne pas avoir une réponse pour ça. Je regarde plus en detail pourquoi c'est arrivé

**Comment by hfroot** [comment]
https://ma-cantine-metabase.cleverapps.io/question/1990-nombre-de-diagnostics-pour-2023-crees-par-des-cuisines-centrales-qui-nont-pas-declare-le-facon-de-declaration-pour-leurs-satellites

**Comment by hfroot** [comment]
Depuis juin 2023 on tracke les changements de cantines.
[Liste de cantines qui ont changé leur type de production](https://ma-cantine-metabase.cleverapps.io/question/1992-cantines-qui-ont-change-type-de-production-depuis-juin-2023) entretemps
Ça fait environ [2100](https://ma-cantine-metabase.cleverapps.io/question/1993-nombre-de-cantines-qui-ont-change-type-de-production) cantines en totale. Ou 5 % des cantines sur la plateforme.

**Comment by hfroot** [comment]
Si on regarde que les cantines qui ont changé a un moment entre central/central_serving et un autre type, on voit [environ 1700](https://ma-cantine-metabase.cleverapps.io/question/1994-cantines-qui-ont-change-entre-central-central-serving-et-un-autre-type-de-production)

**Comment by hfroot** [comment]
https://ma-cantine-metabase.cleverapps.io/question/1996-for-diagnostics-in-2023-made-by-ccs-that-dont-have-a-central-kitchen-diagnostic-mode-when-were-they-last-a-different-production-type

Il y a plusieurs bugs :

- bilans créés par import : https://ma-cantine.agriculture.gouv.fr/admin/data/diagnostic/28007/history/ https://ma-cantine.agriculture.gouv.fr/admin/data/diagnostic/22622/history/
- cantines qui ont changé vers un type central après avoir créé le bilan
- bilans créés avant le fix en prod https://ma-cantine.agriculture.gouv.fr/admin/data/diagnostic/18141/change/
- API ? Pas trouvé un exemple mais je sais pas si on a des validations là

Alors je propose les actions suivantes en ordre de prio:

- Ajouter un bloque au moment de la TD pour que une CC a besoin de spécifier la mode avant TDer
- MAJ l'import, mais comment ? Quelle valeur par défaut ? Ou ajouter une nouvelle colonne ? Mais c'est compliqué
- Investiguer les règles API
