### ISSUE TITLE
Dans le bandeau du tableau de bord, communiquer sur le service recrutement

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4097]
Nous souhaitons tester à moindre coup l'offre de recrutement. 

Pour cela, nous invitions les gestionnaires à nous envoyer leurs offres que l'on relaye sur nos réseaux sociaux. 

Pour augmenter la visibilité de ce service test, je souhaite qu'on utilise le bandeau de communication bleu présent sur le tableau de bord. 
![image](https://github.com/betagouv/ma-cantine/assets/145361544/1e9b5571-1a67-4e1e-b17f-e080b15dde6a)

Egalement, est-il possible de comptabiliser le nombre de clic sur le CTA afin de pouvoir voir faire une analyse mi octobre. 
L'idée est de valider ou pas s'il y a une demande de la part de nos utilisateurs. 

Wording : 
Vous cherchez à recruter au sein de vos équipes ? ma cantine vous propose de diffuser vos offres gratuitement sur nos réseaux sociaux 💌

CTA : 
Je communique mon offre qui ouvre l'action email
email : support-egalim@beta.gouv.fr

**Comment by hfroot** [comment]
J'ai commencé le travail sur ça. Voilà ma proposition UI :

![Screenshot 2024-07-11 at 13-24-35 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/d47209c6-5e85-4a18-bd3b-1b8fcc25b361)

Je n'utilise pas le bandeau surtout parce que les bandeaux comme ça sont conçus d'être visible sur toutes les pages du site, à toutes les utilisatrices.

Niveau action, on peut carrément partir sur un `mailto:` mais je veux remarquer que quand ça ne marche pas c'est difficile pour l'utilisateur de trouver un autre moyen de recuperer l'adresse mail. Autres options :

- mettre un adresse mail visible en texte comme alternatif (ça pourrait diminuer les chiffres trackés)
- envoyer l'utilisateur vers la page contact https://ma-cantine-demo.cleverapps.io/contact/ et ajouter une nouvelle option dans type de demande de "Offre de recrutement" (un équilibre entre temps de dév et être fonctionnel pour tout le monde, le tracking des demandes depuis ce formulaire existe déjà sans du code du plus)
- ouvrir une fenetre modale avec le formulaire de contact sur la même page (un peu plus de dév, mais le plus user-friendly ?)

Tu penses quoi @Tdauvet89  ?

**Comment by Tdauvet89** [comment]
Hello @hfroot 
J'aime bien cette proposition je trouve que l'on remarque bien le bandeau, peut être même plus que l'autre. En responsive, où sera placé le bandeau ? Avant le ou après le titre Bienvenu dans notre espace ... ? 

Je te propose qu'on mette l'adresse email en texte plutot que des boutons ou autre. 
Pourquoi ? 
Déjà c'est moins de dev. Et aussi pour le moment nous n'avons pas reçu bcp d'offres m'algrès la communication de l'équipe bizdev. 
 Ce qui va permettre de dire si c'est un sucess ou un echec, c'est pas telelment le canal de communication, mais le volume d'offre collecté.

**Comment by hfroot** [comment]
Merci pour le retour - alors pas besoin de tracking matomo ?

Le message sera placé après le titre :

![Screenshot 2024-07-12 at 18-00-31 ma cantine](https://github.com/user-attachments/assets/c5280854-29e7-47d8-81b3-a5a501497d88)

**Comment by Tdauvet89** [comment]
Je ne pense pas que ce soit nécessaire.
