### ISSUE TITLE
API : documentation

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4101]

**Comment by qloridant** [comment]
Suite à un point avec Arslane d'api.data.gouv, nous avons deux éléments sur lesquels pour finaliser la publication de notre api sur le site : 
* Hébergement de la doc : 
  * sur notre site et on met un lien sur api.gouv.fr 
  * **ou** sur la page api ma-cantine d'api.gouv.fr
* Définition de l'ouverture de l'API : 
  * ouvert : non
  * restreint : oui -> nécessite la rédaction d'une fiche d'habillitation (voir exemple [Impots](https://api.gouv.fr/les-api/impot-particulier))
  * avec création de compte (comme l'[API Sirene](https://api.gouv.fr/les-api/sirene_v3)) : non

**Comment by qloridant** [comment]
J'ai réflechi à mettre cette doc sur la page API, mais elle nécessite un compte pour y accéder

**Comment by Tdauvet89** [comment]
Hello, merci Quentin pour les infos.
je propose qu'on hébérge sur notre site, en bas de page dans le footer un
lien vers api.gouv.fr (directement sur notre page afin que les éditeurs
n'aient pas à chercher sur le site api.gouv)
[image: image.png]

Je n'ai pas compris la définition de l'ouverture de l'API.
Est-ce que ouverture = d'autres dev externe à Ma-cantine peuvent travailler
dessus ?

Le jeu. 18 juil. 2024 à 15:33, qloridant ***@***.***> a
écrit :

**Comment by hfroot** [comment]
ok pour les docs sur notre site (surtout si les docs du site api ne sont pas vraiment ouvert ?).

On aurait quelles infos dedans (grosso-modo) ?

**Comment by qloridant** [comment]
Pardon j'ai pas été très clair (mais je crois que ça ne change pas forcément la réponse), c'est **notre** page API qui n'est pas accessible sans compte.

j'imagine à minima :
* protocole d'autorisation
* messages d'erreur ?
* lien vers la doc métier (c'est quoi une TD ?....)

**Comment by hfroot** [comment]
Ah @qloridant notre page est accessible, on n'a pas mis le lien nulle part par contre pour les personnes pas authentifiées : https://ma-cantine.agriculture.gouv.fr/swagger-ui/

**Comment by qloridant** [comment]
Je propose donc de compléter cette page : https://ma-cantine.agriculture.gouv.fr/swagger-ui/
Avec les infos :
* protocole d'autorisation
* messages d'erreur ?
* lien vers la doc métier (c'est quoi une TD ?....)

Cette page sera référencée depuis api.oguv.fr

**Comment by hfroot** [comment]
Ok - on utilise https://drf-spectacular.readthedocs.io/en/latest/readme.html pour génerer nos docs. 
Quelques liens utils côté swagger :
https://swagger.io/docs/specification/describing-responses/
https://swagger.io/docs/specification/authentication/oauth2/

niveau messages d'erreur, bcp sont générés côté DRF. J'ai trouvé ça comme une liste d'erreurs et leurs traductions : https://github.com/encode/django-rest-framework/blob/master/rest_framework/locale/fr/LC_MESSAGES/django.po

Faut trouver une solution qui est facilement maintenable en même temps. Je suis étonnée qu'on a des pbs avec les messages d'erreur, est-ce que plus de docs est vraiment la solution ? À un moment on aurait besoin de donner du soutien aux dévs qui ont moins d'experience avec les APIs, peu importe les docs qu'on a. 

Bref, AMA si on peu donner quelques docs facilement ça vaut le coup, mais si on a besoin d'ecrire bcp de code qui auront besoin d'être mis à jour quand on développe, j'ai peur que rapidement ça ajoutera un coût qui est pas rentable.
