### ISSUE TITLE
Installation app cms avec wagtail

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4126]
- [x] Package wagtail installé et ajouté dans requirements.txt
- [x] Création d'une nouvelle application django appelée `cms`
- [x] Lien de la nouvelle app `cms` au projet macantine

Critère d'acceptation : 
- [x] Pouvoir ouvrir l'interface Wagtail depuis l'url : `http://127.0.0.1/cms`
- [x] Documentation de l'étape installation et configuration rédigée

**Comment by valleepa** [comment]
Documentation visible [ici](https://www.notion.so/Installation-Wagtail-macantine-2a34e2f03d504d0eb749f7c65958c39c)
