### ISSUE TITLE
Création modèle Fiche Action

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4127]
- [x] Créer un modèle django action_sheet dans l'application CMS
  - [x] Titre
  - [x] Image bandeau
  - [x] Niveau d'effort ETP (@Tdauvet89 : comment décrire cette notation ? Une note sur 3 ?)
  - [x] Prix 
  - [x] Impact
  - [x] Coefficient d'évolution
  - [x] Paragraphe
- [x] Créer un ViewSet Snippet action_sheet pour faire le lien entre Wagtail et le modèle Django

Critères d'acceptation : 
- [x] Écrire une fiche action depuis l'interface Wagtail avec les bon composants et la retrouver dans la base de données 'Fiche Action'

**Comment by Tdauvet89** [comment]
Hello @qloridant @valleepa 
Dans le modèle django action_sheet dans l'application CMS, il faut rajouter un sous titre afin de permettre de faire la distinction entre le titre de la ressource, et les titre de section. 

Pour le niveau d'effort cela correspond à Type d'action = Petits pas, Grand projet
Egalement il faut un second filtre : Origine du gaspillage = Préparation, Non servi, Retour assiette

En front cela se matérialisera comme ça 
![image](https://github.com/user-attachments/assets/cf8dd396-afde-4f3d-b141-20f0ce3276d4)

Et sur la fiche d'une action, ça sera comme ça 
![image](https://github.com/user-attachments/assets/0e5700f7-49cf-4ad6-8334-3ccc6b3b1e09)

**Comment by valleepa** [comment]
En me basant sur le diapo fiche action et la maquette que @Tdauvet89 a envoyé, je propose un modèle dont la description se trouve ci-dessous. 
<p>Création du modèle dans <code>ActionSheet</code></p>

Nom de champ | Nom verbeux | Type Django | Autre
-- | -- | -- | --
title | Titre | TextField |  
subtitle | Sous-titre | TextField |  
action_type | Type d’action | ForeignKey(ActionType) | Il s’agit du niveau d’effort. Référence vers table
waste_origin | Origine du gaspillage | ManyToMany(WasteOrigin) | Contient plusieurs origines
creation_date | Date de création | DateTimeField |  
modification_date | Date de modification | DateTimeField |  
description | Description | RichTextField | Laisser la possibilité d’uploader des fichiers dans le body → plutôt RichTextUploadingField
advice | Conseils pratiques | RichTextField |  
coefficient | Coefficient d’évolution | IntegerField | nombre entier ? positif ? peut-être nul?
image | Image d’illustration | [ImageRenditionField](https://areweheadlessyet.wagtail.org/images) |  




<p>Création du modèle <code>ActionType</code></p>

Nom de champ | Nom verbeux | Type Django
-- | -- | --
name | Nom | TextField
description | Description | TextField



<p>Création du modèle <code>WasteOrigin</code></p>

Nom de champ | Nom verbeux | Type Django
-- | -- | --
name | Nom | TextField





Plusieurs questions me sont venues quant à sa définition : 
- doit on garder les champs *prix* et *impact*, comme proposé dans le diapo fiche action ?
- et quelle forme doit prendre le coefficient d'évolution ?

**Comment by hfroot** [comment]
@valleepa 

- c'est quoi le différence entre `description` et `advice` ?
- tu imagines quelles valeurs dans `WasteOrigin` ?
- `action_type` : pas besoin du mot `action` car on est dans le modèle fiche actions; et je trouve `effort` ou qqch colle plus avec la description du champ.
- ... est-ce que tu as pensé à définir dans le code le niveau d'effort ? (comme `MenuFrequency`) Je me demande les avantages et les inconvénients de laisser les éditeurs de définir les niveaux vs garder la définition dans le code.
- perso j'imagine prix et impact sont importants (après p-e impact est lié au coefficient ?)

Si jamais c'est plus efficace, on pourrait définir un premier définition du modèle et laisser les champs avec des questions pour après (et comme ça on pourrait tester la migration).

**Comment by valleepa** [comment]
@hfroot 
> 
> * c'est quoi le différence entre `description` et `advice` ?
- En me basant sur la capture d'écran de maquette envoyée par @Tdauvet89, j'ai créé un champ `description` qui correspondrait à la partie "Description" de la fiche action et un champ `advice` qui correspondrait à la partie "Conseils pratiques" de la fiche. Peut-être qu'il serait mieux de tout mettre dans un richtext `content` et ainsi laisser plus de liberté dans la structure de la fiche action ?
> * tu imagines quelles valeurs dans `WasteOrigin` ?
- Dans `Waste Origin` j'imagine avoir par exemple ["Préparation", "Non servi", "Retour assiette"]
> * `action_type` : pas besoin du mot `action` car on est dans le modèle fiche actions; et je trouve `effort` ou qqch colle plus avec la description du champ.
- Effectivement ce serait plus clair si `ActionType` devenait `Effort`
> * ... est-ce que tu as pensé à définir dans le code le niveau d'effort ? (comme `MenuFrequency`) Je me demande les avantages et les inconvénients de laisser les éditeurs de définir les niveaux vs garder la définition dans le code.
- Je trouve que ce serait une bonne idée d'imiter la manière dont `MenuFrequency` est définie pour définir `Effort` et `WasteOrigin`, et si l'on souhaite que les éditeurs puissent le modifier, on pourra toujours le rendre accessible en tant que snippet sur wagtail
> * perso j'imagine prix et impact sont importants (après p-e impact est lié au coefficient ?)
- @Tdauvet89 doit-on garder un niveau de prix / d'impact dans le modèle fiche action ?
> 
> Si jamais c'est plus efficace, on pourrait définir un premier définition du modèle et laisser les champs avec des questions pour après (et comme ça on pourrait tester la migration).





Oui je définis pour l'instant le modèle avec très peu de champs et les ajoute petit à petit pour tester les migrations.
