### ISSUE TITLE
Récuperer un objet Wagtail depuis l'API

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4128]
- [x] Installation de l'API 
- [x] Créer un API View Set pour faire la liaison
- [x] Surcharger un Serializer ? (p-e utile pour les images si le serializer intégré de Wagtail ne permet pas d'envoyer les images ou l'nevoi des RichText)

Critère d'acceptation :
- [x] Récupérer depuis l'API un objet Action Sheet avec tous les éléments le contenant

**Comment by hfroot** [comment]
@valleepa je crois que les règles du nouveau projet ont fermé l'issu mais je le reouvert et je regarde les règles pour qu'ils soient fermés plutôt quand on le passe en staging
