### ISSUE TITLE
Tunnel anti gaspi : conception API

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4143]
En premier temps : on le fait en privé

En deuxième temps (et deuxième issu) : 
- on coupe le parti du diagnostic gaspi qui est ouvert, et communique
- on ouvre le nouveau API aux editeurs

**Comment by hfroot** [comment]
[ce commentaire est en cours, je vais le modifier directement au fur et a mesure sauf si qqn laisse un commentaire]

Avant, un PATCH etait : `/api/v1/canteens/{canteen_pk}/diagnostics/{id}`

## URL

`/api/v1/canteens/{canteen_pk}/waste-diagnostics/{id}` ?

Est-ce que c'est confusant de separer les endpoints ? Après, je vois pas trop comment faire differemment car les règles de création sont differents

## Données

## Règles

- period_start_date devrait être > period_end_date du dernier diag (POST et PATCH)
- period_end_date devrait être > period_start_date

**Comment by hfroot** [comment]
@qloridant j'ai complété mes idées, je te laisse reagir :)

**Comment by hfroot** [comment]
Faut aussi avoir un suivi de progrès du tunnel comme l'ancien tunnel. P-e un champ `tunnel` (string)

**Comment by qloridant** [comment]
* Est-ce qu'on veut l'appeler **WasteDiagnostic** alors qu'on n'utilise plus de le terme de *diagnostic* d'un point de vue métier ?
* Si je comprend bien, le WasteDiagnostic ne fait pas partie de l'objet existant *Diagnostic* car il peut y en avoir plusieurs au cours d'une  même année ?
* Comment tu imagines la relation entre un **WasteDiagnostic** et un **Diagnostic** ? Ma compréhension de cette proposition c'est qu'il n'y a pas a proprement parlé de lien entre un **WasteDiagnostic** et un **Diagnostic**. 
* Sur la règle `period_start_date > period_end_date` du dernier diag, il ne faut pas oublier que ces champs peuvent être laissés vides.

Pour répondre à tes questions :

* **TD 2025** : à mon avis on peut supprimer, on ne va surement jamais les analyser et ça porurait apporter de la confusion
* ** Sauvegarde des données anti-gaspi dans la TD** : A mon avis il faut le traiter comme les mesures Végé et Plastique. Soit on sort tout ça de la télédéclaration soit on inclus aussi les mesures anti-gaspi
* **Comportement entre cet outil et CC/satelittes** : On peut garder le même comportement que pour un diag classique ?
* **Beta Testeurs** : Je trouve que c'est une très bonne idée. Ca déjà été fait au sein de ma-cantine d'avoir des nouvelles fonctionnalités ouvertes qu'aux beta testeurs ?

*Remarque générale :* Est-ce qu'on est pas en train d'ajouter pas mal de complexités du fait de sortir cette partie anti-gaspi d'un diagnostic classique ?

**Comment by hfroot** [comment]
@qloridant 

Oui, AMA il y a pas un lien entre les diagnostics/bilans et la nouvelle fonctionnalité anti-gaspi. Surtout parce qu'ils sont fait de periodicité differente (1 diag 1 an, plusieurs anti-gaspi par an possible). Je suis d'acc que choisir un autre nom complètement dans le code servira à souligner ce fait.

Proposition : `WasteMeasurement`

> Remarque générale : Est-ce qu'on est pas en train d'ajouter pas mal de complexités du fait de sortir cette partie anti-gaspi d'un diagnostic classique ?

Oui. Je pense que c'est inévitable vu le difference avec la période de mesure. Après, il y a tjs des options créatives qu'on pourrait trouver. Pour simplifier les discussions, je viens de créer des issus par sujet, ils sont listés au-dessus car je les ai lié à cet issu. Je propose qu'on continue là-bas.
