### ISSUE TITLE
Evolutions du catalogue d'indicateurs

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4147]
- [ ] Vérifier différence de valeurs identifiée par Val
- [ ] Vérifier les calculs de Stéphane et Erwan sur les repas végé

**Comment by qloridant** [comment]
[Catalogue d'indicateurs](https://ma-cantine-metabase.cleverapps.io/dashboard/43-catalogue-indicateurs)
- [ ] Investiguer (onglet secteurs): Trou dans la raquette pour le nombre secteurs 
- [ ] Ajouter (onglet Chiffres Appro) :  Taux Egalim/Bio par mode de gestion (Stéphane ?)
- [ ] Ajouter (onglet Chiffres Appro) : Ajouter calcul borne haute du taux Egalim pour mise en place d'une fourchette
- [ ] Investiguer (onglet Chiffres Généraux) : distribution des TD : nombre très important de valeur non renseignée
- [ ] Calculer le nombre de TD crées par API
- [ ] Mettre  à jour le taux de transformation en filtrant sur les value_total_ht puis prévenir Mathilde
- [ ] Ajouter dans la chaîne de traitement un suivi des NSP (je ne sais pas). *optionnel*
- [ ] Ajouter dans la chaîne de traitement le montant des achats totaux avant applicaiton filtre (au moins celui value_bio_vide)
- [ ] Ajouter un  graphique sur la distribution des taux bio/egalim par classe de 10%
- [ ] Investiguer les valeurs d'achats alimentaires SIQO négatives
- [ ] Ajouter le graphe tunnel des filtres
