### ISSUE TITLE
[Bug]: Numéro Siret Invalide

### ISSUE THREAD

**Issue by Greta712** [betagouv/ma-cantine#4157]
### Ton prénom

Great

### C'est de quel prio ?

{"label"=>"Bloquant, pas urgent (sprint prochain idéalement)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/nouvelle-cantine/?etape=siret

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

L'utilisateur veut enregistrer sa cantine avec le numéro Siret (trouvé sur annuaire education) mais celui-ci ne semble pas être valide 

### Qu'est-ce que t'as bloqué ?

J'ai un message d'erreur

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
T'as quel message d'erreur ?
