### ISSUE TITLE
[Bug]: Images ne s'affichent pas dans article de blog

### ISSUE THREAD

**Issue by valleepa** [betagouv/ma-cantine#4160]
### Ton prénom

Paul-Elie

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/blog/4

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [X] Équipe
- [X] Citoyen
- [X] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Je voulais consulter un article du blog

### Qu'est-ce que t'as bloqué ?

Les images ne se sont pas affichées 
![image](https://github.com/user-attachments/assets/ed5e6c49-ca5f-443b-8a12-f0b81270b332)
Avec l'erreur suivante dans la console
`Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' cellar-c2.services.clever-cloud.com voxusagers.numerique.gouv.fr 'unsafe-inline' stats.beta.gouv.fr <URL> data: image.crisp.chat jedonnemonavis.numerique.gouv.fr".`

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
Quand je regarde les logs, je vois que les images sont servis depuis github, alors on les soutien pas ([un autre blog](https://ma-cantine.agriculture.gouv.fr/blog/50) n'a pas le même pb.

J'ai remplacé les images.
