### ISSUE TITLE
MAJ DNS ? Suite au CleverCloud (date limite : 23 aout)

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4161]
![Screenshot 2024-07-17 at 16-08-54 Console - Clever Cloud](https://github.com/user-attachments/assets/1095959e-f71d-4609-af68-cacca8e858a0)

**Comment by hfroot** [comment]
on attende la réponse de la personne qui gère la domaine agriculture.gouv.fr

**Comment by alemangui** [comment]
Côté SI du ministère des records `CNAME` ont été ajoutés, donc normalement on n'aura plus besoin de mettre à jour des records `A` si les adresses IP changent à nouveau :+1:
