### ISSUE TITLE
[Bug]: Cuisine centrale a pu supprimer leur SIRET sans le remplacer

### ISSUE THREAD

**Issue by Greta712** [betagouv/ma-cantine#4164]
### Ton prénom

Great

### C'est de quel prio ?

{"label"=>"Bloquant, pas urgent (sprint prochain idéalement)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/modifier-ma-cantine/58496--LEZTROY%20(Cuisines%20Centrales)/satellites?page=1

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

L'utilisateur m'informe que ces cantines satellites ont tout simplement disparu. En regardant de plus près je constate qu'il n'y a plus de siret dans la page "établissement" de la cuisine centrale ni dans admin. Et pourtant je n'ai pas de message d'erreur sur l'espace de l'utilisateur lui disant qu'il y a une information manquante.

### Qu'est-ce que t'as bloqué ?

Le siret de la centrale a disparu mais impossible de dire comment. 

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
@Greta712 si tu regardes dans l'[historique de la cantine](https://ma-cantine.agriculture.gouv.fr/admin/data/canteen/58496/history/) (fiche admin -> historique) l'utilisateur a supprimé le siret le 18 juillet. Ça devrait pas être possible, alors je laisse le bug ouvert pour investiguer plus comment ça a été fait, mais pour résoudre le pb pour l'utilisateur, faut si rajouter le SIRET dans admin, si demander l'utilisateur de le faire. Si jamais c'est possible de demander l'utilisateur comment il l'a supprimé ça serait utile.
