### ISSUE TITLE
[API] - lorsqu'on éditeur injecte des données dans un bilan, le tableau de bord sur l'année en question ne s'update pas.

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4174]
### Ton prénom

Thomas

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine-demo.cleverapps.io/dashboard/2728--Test%20siret

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [ ] Administration
- [X] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Après avoir réceptionné les données sur ma cantine, je veux voir la synthèse sur mon tableau de bord

### Qu'est-ce que t'as bloqué ?

https://www.loom.com/share/8863bc1776ad4a76bfcd1652298f6327?sid=71449101-3039-4c47-b844-6952d74d04b0

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by Tdauvet89** [comment]
hello @alemangui j'ai vu ce bug lors de l'installation avec Wenzi, il me semblait que tu l'avais corrigé ? C'est sur l'environnement de démo

**Comment by hfroot** [comment]
@Tdauvet89 le bug est réglé :)

**Comment by hfroot** [comment]
lié au #4081 qui a été déployé avec https://github.com/betagouv/ma-cantine/releases/tag/2024-07-23
