### ISSUE TITLE
[Bug]: Une cuisine sateliite s'est crée sans SIRET

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4176]
### Ton prénom

Quentin

### C'est de quel prio ?

{"label"=>"Bloquant, pas urgent (sprint prochain idéalement)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/admin/data/canteen/109862/change/

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [X] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Je veux bloquer la création de cantine sans siret

### Qu'est-ce que t'as bloqué ?

-

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
En lisant l'historique, je vois que le SIRET a été supprimé dans une modification https://ma-cantine.agriculture.gouv.fr/admin/data/canteen/109862/history/
C'est lié alors j'imagine à https://github.com/betagouv/ma-cantine/issues/4164

**Comment by hfroot** [comment]
Je le ferme comme dupliqué après l'investigation
