### ISSUE TITLE
Docs intégration iframe

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4181]
Écrire quelques notes de comment le faire dans un article de blog, qui pourrait être finaliser et diffuser par l'équipe bizdev

**Comment by hfroot** [comment]
En brouillon : https://ma-cantine.agriculture.gouv.fr/admin/data/blogpost/52/change/

**Comment by Tdauvet89** [comment]
J'ai ajusté les photos et fait qq correctifs de coquilles. 
Article maintenant en ligne https://ma-cantine.agriculture.gouv.fr/blog/52
