### ISSUE TITLE
Import : ajouter un lien sur la page création cantine/siret pour l'option import

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4183]
Parcours nouveau utilisateur c'est : creation compte -> page création cantine

Alors pour les utilisateurs qui gère bcp de cantines c'est confusant de tomber sur cette page d'un siret seul quand ils veulent créer plusieurs cantines avec l'import. Cette confusion génère du support.

https://www.notion.so/Import-massif-fd049078a993468e8ea5160e14396cd8?pvs=4#39d97a09b6154069b53a985955c14a69

**Comment by Tdauvet89** [comment]
@hfroot il y a une petite coquille sur le mot préparer. 
Mise à part ça c'est good.


![Image](https://github.com/user-attachments/assets/93e29548-3cd4-44ac-8ab4-ce2f5b3518c3)

**Comment by hfroot** [comment]
Bien vu ! Je [le répare](https://github.com/betagouv/ma-cantine/pull/4290) et je vais faire le release
