### ISSUE TITLE
Import : formulaire pour aider le choix

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4184]
https://www.notion.so/Import-massif-fd049078a993468e8ea5160e14396cd8?pvs=4#c6f01db6836e4f10941e39484cc25aa5

**Comment by Tdauvet89** [comment]
Testé sur Staging, c'est top ! 

Mes retours : 
- Remplacer la page https://ma-cantine-staging.cleverapps.io/importer-diagnostics par le formulaire. 
- Dans le menu aide, ajouter un onglet "Importer un fichier" qui bascule vers /importer-diagnostics

**Comment by hfroot** [comment]
D'acc pour points 1 & 2.

Sur le 3e point je peux supprimer le doublon mais je trouve que l'action d'import ne sera pas utilisé assez par nos utilisateurs pour justifier le mettre en haut à droit. Pour la petite partie de nos utilisateurs qui vont utiliser l'import, ils vont l'utiliser qu'une fois par an. Je pense qu'on va générer plus de support si on mets le lien dans un endroit tellement visible. Je propose qu'on mets le quiz en production et voir en fonction avec l'usage de si on a besoin de le mettre encore plus en avant.

**Comment by Tdauvet89** [comment]
En y repensant, si on a pas ce bouton, ça oblige les utilisateurs qui ont
téléchargé une template a refaire le formulaire pour tomber sur la page qui
permet de faire l'import.

**Comment by hfroot** [comment]
> qui ont crée leur compte, et qui voulaient importer un fichier. Sauf qu'ils ne savent pas où le faire sur la plateforme.

ces retours datent de quand ?

**Comment by Tdauvet89** [comment]
Fin juillet quand j'ai fais le support

**Comment by hfroot** [comment]
ok, attendons voir les impacts des changements qu'on vient de faire avant faire plus ?

**Comment by Tdauvet89** [comment]
Je te propose qu'on en parle demain au seminaire avec la team bizdev, au
final c'est eux qui gèrent le support :)

**Comment by Tdauvet89** [comment]
Ok pour le changement, on reparlera du bouton plus tard avec les bizdev
GO pour prod
