### ISSUE TITLE
Doc API / Création d'un Diagnostic : Préciser que l'année est obligatoire

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4196]
**Problème rencontré**
Les développeurs de Wenzy avaient crée des diagnostic sans injecter l'année et du coup ils ne comprennaient pas pourquoi les diagnostic ne s'affichaient pas sur la plateforme...

**Solutions à mettre en place:** 
1. Préciser que l'année est obligatoire lors de la création
2. Avoir un gestion d'erreur qui dit que ce champ est manquant

**Comment by qloridant** [comment]
Comme l'indique @raphodn , ce ticket fait un doublon avec le ticher #4152 qui a été traité par la [PR](https://github.com/betagouv/ma-cantine/pull/4275)

**Comment by raphodn** [comment]
En effet la correction faite pour #4152 a aussi mis à jour la doc swagger automatiquement :heavy_check_mark:
