### ISSUE TITLE
[Bug]: Certaines cantines ont TD sans SIRET

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4206]
### Ton prénom

Quentin

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine-metabase.cleverapps.io/question/1516-td-filtrees-car-siret-vide

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [X] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Forcer les gestionnaires à renseigner leur SIRET avant une TD

### Qu'est-ce que t'as bloqué ?

La TD n'est pas encore complètement bloqué en cas que SIRET absent 

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
24 de 25 ont été créées par le même utilisateur qui n'a plus un compte (ou n'a plus le même compte) https://ma-cantine-metabase.cleverapps.io/question/1984-td-filtrees-car-siret-vide-avec-adresse-mail

J'ai vérifié quelques unes de ces TDs, et elles ont été fait via API. Alors normalement ce pb est réglé avec #3675. Après, il y a d'autres pbs comme #4152 et en générale il faut vérifier si les règles sont les mêmes entre API et site #3884 

Pour la dernière c'est un peu difficile à confirmer, car la TD a été fait avant qu'on a [ajouté l'historique au modèle](https://github.com/betagouv/ma-cantine/blame/3fe881a89da1212ee2b9ae61148711d30f0680f8/data/models/teledeclaration.py). Mais les changemennts sur le diagnostic ont été fait via le site.

 Je ferme cet issu et je le remplace dans le sprint avec #3884
