### ISSUE TITLE
MAJ règles badge anti-gaspi

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4207]
on fait quoi avec le badge gaspi (affiché sur l'affiche PDF, affiche en ligne, cartes cantines, page stats) ?

Règles d'aujourd'hui :

    faut avoir fait un diag ("J'ai réalisé un diagnostic sur les causes probables de gaspillage alimentaire")
    faut avoir 1+ actions de:
        Pré-inscription des convives obligatoire
        Sensibilisation par affichage ou autre média
        Formation / information du personnel de restauration
        Réorganisation de la distribution des composantes du repas
        Choix des portions (grande faim, petite faim)
        Réutilisation des restes de préparation / surplus
    si > 3000 couverts par jour
        faut proposer des dons ("Je propose une ou des conventions de dons à des associations habilitées d’aide alimentaire")

Si on change les règles, est-ce qu'il faut MAJ les infos de la mesure : https://ma-cantine.agriculture.gouv.fr/mesures-phares/gaspillage-alimentaire ?

Question originellement posée ici : https://github.com/betagouv/ma-cantine/issues/4143

**Comment by hfroot** [comment]
https://mattermost.incubateur.net/betagouv/pl/tuxzoygxkfncdqnxouir4mrgrc

**Comment by Tdauvet89** [comment]
Prise de décision: 
Concernant la règle d’affichage du badge, après échange avec Maiwenn et Erwan, il a été convenu que lon conserve la mm règle (= doit avoir réalisé un diagnostic + une action. Pour les >3000couverts, doit faire du don)

Comme nous n’avions pas prévu ces questions dans le nouveau design du tunnel, nous allons réajuster la page l’onglet “ma progression gaspillage alimentaire de la TDen 2 parties :
1. Un bloc pour les questions sur le diagnostic et les dons
2. Un bloc sur les actions

Historique dans le ticket notion de la feuille de route https://www.notion.so/Feuille-de-route-ma-cantine-281d9e99ef454058b4a8946e8fb7eaaa?p=f46e920a57884e33926129afdc30ede4&pm=s
Notion des regles sur les badges : https://www.notion.so/Regles-des-badges-ce7778f3055d46c0bf5cb7a0c9dcf400

**Comment by Tdauvet89** [comment]
Concernant la règle d’affichage du badge, après échange avec Maiwenn et Erwan, il a été convenu que lon conserve la mm règle (= doit avoir réalisé un diagnostic + une action. Pour les >3000couverts, doit faire du don)

Comme nous n’avions pas prévu ces questions dans le nouveau design du tunnel, nous allons réajuster la page l’onglet “ma progression gaspillage alimentaire de la TDen 2 parties :
1. Un bloc pour les questions sur le diagnostic et les dons
2. Un bloc sur les actions

Historique du ticket Gaspillage alimentaire https://www.notion.so/Feuille-de-route-ma-cantine-281d9e99ef454058b4a8946e8fb7eaaa?p=f46e920a57884e33926129afdc30ede4&pm=s
Notion vers les règles des badges https://www.notion.so/Regles-des-badges-ce7778f3055d46c0bf5cb7a0c9dcf400

**Comment by hfroot** [comment]
vu que cette issu a été plutòt un issu de discussion, je le ferme avec notre décision. Je crée un nouveau issu pour le développement.
