### ISSUE TITLE
Problème d'accessibilité sur les DsfrTags non clickables

### ISSUE THREAD

**Issue by valleepa** [betagouv/ma-cantine#4232]
[voir vidéo](https://www.loom.com/share/f77e185cc622465397b95add80e8acd0?sid=52c4e37c-e0b6-4a3b-9947-75f74491cd08)

**Comment by hfroot** [comment]
T'as tout à fait raison, bien vu. En fait, dans `frontend/src/components/ProductionTypeTag.vue` on a déjà une classe definie et on utilise un element `p` plutôt que le `v-chip` pour ce tag non-cliquable. On pourrait refactoriser notre `DsfrTag` pour utiliser ce code quand un tag n'est pas interactif. Avec la refacto, on pourrait refactoriser ProductionTypeTag pour utiliser le nouveau composant

**Comment by hfroot** [comment]
Peut-être le problème vient du fait qu'on definie tjs une action `@click` sur notre utilisation de `v-chip` dans `DsfrTag`, même si c'est une mêthode vide. Alors j'imagine le navigateur voit qu'il y a une action associée à un element non interactif (un span) et remonte l'erreur. Je crois que c'est pas vraiment un pb en vrai pour l'a11y, vu que une action qui fait rien n'est pas accessible au clavier.

Le truc qui m'ennerve plus c'est qu'on voit un `cursor: pointer` sur les tags même quand il y a pas d'action, qui est confusant niveau UX
