### ISSUE TITLE
[Bug]: Différences de chiffres entre le nbr de cantines

### ISSUE THREAD

**Issue by Greta712** [betagouv/ma-cantine#4233]
### Ton prénom

Greta

### C'est de quel prio ?

{"label"=>"Nice to have"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/statistiques-regionales?year=2023&epcis=200058360

### Quel type d'utilisateur est concerné ?

- [ ] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [X] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

 j'ai un retour au sujet des stats. Il y a une différence entre le total de cantines publiées (22) et la répartition par secteur pour l'EPCI d'entre Beauce et Perche (17). Je ne sais pas si c'est un bug ou bien lié à l'absence des chiffres pour le secteur Armée ?

### Qu'est-ce que t'as bloqué ?

Je n'arrive pas à trouver l'erreur ou ce qui explique cette différence.

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
@Greta712 il y a bien 5 cantines qui n'ont pas de secteur dans cet EPCI. https://ma-cantine-metabase.cleverapps.io/question/1983-debugging-github-issu-4233-les-cantines-sans-secteur-dans-epci-200058360

**Comment by hfroot** [comment]
https://www.notion.so/fabe4c2eba6248129d7780b10c8c0df6?v=37001600875549f9ad381b61a1c16f5c&p=fff4a08edabc8130ab52cc64deddb90b&pm=s
