### ISSUE TITLE
Discussion architecture CMS

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4304]
### API CMS dédiée (actuellement) ou API classique ?

voir #4274 

### Page ou snippet ?

Travail exploratoire commencé dans wagtail-blogpost

Avec snippets c'est très facile d'ajouter nos modèles actuels dans wagtail (exemple avec blogpost)

Avec page la [migration est difficile](https://github.com/wagtail/wagtail/discussions/8340) mais on a des fonctionnalités out-of-the-box, y inclus brouillon, [commentaires](https://guide.wagtail.org/en-latest/how-to-guides/manage-pages/#create-and-edit-comments) (qui n'est [pas dispo pour les snippets](https://stackoverflow.com/a/77714721/3845770))
il y a aussi peut-être quelques complications avec la publication car les pages sont normalement publiées sur un URL géré par wagtail

[Snippets](https://docs.wagtail.org/en/v6.2.1/topics/snippets/index.html)

**Comment by hfroot** [comment]
relié à #4274 car ma branche montre comment c'est possible d'utiliser les modèles et l'api normale

**Comment by raphodn** [comment]
Modèles actuels

|`data/models/BlogPost`|`cms/models/WasteAction`|
|---|---|
|`title`|`title`|
|`tagline`|`subtitle`|
|`body` (RichTextUploadingField)|`description` (RichTextField)|
|`display_date`||
|`published`||
|`author`||
|`tags`||
||`effort`|
||`waste_origins`|
||`lead_image`|
|`creation_date` & `modification_date`|`creation_date` & `modification_date`|

**Comment by raphodn** [comment]
Décisions
- on va basculer le modèle `WasteAction` vers /data
- on va regarder pour la migration
- on va utiliser /v1/api
- on va continuer avec les snippets
