### ISSUE TITLE
Investiguer les valeurs null du champs diagnostic_type dans les TD

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4308]
Voir la distribution des valeurs sur cette [question](https://ma-cantine-metabase.cleverapps.io/question/1997-issue-4308-valeurs-nulles-de-diangotic-type)

Hypothèse : Les TD simplifiées ont la valeur nuill au lieu de 'SIMPLE'

**Comment by hfroot** [comment]
tu pourrais aussi voir les données historique pour vérifier si les changements ont été fait par API ou via le front.
Avec creation_source = TUNNEL et appro_tunnel = complet p-e on pourrait dire que le type est SIMPLE. (Je crois qu'on montre de base les étapes simples si on n'a pas de valeur pour cette question.

**Comment by qloridant** [comment]
Problème identifié pour le front #4342  (90% des valeurs manquantes). Ces valeurs pour le front sont bien des `SIMPLE`

Le problème est donc réglé pour l'analyse. Il reste à corriger le code : 
* front : #4342 
* API : #4344 
* imports : #4343
