### ISSUE TITLE
CMS : sous titre n'est pas obligatoire

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4311]

**Comment by raphodn** [comment]
@hfroot à noter en testant que dans l'onglet "Caractéristiques" les champs `effort` et `waste_origins` sont tous les 2 obligatoires. ok pour l'instant ?

**Comment by raphodn** [comment]
en lien avec mon message au dessus, j'ai ouvert une PR #4371 pour bien s'assurer que ces champs sont remplis (et on pourra à terme les modifier en rajoutant null=True/blank=True si l'on ne souhaite pas qu'ils soient obligatoires)

**Comment by Tdauvet89** [comment]
Ok pour moi, par contre il faudra bien sensibiliser les utilisateurs sur ce champs car si celui-ci est vide car en vue liste cela fait un blanc dans le tableau. 

Ok pour prod

**Comment by hfroot** [comment]
@raphodn oui, les autres champs sont obligatoires (notre utilisatrice a testé le CMS et n'a pas donné de retours)
