### ISSUE TITLE
CMS admin : filtrage et recherche

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4313]
par tag, par titre

Besoin "Prévoir la possibilité de faire des dossiers de fiches actions sur l'espace ma cantine plutôt que d'avoir tout de regroupé;"

Edit : les snippets wagtail ne permettent pas (facilement ?) de faire des dossiers. Donc on va plutot proposer du filtrage & recherche pour l'instant

**Comment by raphodn** [comment]
@hfroot on a déjà une idée du nom des dossiers ? custom ?

ou alors rajouter un champ dans le modèle `WasteAction`, et demander à l'auteur.ice de le mettre dans le bon dossier (un peu comme le champ/tag `effort`)

**Comment by raphodn** [comment]
Suite à nos discussions, j'ai modifié l'issue initiale et rajouté le besoin de filtres/recherche plutôt que dossiers

**Comment by Tdauvet89** [comment]
ça marche super bien, j'en ai profité pour faire une vidéo tuto, que l'on enverra à Maiwenn lorsque ça sera sur Démo

https://www.loom.com/share/01a7c08a36fe42d48d6c72f3f39fcf3a?sid=5d8de4b4-9e7b-4b0e-8ca0-206d80b8795e

Ok pour le passer en prod, bien joué 🥇
