### ISSUE TITLE
Fiches action anti gaspi : option de filtrer par tag

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4316]

**Comment by hfroot** [comment]
dupliqué par #4313

**Comment by hfroot** [comment]
C'est pour le front, pas l'admin

**Comment by Tdauvet89** [comment]
ça marche super bien, j'en ai profité pour fair eune vidéo tuto, que l'on enverra à Maiwenn lorsque ça sera sur Démo
https://www.loom.com/share/01a7c08a36fe42d48d6c72f3f39fcf3a?sid=5d8de4b4-9e7b-4b0e-8ca0-206d80b8795e

Ok pour le passer en prod, bien joué 🥇
