### ISSUE TITLE
Fiches action anti-gaspi : option de rechercher par texte

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4317]

**Comment by raphodn** [comment]
@hfroot recherche par texte = dans le contenu de la fiche ? ou juste dans le titre ?

si juste dans le titre, alors c'est fait dans la PR #4313

**Comment by hfroot** [comment]
je crois qu'on peut commencer par le titre oui

**Comment by hfroot** [comment]
C'etait pour le front, pas l'admin. Je l'ouvre et je le prends pour ce sprint

**Comment by Tdauvet89** [comment]
![Image](https://github.com/user-attachments/assets/5c72c4d3-94a4-4b11-b261-a7be9cd110e9)
ça marche super bien sur staging. 

Testé aujourdhui : 
- Recherche par mot
- Recherche mot plus 1 filtre
- Recherche mot plus 2 filtres
- Recherche filtre + mot non présent dans les actions filtrés = (pas de résultat avec ces)

👉 @hfroot un retour de wording sur le message pas de résultat
Remplacer "trouvé des actions" ->  "trouvé de ressources"
![Image](https://github.com/user-attachments/assets/ea9afd1a-68e8-46e7-bda3-1cef8c795e1b)

**Comment by Tdauvet89** [comment]
Je viens de trouver un petit bug, lorsque je clique sur le bouton Désactiver tous les filtres, il ne marche pas. 
Vidéo explicative du bug  https://www.loom.com/share/ed681f7611c9418595baeaa1a9c14716?sid=5c85a994-e6b0-42ea-be08-1af6c60b5bb6

**Comment by hfroot** [comment]
merci ! je regarde

**Comment by Tdauvet89** [comment]
Cette fois c'est nickel :) 
GO pour prod @hfroot
