### ISSUE TITLE
Actions anti-gaspi : vue liste

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4337]

**Comment by Tdauvet89** [comment]
![Image](https://github.com/user-attachments/assets/167b5ddd-9197-4cc5-bbcb-a2c2413bbbd1)

Faudra bien sensibiliser Maiwenn sur l'importance d'avoir une description courte afin de ne pas ce retrouver dans la configuration du screeshot, cad juste un blanc au niveau de la description courte. 

J'ai regardé ses fiches sur démo, il n'y a pas de pb

OK pour moi alors, merci 👍

**Comment by hfroot** [comment]
@Tdauvet89 AMA un besoin de sensibilisation signale un faiblesse de design. Je vois pas trop le problème avec une cellule vide dans le tableur au-dessus. Par contre, si tu penses qu'il nécessite un changement pour éviter le besoin de sensibilisation je vois des options : 

1. on passe pas #4311 en prod, et on revient vers Maiwenn pour elle dire qu'on va pas effectuer ce changement qu'elle a demandé
2. on enlève la colonne "Description courte" du tableur, et des sous-titres de la vue cartes
