### ISSUE TITLE
Page Ma Collectivité : Supprimer graphique cantines publiées

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4367]
Le champs `publication_status` étant globalement obsolète, ce graphique le devient tout autant.

**Comment by hfroot** [comment]
peut-être aussi supprime les stat depuis le back ? Faut vérifier que c'est pas utilisé autre part

**Comment by raphodn** [comment]
on parle du graphique de gauche (dans l'image ci-dessous) ?

![Image](https://github.com/user-attachments/assets/45243d0c-d61b-4a9d-91a4-b491cfa7e612)

**Comment by raphodn** [comment]
on parle du graphique de gauche (dans l'image ci-dessous) ?

![Image](https://github.com/user-attachments/assets/45243d0c-d61b-4a9d-91a4-b491cfa7e612)

**Comment by Tdauvet89** [comment]
Ok pour moi, GO prod
