### ISSUE TITLE
Les photos uploadées par les users sont KO

### ISSUE THREAD

**Issue by paulineeyherabide** [betagouv/ma-cantine#4377]
Les photos uploadées par les utilisateurs ne sont plus visibles sur "Trouver ma cantine"
![Uploading Screenshot 2024-09-03 15.58.35.png…]()

**Comment by hfroot** [comment]
J'ai testé si c'est la MAJ d'un dépendance mais c'est pas le cas. Je vais suivre le statut Clever Cloud et on espère que ça va résoudre le pb

**Comment by Tdauvet89** [comment]
Même problème sur la brique anti-gaspi (ici démo).
Comme l'a expliqué Helen, ça touche tous les environnements. 



![Image](https://github.com/user-attachments/assets/c7a7ba22-cc2a-48b5-9233-4e2ed2adc04f)

**Comment by hfroot** [comment]
Resolu avec #4393
