### ISSUE TITLE
[Bug]: Message d'erreur des imports 

### ISSUE THREAD

**Issue by paulineeyherabide** [betagouv/ma-cantine#4390]
### Ton prénom

Pauline

### C'est de quel prio ?

{"label"=>"Nice to have"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/importer-diagnostics

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Il veut télécharger un fichier mais ce dernier n'est pas au bon format. L'erreur "Le fichier doit être sauvegardé en Unicode UTF8".

### Qu'est-ce que t'as bloqué ?

L'encodage en UTF8 n'est normalement plus actif, ça peut être confusant de le laisser. De plus, "Unicode" ne parle aux utilisateurs. S'il est possible de parler de "format .csv" ce serait peut-être plus parlant.

![Screenshot 2024-09-05 16 36 26](https://github.com/user-attachments/assets/0623e70d-a4a1-43e1-9914-2c0ee050b0df)

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
Depuis debut septembre on accepte plus d'encodages pour l'import achats alors normalement ce n'est plus un problème, https://github.com/betagouv/ma-cantine/pull/4309
