### ISSUE TITLE
[Bug]: Pb d'affichage des factures (peut-être lié au pb Clevercloud mais je ne sais pas)

### ISSUE THREAD

**Issue by paulineeyherabide** [betagouv/ma-cantine#4392]
### Ton prénom

Pauline

### C'est de quel prio ?

None

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/mes-achats/1131261

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

L'utilisateur veut visualiser sa facture.

### Qu'est-ce que t'as bloqué ?

Une erreur s'affiche "Oups page introuvable" quand l'utilisateur clique sur "Voir le fichier" 

![Screenshot 2024-09-06 10 23 06](https://github.com/user-attachments/assets/4e62aa3a-d358-4e65-aad4-7b1b6189e1e5)

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
dupliqué [#4377](https://github.com/betagouv/ma-cantine/issues/4377)
