### ISSUE TITLE
Monitorer les résultats des tâches

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4405]
# Contexte
Nous avons actuellement une petite dizaine de tâches qui tournent de façon régulière grâce à Celery (ETL Open Data, ETL Analysis, Geo Bot)

# Problème
Nous ne les monitorons pas. Il est difficile de dire si elles s'executent correctement.

# Solution
Utiliser un outil de monitoring comme [Airflow](https://airflow.apache.org/) ou [Prefect](https://www.prefect.io/)

**Comment by raphodn** [comment]
Est-ce qu'un outil plus Django-friendly comme [django-q2](https://github.com/django-q2/django-q2) aurait du sens ? C'est à dire utiliser la DB pour stocker le résultat des tâches.

Ma crainte c'est de complexifier notre archi en rajoutant un nouvel outil :sweat_smile:

**Comment by qloridant** [comment]
Je connais pas ! Et je comprend ta crainte :)
Autre option Flower (gui sur celery). On toucherait pas au code existant sur la gestion des tâches

**Comment by qloridant** [comment]
Alors, après les tests : 
* flower fonctionne avec un cache. SI on démarre flower à un instant T on aura pas accès aux résultats passés, or les tâches tournent bien souvent la nuit.

J'ai donc testé et ajouté le package django_celery_results qui permet de stocker les résultats des taĉhes dans notre BDD
