### ISSUE TITLE
Anti-gaspi : j'ai mis en place cette action, backend

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4422]
https://www.figma.com/design/t4kFF08mjjXprQNF134ssu/ma-cantine?node-id=4064-106471&node-type=FRAME&t=m5WUdvXWxzXk8PVW-0

### Todo

- [x] modèle ResourceAction : #4497
- [x] SimpleHistory : #4541
- [x] API POST (créer & modifier une ResourceAction) : #4500
- [x] API GET (récupérer une Resource avec ses actions) : #4544

**Comment by raphodn** [comment]
Le modèle qui stock les actions anti-gaspi : `WasteAction`
Relation M2M through (pour avoir des timestamps) avec le modèle `Canteen` ? Et si l'utilisateur a plusieurs cantines ?

**Comment by raphodn** [comment]
- M2M entre WasteAction & Canteen
- utilisateur authentifié + cantine déjà sélectionnée (sous l'url ``/gaspillage-alimentaire

**Comment by raphodn** [comment]
Question de créer un modèle + générique ?
Si ces actions (j'ai mis en place, favoris, je ne suis pas intéressé) peuvent s'appliquer aux autres (futures) ressources

Django's Generic Foreign Keys
https://docs.djangoproject.com/en/5.1/ref/contrib/contenttypes/#generic-relations

On pourrait commencer simple avec un nom de modèle un peu générique `CanteenAction`
Et voir ensuite pour remplacer la FK vers WasteAction par un GFK.
Ou renommer WasteAction en BlogPost avec

**Comment by hfroot** [comment]
@raphodn merci !

Il nous manque les champs pour indiquer que la ressource est utilisé/mise en place par la cantine.

Pour le nom du modèle - tu penses quoi de `ResourceReview` pour ne pas mélanger avec le concept d'action comme on l'utilise pour `WasteAction` ?

> j'ai mis "resource" pour être générique, et permettre à terme de renommer WasteAction en Resource 👀

Pour le modèle qui n'existe pas encore de `Resource`, je pense qu'on peut pas simplement renommer `WasteAction` car il y a des champs dedans comme `waste_origins` et `effort` qui sont peut-être specifique aux actions anti-gaspi.

Je crois que les options pour un `Resource` sera si un [Abstract Base Class](https://docs.djangoproject.com/en/5.1/topics/db/models/#abstract-base-classes) ou un [Proxy Model](https://docs.djangoproject.com/en/5.1/topics/db/models/#proxy-models). Par contre j'ai pas bcp d'experience avec.

Je me pose la question alors de si le modèle proposé pourrait être migré plus tard si jamais on crée un classe parent de Resource ? Ou utiliser un generic key relation comme t'as évoqué plus haut.

... je me demande si on a assez d'info pour faire qqch generique ou est-ce que c'est mieux de le faire que pour `WasteAction` ajd et quand on retravaille les autres ressources on pourrait revoir le pb. Tu penses quoi ?

**Comment by raphodn** [comment]
oops merci d'avoir relevé cet oubli. je viens de rajouter le champ `is_done` du coup (et rajouter les prefix `is_` aussi)

**Comment by raphodn** [comment]
alors pour le nom.. :sweat_smile: 
- si on fait disparaitre WasteAction à terme, alors perso j'aime bien le terme Action et on aurait pas de conflit pour le (ré)utiliser
- Review ca me fait penser à un workflow de validation, non ? 
- ou alors ResourceFeedback ?

**Comment by raphodn** [comment]
ma crainte pour les GFK, c'est que ca va complexifier l'API (lecture, écriture), et aussi afficher ces données dans Metabase par exemple. 

je vais aller lire tes notes concernant les Resources, comment on pourrait tout mettre sous un même modèle, ca ne me gènerais pas par exemple d'avoir des fields spécifiques à certaines resources.

**Comment by hfroot** [comment]
J'aime bien `ResourceFeedback` :) J'ai proposé `Review` car on a déjà le modèle `Review` (évaluations du site). Mais feedback marche aussi.

**Comment by hfroot** [comment]
En re regardant le truc, est-ce que le concept de `rating` et des "actions" (mise en place) sont différents ? Car le rating est fait par utilisateur, et les actions par cantine (même si on garde q-m une trace de l'utilisateur). 

Je sais pas où tombe les concepts de favoris et pas intéressant...

**Comment by raphodn** [comment]
à terme : un modèle parent ``ResourceX + proxy models

ResourceAction / ResourceReview / ResourceFeedback / ResourceUsage / ResourceImplementation ?
