### ISSUE TITLE
Actions anti-gaspi : Action mis en place s'affiche sur mon affiche en ligne

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4423]
### Quoi

Afficher les actions mis en place par la cantine dans son affiche (section "Lutte contre le gaspillage")

### Todo

- [x] Backend : renvoyer les ResourceActions de la cantine : #4557
- [x] Frontend : afficher les actions sous forme de cards : #4558

**Comment by Tdauvet89** [comment]
Il reste : 
Sur l'affiche publique qui est accéssible depuis longlet mes cantines
1. Afficher l'action mis en place -> Récupérer la carte tel qu'elle est affiché dans l'outil
2. L'intégrer dans l'accordéon 
3. Ajouter un tag qui précise le nombre d'actions mis en place par la cantines

**Comment by Tdauvet89** [comment]
@raphodn voici la maquette et [lien figma](https://www.figma.com/design/t4kFF08mjjXprQNF134ssu/ma-cantine?node-id=4756-51521&node-type=frame&t=CWIX9OpbsGSRV2Nt-0)

Je te propose que dans un premier temps, on affiche les cartes les une à la suite des autres. 
Dans 1 mois un regarde la moyenne d'action mise en place par cantine et en fonction on ajuste le design (par exemple des acrtes plus petite, une pagination, autre) ou pas. 

![Image](https://github.com/user-attachments/assets/49f5aafa-7278-47bc-9ebc-38b98aec2e9e)

**Comment by raphodn** [comment]
Idées en vrac v2 : 
- réduire l'affichage des cards (enlever l'image, les chips)
- utiliser une list html vs des row/cols (accessibilité)

**Comment by Tdauvet89** [comment]
@raphodn voici mes retours

Page action 
- Mettre en point ? après mis en place
<img width="353" alt="image" src="https://github.com/user-attachments/assets/70647d55-aecc-4e58-8026-f3b4707b2e0a">

Changer le wording du bouton 
Etat 1 : l'action n'est pas encore mise en place
-> J'ai mis en place cette action
<img width="327" alt="image" src="https://github.com/user-attachments/assets/745ec4f8-b730-44d0-9a6a-7786d521587e">

Etat 2 : l'action est mise en palce dans X cantine(s)
-> Retirer cette action
<img width="299" alt="image" src="https://github.com/user-attachments/assets/a2261030-cdb3-4821-966c-d4314c3f688e">

**Comment by raphodn** [comment]
![image](https://github.com/user-attachments/assets/6a3ff351-94ad-4f0e-a81b-c24151b73f2b)

- Mis en place j'ai utilisé le même affichage que les titres à gauche, qui n'ont pas de point à la fin
- Ok pour le changement de wording

**Comment by Tdauvet89** [comment]
Ok ça marche. 
Après intégration des nouveau wording on peux mettre en ligne. Je te fais confiance, pas besoin de vérifier cela de mon côté.
