### ISSUE TITLE
[Bug]: CSM Staging - erreur 500 lors de l'enregistrement d'une nouvelle fiche action

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4439]
### Ton prénom

Thomas

### C'est de quel prio ?

{"label"=>"Bloquant, pas urgent (sprint prochain idéalement)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine-staging.cleverapps.io/cms/snippets/data/wasteaction/add/

### Quel type d'utilisateur est concerné ?

- [ ] Gestionnaire
- [X] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Je veux enregistrer une nouvelle fiche action sur le CMS staging

### Qu'est-ce que t'as bloqué ?

J'ai cliqué sur le bouton nouvelle fiche
Remplis un titre, un sous titre, les caractérisques et j'ai sauvegardé. 
Au clic sur le bouton, j'ai eu une erreur 500

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/fd46ef62-fa5d-42bf-b649-855992ea3c81">

### Tu utilises quel navigateur ?

{"label"=>"Chrome"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by raphodn** [comment]
Ok zut c'est lié à #4383

> psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "data_wasteaction_pkey"
DETAIL:  Key (id)=(1) already exists.

Je pense qu'en réimportant les données existantes, cela n'a pas pour autant mis à jour "l'index SQL de la table"

Une solution est de le faire manuellement du coup : https://stackoverflow.com/a/44113124

**Comment by Tdauvet89** [comment]
Infos complémentaires, je viens de refaire une création de fiche, je n'ai plus l'erreur 500. Le correctif est déjà déployé sur staging ?

**Comment by raphodn** [comment]
Non pas encore déployé, la PR est ici : #4440
J'ai l'erreur en local.
Mais peut-être qu'elle n'a lieu qu'une fois ?
