### ISSUE TITLE
Création Cantine : réparer bug redis, timeout variable rate limiting

### ISSUE THREAD

**Issue by qloridant** [betagouv/ma-cantine#4452]
# Contexte
La première étape de la création du SIRET demande le SIRET d'une cantine. Dès que le SIRET est renseigné nous requêtons la base SIRENE pour récupèrer des infos sur la cantine.

# Problème
Temps de chargement de cette requête sur les plateformes : 
* prod : plusieurs dizaine de seconde
* staging/local : quasi instantanée

# Solution

**Comment by qloridant** [comment]
Sur le redis de prod, on a une valeur anormalement haute pour notre SIRET_API_CALL_PER_MINUTE
On devrait avoir max 31, et on a actuellement 19299

```
notre_url.clever-cloud.com:notre_port> GET PROD_SIRET_API_CALLS_PER_MINUTE
"19299"
```

**Comment by qloridant** [comment]
En faite on ne met au temps de réinistialisation de la valeur :
* voir [doc méthode redis.set()](https://redis-py.readthedocs.io/en/stable/_modules/redis/commands/json/commands.html#JSONCommands.set)
* `TTL PROD_SIRET_API_CALLS_PER_MINUTE` renvoi -1 [(Key exists, but no associated expiration)](https://redis.io/docs/latest/commands/ttl/)

**Comment by hfroot** [comment]
@qloridant est-ce que t'as testé sur staging/demo ? Si ça ne marche pas non plus p-e contactes clever cloud, leur support est souvent reactif et aidant.

**Comment by qloridant** [comment]
Je les ai contactés !

**Comment by qloridant** [comment]
Le problème ne semble pas ré-apparaître.. Je ferme
