### ISSUE TITLE
CMS admin : migrer les fiches de demo vers prod

### ISSUE THREAD

**Issue by raphodn** [betagouv/ma-cantine#4464]
### Quoi ?

Suite à #4383 on souhaite maintenant migrer les données "actions anti-gaspi" crées dans l'environment de demo --> environment de prod.

### Comment ?

1. migrer les images wagtail (s'assurer que les id soient identiques...)
2. migrer les wasteactions (ignorer les revisions, modifier le user ?)

**Comment by Tdauvet89** [comment]
hello @raphodn, dis moi est-ce que les ressources seront quand mm conserver sur démo ?

**Comment by raphodn** [comment]
> hello @raphodn, dis moi est-ce que les ressources seront quand mm conservé sur démo ?

oui je vais dupliquer

**Comment by Tdauvet89** [comment]
Nickel, c'est très utile pour les démo, webinaire et autre. 
Merci 👍

**Comment by Tdauvet89** [comment]
Hello @raphodn @hfroot j'ai uploadé manuellement toutes les illustrations, c'était looooong 😅
Vous pouvez donc avancer sur l'ajout du sous menu "Fiches anti-gaspi" dans l'onglet M'améliorer.
