### ISSUE TITLE
Actions anti gaspi : front, j'ai mis en place cette action

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4478]
https://www.figma.com/design/t4kFF08mjjXprQNF134ssu/ma-cantine?node-id=4064-106471&node-type=FRAME&t=m5WUdvXWxzXk8PVW-0

### Quoi

- option pour indiquer qu'une action est fait pour 1+ cantines
- indication sur un fiche action si c'est fait et de quelle cantine

### Todo

- [x] affichage : si l'utilisateur est connecté, lister les cantines de l'utilisateur qui ont mis en place cette action : #4552
- [x] modification : permettre à l'utilisateur de modifier la/les cantines qui ont mis en place cette action : #4554

### Issues liées

- backend : #4422
- affiche : #4423

**Comment by Tdauvet89** [comment]
retours front à prendre en compte pour la mise en ligne : 
**En prio V1**
- Revoir la taille de la modale
- Trier les items par ordre alphabétique

Attention, car le noms des cantines sont souvent long, du coup niveau design ça risque de coincer.
**V2 améliorations**
- Ajouter un select/deselect all
