### ISSUE TITLE
API : bloquer la possibilité de TD via logiciel tiers

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4491]
Il y a p-e un logiciel qui l'utilise

Sur la plateforme, on a des garde-fous non bloquants (comme [cout par repas, nombre de satellites, etc](https://github.com/betagouv/ma-cantine/blob/staging/docs/matomo.md)) qu'on veut peut-être garder dans le flow.

Aussi ça invite les gens de découvrir la plateforme et les autres ressources.

Êvoqué pendant le seminaire 20 septembre 2024

**Comment by qloridant** [comment]
Décision prise de bloquer cette TD via API.
Communication en cours grâce à @Tdauvet89

**Comment by hfroot** [comment]
NB : c'est pas encore fait côté code @Tdauvet89

**Comment by Tdauvet89** [comment]
Oui, a faire le sprint pro alors :)

Coté communication, je re-colle les infos publiées sur Tchap
![image](https://github.com/user-attachments/assets/f6f9b3e4-9a6a-42ac-a89e-a70032662ebe)

**Comment by Tdauvet89** [comment]
@qloridant je viens de retrouver ce ticket qui est le doublon de celui crée hier
