### ISSUE TITLE
Problème avec la configuration brevo

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4493]
https://sentry.incubateur.net/organizations/betagouv/issues/95138/?query=is%3Aunresolved&referrer=issue-stream&stream_index=2

**Comment by qloridant** [comment]
Ca peut-être intéressant de merger #4501 pour faire le suivi de cette tâche Celery

**Comment by qloridant** [comment]
La mise à jour s'execute tous les jous. Elle charge les contacts qui n'ont pas été updaté depuis un certain temps (last_brevo_update).

Cette mise à jour se fait par batch. Brevo fait planter tout le batch s'il y a une erreur. 

L'erreur en questio est le fait de ne pas trouver un contact.
