### ISSUE TITLE
Bug photos non-chargées fiches actions

### ISSUE THREAD

**Issue by raphodn** [betagouv/ma-cantine#4535]
Suite à #4464

**Comment by raphodn** [comment]
ca a lieu sur quelles fiches ?

**Comment by hfroot** [comment]
j'ai simplement re-uploadé les images et ça marche maintenant. J'ai du faire que environ 3. Elles ont eu des thumbnails alors peut-être le téléversement n'a pas été terminé avant la fermeture de l'onglet ou qqch. Je pense il vaut pas le coup maintenant d'en regarder plus, mais si ça arrive encore on peut faire une investigation plus fine.
