### ISSUE TITLE
Topo ressources

### ISSUE THREAD

**Issue by raphodn** [betagouv/ma-cantine#4539]
deadline : mercredi
pour qu'on puisse finaliser jeudi
et presenter vendredi

**Comment by raphodn** [comment]
Helen m'avait montré la page "Ressources v2" dans le Notion qui contient déjà pas mal de choses !
https://www.notion.so/Ressources-v2-0-3ca9f4c8129f4e9db90da7dcedb740bf

J'ai créé une section Octobre 2024 en bas.

**Comment by raphodn** [comment]
Modèles actuels

|`data/models/BlogPost`|`data/models/WasteAction`|`data/models/VideoTutorial`|
|---|---|---|
|`title`|`title`|`title`|
|`tagline`|`subtitle`||
|`body` (RichTextUploadingField)|`description` (RichTextField)|`description` (TextField)|
|`display_date`|||
|`published`||`published`|
|`author`|||
|`tags` (M2M BlogTag)||`categories` (ChoiceArrayField)|
||`effort` & `waste_origins`|`video` & `subtitles` & `transcription`|
||`lead_image` (FK Wagtail image)|`thumbnail` (ImageField)|
|`creation_date`|`creation_date`|`creation_date`|
|`modification_date`|`modification_date`|`modification_date`|

**Comment by hfroot** [comment]
on peut fermer l'issu @raphodn ?
