### ISSUE TITLE
ajouter champs et questions au diagnostic

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#461]

**Comment by alemangui** [comment]
Les champs sont déjà présents, on a vu avec @valeriemerle 

Éventuellement on aura une deuxième story pour ajouter des champs dans la partie de diversification de protéines, mais pas encore confirmé (besoin d'informations de la part d'Erwan)

![image](https://user-images.githubusercontent.com/1225929/130595132-1b2bc4e8-9f55-4826-b940-13754572c195.png)
