### ISSUE TITLE
Tableau de bord > Synthèse : ajuster le design avec les retours #4400

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4618]
Intégrer les ajustements design du tickets #4400 sur cette vue 
![Image](https://github.com/user-attachments/assets/bf52c9ef-095c-4be0-9940-7b62a2cd575e)

**Comment by hfroot** [comment]
@Tdauvet89 dans #4400 les retours ont été fait sur la page synthèse mais ici le capteur est pour la page principale, est-ce que tu veux voir les changements sur les deux pages ?

En tout cas ça a pas mal bougé depuis, alors j'ai appliqué quelques retours mais pas tous, je propose :

![Image](https://github.com/user-attachments/assets/0aa824d3-ffe6-464c-91ec-c24c44b949c4)
