### ISSUE TITLE
[Bug]: Des utilisateurs ne reçoivent pas l'infolettre 

### ISSUE THREAD

**Issue by paulineeyherabide** [betagouv/ma-cantine#4621]
### Ton prénom

Pauline

### C'est de quel prio ?

{"label"=>"Bloquant, pas urgent (sprint prochain idéalement)"}

### Le(s) url(s) où tu vois le bug

NC

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [X] Équipe
- [X] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Que tous les utilisateurs avec un compte reçoivent l'infolettre

### Qu'est-ce que t'as bloqué ?

Certains utilisateurs ne reçoivent pas l'infolettre alors qu'ils ont créé leur copte sur ma cantine

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
Demande de plus d'infos fait via Tchap

**Comment by hfroot** [comment]
J'ai ouvert un ticket chez brevo

**Comment by hfroot** [comment]
Quelques points :

- les logs brevo sont supprimés après 7 jours alors faut regarder rapidement avec eux si ça arrive encore
- si une campagne est crée, et suspendu, et après des utilisateurs sont ajoutés à la liste, quand la campagne est envoyée elle sera envoyée que aux contacts déjà presents sur la liste avant la suspension de la campagne
- c'est possible d'envoyer une campagne vers que les nouveaux contacts : https://help.brevo.com/hc/en-us/articles/4411394977810-Send-to-new-contacts-resume-duplicate-and-archive-email-campaigns
