### ISSUE TITLE
[Gaspi] Changer les wordings gaspillage alimentaire par déchets alimentaires

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4627]
Suite à un ajustement de la lois européenne, Maiwen m'a demandé de changer tous les wording "gaspillage alimentaire" par déchets alimentaire". Cela est plus vaste. 

### Liste des changements à faire dans le tunnel 2

- [ ] Step 1 Période de mesure : Changer `Masse totale de gaspillage` par Masse totale des déchets alimentaires (incluant une fraction comestible assimilable a du gaspillage alimentaire et une fraction non comestible comme les os et les épluchures) ![Image](https://github.com/user-attachments/assets/9e4a1a26-5947-4100-9483-b6fc293374d7)

- [x] Step 1 Période de mesure : Changer Période de mesure de `mon gaspillage alimentaire` par Période de mesure de `mes déchets alimentaires` ![Image](https://github.com/user-attachments/assets/c3b2a6ec-6c6f-42e0-97ea-9712c8754d93)

- [x] Step 2 Masse totale de gaspillage : Changer le titre par Masse totale des déchets alimentaire ![Image](https://github.com/user-attachments/assets/a7822c0a-5a07-440d-bdf5-a1330681d685)

- [x] Step 2 Masse totale de gaspillage : Changer le label `Masse totale de gaspillage relevée sur la période de mesure` par `Masse totale des déchets alimentaires relevée sur la période de mesure` ![Image](https://github.com/user-attachments/assets/eff7bf2d-31f1-4d07-8666-520fee18edd9)

- [x] Step 3 Distinction du gaspillage en fonction de la source : Changer le titre par Distinction des déchets alimentaires en fonction de la source ![Image](https://github.com/user-attachments/assets/6c9e5f69-8248-4359-b814-2f9da658cf6e)

- [x] Step 3 Distinction du gaspillage en fonction de la source : Changer le label `Avez-vous trié votre gaspillage en fonction de sa source ?` par `Avez-vous trié vos déchets en fonction de leur source ?`  ![Image](https://github.com/user-attachments/assets/0adb5d80-ba0d-4c32-a267-2f65da30302d)

- [x] Step 3 Distinction du gaspillage en fonction de la source : dans le bandeau tips, changer `de gaspillage` par `des déchets` ![Image](https://github.com/user-attachments/assets/5ded51c8-4905-4b72-ba5a-55b9f8c9e549)

- [x] Step 3 Distinction du gaspillage en fonction de la source : dans le header, Etape suivante, changer `Gaspillage lié` par `Déchets alimentaires liés` ![Image](https://github.com/user-attachments/assets/920efd17-edbb-4a32-93cf-58d05370d418)

- [x] Step 4 Gaspillage lié aux excédents de préparation : Changer le titre par Déchets alimentaires liés aux excédents de préparation ![Image](https://github.com/user-attachments/assets/32e2ba04-8c0f-4653-9e9e-6f781ccde605)

- [x] Step 4 Gaspillage lié aux excédents de préparation : Etape suivante, changer `Gaspillage lié aux` par `Déchets alimentaires des` ![Image](https://github.com/user-attachments/assets/1a7cf591-575b-4098-9ae1-b436fcc9523c)

- [x] Step 4 Gaspillage lié aux excédents de préparation : Dans le label, changer `Masse de gaspillage pour les excédents de préparation` par `Masse de déchets alimentaire pour les excédents de préparation (en kg)` ![Image](https://github.com/user-attachments/assets/98d39db6-b54a-4ca0-a2e7-d5904b480090)

- [x] Step 4 Gaspillage lié aux excédents de préparation : Dans le label, le fait de préciser en Kg (optionnel) porte a confusion, on pourrait croire que je peux renseigner une autre mesure. Pour éviter tout problème, mettre la mesure attendu dans le label et laisser que Optionnel en gris. ![Image](https://github.com/user-attachments/assets/02ea7a8c-29a6-4963-bce2-75fd6ea4540d)

- [x] Step 5 Gaspillage lié aux denrées présentées aux convives mais non servies : Changer le titre par Déchets alimentaires des denrées présentées aux convives mais non servies ![Image](https://github.com/user-attachments/assets/bc8004e6-715c-4414-a823-a9ba2377a33a)

- [x] Step 5 Gaspillage lié aux denrées présentées aux convives mais non servies : Etape suivante : `Déchets alimentaire liés au reste assiette` ![Image](https://github.com/user-attachments/assets/c1721278-6660-4115-af99-227598f7b05e)

- [x] Step 5  Dans le label, changer `Masse de gaspillage pour les excédents de préparation` par `Masse de déchets alimentaire pour les excédents de préparation (en kg)` ![Image](https://github.com/user-attachments/assets/9646b5d2-46d7-450e-b558-d02265966160)
- [x] Step 5  Dans le label, le fait de préciser en Kg (optionnel) porte a confusion, on pourrait croire que je peux renseigner une autre mesure. Pour éviter tout problème, mettre la mesure attendu dans le label et laisser que Optionnel en gris. ![Image](https://github.com/user-attachments/assets/27fef69e-d6e9-4731-9bbb-019d230fd8c2)
- [x] STEP 6  Changer le titre par Déchet alimentaire liés au reste assiete ![Image](https://github.com/user-attachments/assets/034663fc-7254-417d-9c35-b754fdfa7c52)
- [x] STEP 6   Dans le label, changer `Masse de gaspillage pour le reste assiette` par `Masse de déchets alimentaire pour le reste assiette (en kg)` ![Image](https://github.com/user-attachments/assets/943f4e68-a489-4490-8f23-36f8d14fb3fe)
- [x] STEP 6  Dans le label, le fait de préciser en Kg (optionnel) porte a confusion, on pourrait croire que je peux renseigner une autre mesure. Pour éviter tout problème, mettre la mesure attendu dans le label et laisser que Optionnel en gris. ![Image](https://github.com/user-attachments/assets/dbb0251c-1d03-4d03-9fb9-dc27c80ac3b8)
- [x] STEP 4, 5, 6 changer le label Total du gaspillage de denrées comestibles par **Total des déchets alimentaires en Kg comestibles assimilable a du gaspillage alimentaire** ![Image](https://github.com/user-attachments/assets/0ab3a684-0a9d-4f0c-88dd-01dd34b1278a)
- [x] STEP 4, 5, 6 Dans le label, le fait de préciser en Kg (optionnel) porte a confusion, on pourrait croire que je peux renseigner une autre mesure. Pour éviter tout problème, mettre la mesure attendu dans le label et laisser que Optionnel en gris. ![Image](https://github.com/user-attachments/assets/a027e514-5eb0-40dd-8c72-f6facde66ff2)
- [x] STEP 4, 5, 6 changer le label Total du gaspillage de denrées non comestibles par **Total des déchets alimentaires en Kg non comestibles** ![Image](https://github.com/user-attachments/assets/f94ea01e-4d3c-4491-9945-c6a5fd026fb5)
- [x] STEP 4, 5, 6 Dans le label, le fait de préciser en Kg (optionnel) porte a confusion, on pourrait croire que je peux renseigner une autre mesure. Pour éviter tout problème, mettre la mesure attendu dans le label et laisser que Optionnel en gris. ![Image](https://github.com/user-attachments/assets/bb63289c-2c80-4639-a26b-b1464269408c)
- [x] Sur la synthèse, changer le titre Gaspillage alimentaire par Déchets alimentaires ![Image](https://github.com/user-attachments/assets/543d3c57-beb8-4453-926c-72c3526b34d1)
- [x] Sur la synthèse, changer le sous titre Mon gaspillage mesuré par Mes déchets alimentaires mesurées ![Image](https://github.com/user-attachments/assets/f580c5d6-b57a-4517-ac7f-9bd3c2fee568)

### Dans le tunnel 1

- [x] STEP 1 Changer Étape suivante : Mesure de mon gaspillage alimentaire par Mesure de mes déchets alimentaires ![Image](https://github.com/user-attachments/assets/40e9a5c3-3b47-4fa6-99b5-efaba4651099)
- [x] STEP 2 Changer le titre Mesure de mon gaspillage alimentaire par Mesure de mes déchets alimentaires ![Image](https://github.com/user-attachments/assets/15061f3b-b063-42a4-bc46-3630c11651c3)
- [x] STEP 2 Changer le label J’ai réalisé des mesures de mon gaspillage alimentaire par J’ai réalisé des mesures de mes déchets alimentaires incluant une fraction comestible (assimilable à du gaspillage alimentaire) et une fraction non comestible (os, épluchures, arêtes).  👉 Je trouve que ça fait un label très long, mettre un bandeau 

### Dans le tunnel 2 (?)

- [x] STEP 2 mettre un bandeau tips avec ce wording : Les mesures de mes déchets alimentaires incluent une fraction comestible (assimilable à du gaspillage alimentaire) et une fraction non comestible (os, épluchures, arêtes)
![Image](https://github.com/user-attachments/assets/b1247365-96c4-489b-aa4a-c7527a2d4a02)
- [x] Sur la Synthèse > graphique, Changer le label Excédents de préparation par Excédents de préparation dont stock
- [x] Sur la Synthèse > graphique, Changer le label Denrées non servies par Denrées présentées aux convives et non servies
- [x] Sur la Synthèse > graphique, Changer le label Reste-assiette par Restes assiettes
![Image](https://github.com/user-attachments/assets/a763f5c4-57b7-4d83-b206-881d81c30d2e)

**Comment by Tdauvet89** [comment]
Hello @raphodn voici les retours de wordings demandé par Maiwenn. Je suis a ta dispo si besoin

**Comment by raphodn** [comment]
est-ce qu'on écrit "non-comestible" ou "non comestible" ?

**Comment by Tdauvet89** [comment]
Oui c'est bien sans espace

**Comment by Tdauvet89** [comment]
OK sur staging, GO pour prod
