### ISSUE TITLE
[Gaspi] Sur la synthèse ajouter un graph qui montre les déchets commestibles et non commestibles en kg

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4628]
Additionner les valeurs renseignées dans le tunnels de mesure des déchets alimentaires, afin de faire un graph à baton

**Part de déchets alimentaires comestible **
= Excédents de préparation comestibles + Denrées présentées aux convives mais non servies comestibles + Reste assiette comestibles

**Part de déchets alimentaires non comestible **
= Excédents de préparation non comestibles + Denrées présentées aux convives mais non servies non comestibles + Reste assiette non comestibles

Afficher le graph devant le camembert 
![Image](https://github.com/user-attachments/assets/2e09d59a-d978-40f3-85d0-656b816b1f2c)

Utiliser le composant du DSFR https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants-beta/graphiques-charts

**Comment by raphodn** [comment]
Petit point bloquant : pas réussi de faire un BarChart simple avec la lib DSFR (!). Je continue de creuser (possible de faire des BarChart stacked, ou simple mais légende bizarre), j'ai rejoint le Slack de la communauté, et au pire on bascule sur un PieChart (comme l'autre graph)

**Comment by Tdauvet89** [comment]
@raphodn du coup, quelle solution a été mise en place ?

**Comment by raphodn** [comment]
Dans la PR liée à l'issue j'ai mis une capture d'écran ! Et sinon c'est visible en staging :)

**Comment by raphodn** [comment]
> J'ai un retour, dans la légende qui apparait en hover, peux-tu rajouter l'unité de mesure (Kg) stp.

ca marche, j'ai ouvert une PR : https://github.com/betagouv/ma-cantine/pull/4689
seul hic, faut attendre une nouvelle release de https://github.com/GouvernementFR/dsfr-chart (fonctionnalité pas dispo actuellement), avec un peu de chance ca arrivera soon ! sinon on peut contourner si ca prend trop de temps

**Comment by Tdauvet89** [comment]
On peut attendre, je trouve plus cohérent de le faire en mm temps. Et on n’a pas le couteau sous la gorge :)Le 25 nov. 2024 à 17:18, Raphaël Odini ***@***.***> a écrit :﻿

J'ai un retour, dans la légende qui apparait en hover, peux-tu rajouter l'unité de mesure (Kg) stp.

ca marche, j'ai ouvert une PR : #4689
seul hic, faut attendre une nouvelle release de https://github.com/GouvernementFR/dsfr-chart (fonctionnalité pas dispo actuellement), avec un peu de chance ca arrivera soon ! sinon on peut contourner si ca prend trop de temps

**Comment by raphodn** [comment]
Pour préciser, la fonctionnalité a été rajoutée à dsfr-charts, juste que ce n'est pas encore release (comme nos MEP ^^)

**Comment by Tdauvet89** [comment]
Ah autant pour moi, je n'avais pas compris. Du coup on parle d'attendre cbt
de temps ? Niveau deadline on peut attendre jusquau 7 janvier, après on
sera en pleine campagne et l'on avoir des retours sur ça.

Le lun. 25 nov. 2024 à 18:26, Raphaël Odini ***@***.***> a
écrit :
