### ISSUE TITLE
[Gaspi] Sur la synthèse, intégrer un lien qui ouvre le detail de l'XP reservation

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4649]
Dans le tunnel 1, nous avons (ou en cours) supprimé l'étape 5 Expérimentation réservation de repas (#4626) car cette expérimentation est terminé, mais Maiwenn veut garder une trace pour éviter tt problème avec un controle ou quoi ou caisse. 

Sachant que l'année dernière, nous avons des inspecteur qui nous ont audité dessus, on souhaite garder un accès pour l'utilisateur. 

Du coup, 
Sur la l'onglet synthèse du volet Gaspillage, en bas, ajouter un bouton tertiaire "En savoir plus sur l'expérimentation des réservation des repas de 2023"
Ce bouton ouvre une modale où l'on retrouve mot pour mot, le texte du tunnel setp 5

> Vous souhaitez réduire le gaspillage alimentaire dans votre établissement et générer des économies : la réservation de repas peut être une solution !
> 
> Pour évaluer ses effets sur le gaspillage alimentaire, la satisfaction de vos convives et le taux de fréquentation de votre établissement, nous vous proposons de participer à une expérimentation prévue par la loi climat et résilience.
> 
> Votre candidature à cette expérimentation vous permettra de mettre en place une démarche d’évaluation dont les résultats permettront de saisir le potentiel de la solution de réservation de repas.
> 
> Vous avez déjà mis en place une solution de réservation de repas ou souhaitez en adopter une ? Vous pouvez vous inscrire dès maintenant !
> 
> Vous serez amenés à répondre à des questions sur votre structure et la solution de réservation que vous aurez mise en place, ainsi qu’à transmettre des données relatives aux évaluations du gaspillage alimentaire, du taux de fréquentation et de la satisfaction des usagers sur une période de six mois.
> 
> Les inscriptions sont ouvertes jusqu’au 1er juillet 2023.
> 
> Les informations relatives aux conditions de mise en œuvre de l’expérimentation sont précisées dans [le guide pratique ](https://ma-cantine-staging.cleverapps.io/static/documents/Guide_pratique_XP_RESERVATION.pdf) .

![Image](https://github.com/user-attachments/assets/a27e88b9-364c-4cf9-afed-7006d32225aa)

**Comment by Tdauvet89** [comment]
Si c'est simple alors à conditionner sur l'année

**Comment by hfroot** [comment]
@raphodn comme exemple retrouve `v-model="valueExternalityPerformanceHtDialog"` dans le code, `OtherEgalimStep.vue`
