### ISSUE TITLE
[Bug]: Disparition d'un compte utilisateur avec une TD

### ISSUE THREAD

**Issue by Greta712** [betagouv/ma-cantine#4651]
### Ton prénom

Greta

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine.agriculture.gouv.fr/nos-cantines/111647--CENTRE%20DE%20RESSOURCES%20D'EXPERTISE%20ET%20DE%20PERFORMANCE%20SPORTIVE

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [ ] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Une utilisatrice me précise qu'elle n'a plus accès à son compte alors qu'elle avait référencé sa cantine et fait la télédéclaration. Je veux comprendre quel est le bug et comment sa cantine a pu disparaitre avec toutes les données

### Qu'est-ce que t'as bloqué ?

Je ne sais pas comment l'expliquer à l'utilisatrice

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by hfroot** [comment]
repondu par tchap

**Comment by hfroot** [comment]
Pour completer : l'utilisateur s'est trompé avec la plateforme démo, je ferme l'issu
