### ISSUE TITLE
Mettre le tableau de bord sur l’année en cours par défaut

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4666]

**Comment by hfroot** [comment]
Comme évoqué dans une réunion, je pense que c'est pas une bonne idée car en janvier 2025 quand on veut les gestionnaires remplissent la TD pour 2024, il les faudra naviguer vers l'année N - 1 pour le faire.

**Comment by Tdauvet89** [comment]
Yes je suis d'accord avec toi. Je pense qu'une amélioration des wordings peut aider. 
On peut killer ce ticket alors
