### ISSUE TITLE
Renommage du label "Ministère de tutelle"

### ISSUE THREAD

**Issue by Charline-L** [betagouv/ma-cantine#4702]
### Quoi
Remplacer le label “Ministère de tutelle” pour  “Administration générale de tutelle (ministère ou ATE) - hors fonction publique territoriale et hospitalière”

### Comment
À changer dans les pages : 
- [x] formulaire à l'inscription des cantines simples
- [x] formulaire inscription des cantines satelittes
- [x] dans la page de réglages d'une cantine
- [x] dans le dernier onglet de la TD "Établissement" 
- [x] dans le récapitulatif de la TD avant publication
- [x] dans le récapitulatif de la TD au format pdf
- [x] (discuté en daily) pas besoin de changer l'admin

**Comment by raphodn** [comment]
Comme discuté en standup, ce n'est peut-être pas nécessaire de faire ce changement dans le backend. On peut juste modifier l'affichage sur le frontend, plus simple et plus rapide :)

**Comment by Charline-L** [comment]
Dans le téléchargement pdf des TD il existe 2 templates : 
- un pour celles de 2024 et après
- un pour celles avant 2024 

J'ai modifié uniquement le template des TD du premier point, comme le changement se fait en 2024 mais à confirmer s'il faut les modifier pour les précédentes.

**Comment by Tdauvet89** [comment]
Ok nickel sur staging. GO pour prod 🙌 ![Image](https://github.com/user-attachments/assets/89707de5-b24a-4f54-9e8e-bc7f4fb59941)
