### ISSUE TITLE
Migration de la page Contact vers vue3

### ISSUE THREAD

**Issue by Charline-L** [betagouv/ma-cantine#4730]
## Description
Pour la passation il serait bien de tester la migration d'un formulaire avec un validateur pour en discuter avec Helen si besoin.

## Plan de dév
- [x] Migrer la page html
- [x] Changer la page dans les routers
- [x] Changer l'url dans le plan du site
- [x] Changer l'url dans le menu
- [x] Changer les urls en accès rapide
- [x] Changer le formulaire
- [x]  Ajouter le Matomo
- [x] Responsive
- [x] Accessible

## À tester
- [ ] Si je suis connecté le formulaire est pré-rempli avec mon adresse email et nom prénom
- [ ] Si je ne suis pas connecté le formulaire n'est pas ré-rempli
- [ ] Si j'envoi le formulaire et qu'un champ est manquant une erreur s'affiche au niveau du champ
- [ ] Si je renseigne une adresse email non valide un message d'erreur s'affiche à l'envoi du formulaire
- [ ] Si j'envoi le formulaire et que tout est correct un mail est envoyé à l'adresse renseignée dans clevercloud
- [ ] Si le formulaire est envoyé : un message de validation s'affiche en haut à droite
- [ ] Si le formulaire est envoyé : un évènement est créé sur notre Matomo
- [ ] Si le formulaire est envoyé : les champs sont réinitialisés
- [ ] Si le formulaire est envoyé : la page est scrollée "vers le haut"

**Comment by Charline-L** [comment]
Nouvelles infos : 
- j'ai pu avoir le droit admin sur Matomo pour pouvoir paramétrer les urls autorisées à envoyer des données. 
- j'ai donc autoriser uniquement celle agriculture.gouv.fr

**Comment by Charline-L** [comment]
@Tdauvet89 la fonctionnalité à tester sur staging : 

**Accès**
- [ ] La page est accessible depuis le menu et la page "Plan du site"
- [ ] L'url contient bien "/v2"

**Pré-remplissage :**
- [ ] Si je suis connecté le formulaire est pré-rempli avec mon adresse email et nom prénom
- [ ] Si je ne suis pas connecté le formulaire n'est pas pré-rempli

**Validation des champs :**
- [ ] Si j'essaye d'envoyer le formulaire et qu'un champ obligatoire est manquant une erreur s'affiche au niveau du champ
- [ ] Si j'essaye d'envoyer le formulaire avec une adresse email non valide un message d'erreur s'affiche

**Envoi :**
- [ ] Si tout est correcte un mail est envoyé à l'adresse "support-egalim@beta.gouv.fr"

**Une fois le formulaire envoyé :**
- [ ] Un message de validation s'affiche en haut à droite
- [ ] Les champs sont réinitialisés, sauf email et nom prénom si je suis connectée
- [ ] La page est scrollée "tout en haut"

**Modification qui a de l'impact sur une autre page :**
- [ ] Si utilisateur non connecté va sur une page vue3 qui demande une authentification (exemple importer des données) je suis bien redirigé vers la page de connexion

**Comment by Charline-L** [comment]
Pour information le Matomo arrive dans un prochain ticket : #4790

**Comment by Tdauvet89** [comment]
hello @Charline-L impossible de tester la page, j'ai une erreur 500
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/0729ce13-7cf7-47a0-99e2-5bcab7dc6cbd" />

**Comment by qloridant** [comment]
Je n'ai pas accès aux mail, donc je ne sais pas si les mails sont bien partis. 

ETQ utilisateur connecté, le formulaire s'est complètement réinitialisé après un premier envoi de message.
