### ISSUE TITLE
En période de TD rendre l’antisèche plus visible

### ISSUE THREAD

**Issue by Charline-L** [betagouv/ma-cantine#4750]
[🥃 Picardie](https://www.notion.so/En-p-riode-de-TD-rendre-l-antis-che-plus-visible-48d66a7da6c44621abb74594fb8111c9)

**Comment by Tdauvet89** [comment]
Trop bien, merci Charline, GO pour prod
<img width="838" alt="Image" src="https://github.com/user-attachments/assets/c96fb106-e10b-4d1c-9fd9-e2c4a7db5cba" />
