### ISSUE TITLE
modifications sites suite à la promulgation de la loi Climat et résilience

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#476]
Page mesures-phare
- [x] ajouter le commerce équitable dans le décompte des 50% pr les appros
- [x] viandes : En 2024, 60% de la viande et des produits de la pêche servis devront respecter les critères de qualité.
- [x] menu vege : 
"Les cantines de l’Etat et les universités qui proposent déjà plusieurs menus devront obligatoirement proposer une option végétarienne.

Les cantines scolaires devront composer un menu végétarien au moins une fois par semaine.

Les collectivités volontaires pourront expérimenter le menu végétarien quotidien et ainsi venir enrichir l’évaluation qui sera conduite par l’Etat."

- [x] Extension de l’obligation d’approvisionnement a hauteur d’au moins 50 % de produits durables et de qualité dont au moins 20 % de produits issus de l’agriculture biologique a la restauration collective privée à partir de 2025
"L’ensemble de la restauration collective, publique comme privée, a l’obligation de proposer 50 % de produits de qualité dont 20 % de produits bio à compter de 2022 pour le public, et d’ici 2025 pour le privé.
En 2024, 60% de la viande et des produits de la pêche servis devront respecter les critères de qualité."

- [ ] Article 61
Ajout d’une dimension climatique au plan national de l’alimentation et de la nutrition (PNAN)

Chapitre 2 : Développer l’agroécologie
Article 62 et 63
Trajectoire de réduction des émissions liées à l’utilisation des engrais azotés, avec déclenchement d’une taxe à partir de 2024 si les objectifs ne sont pas tenus

Article 64
Création d’un mécanisme d’alerte à destination des entreprises lorsqu’elles importent depuis des zones déforestées

Article 65
Compatibilité des objectifs du futur plan stratégique national avec les stratégies nationales en matière d’environnement

Article 66
Encadrement du label commerce équitable avec des conditions écologiques

**Comment by qloridant** [comment]
@Tdauvet89

**Comment by Tdauvet89** [comment]
Evoqué avec le BPAL la semaine dernière, Frederika est revenu vers moi avec tout un tas de changement à apporter sur la page comprendre mes obligations > Qualité des produits. 

https://ma-cantine.agriculture.gouv.fr/mesures-phares/qualite-des-produits/

Les modifications de la page sont listées dans le doc ci joint. 
Attention, les camemberts et les sigles sont à conserver ! 

[Page catégories de la loi.docx](https://github.com/user-attachments/files/17056110/Page.categories.de.la.loi.docx)

**Comment by Tdauvet89** [comment]
A intégrer dans le sprint prochain (lundi 23 septembre)

**Comment by hfroot** [comment]
@Tdauvet89 à la fin du document, parmi les ressources, il y a une nouvelle ligne "Pour plus d’informations sur les catégories de produits durables et de qualité et pour des explications concernant la catégorie « les produits acquis principalement sur la base de leurs performances en matière environnementale et d’approvisionnements directs » " - quel ressource devrait être lié à ça ?

**Comment by Tdauvet89** [comment]
Ce sont les 2 pdf des lignes suivantes : 
Télécharger le guide pratique CNRC de rédaction des marchés publics pour des appros durables à destination des acteurs de la restauration collective en gestion directe PDF – 2,4 Mo 
Télécharger le guide pratique CNRC à destination des acteurs de la restauration collective en prestation de service 

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/12c19271-c29a-4e1c-b10b-96a4b343f6e7">

La phrase de Frederika introduit les 2 ressources. Pour que ça soit plus clair, peux-tu rajouter un` : `à la fin stp.

Pour plus d’informations sur les catégories de produits durables et de qualité et pour des explications concernant la catégorie « les produits acquis principalement sur la base de leurs performances en matière environnementale et d’approvisionnements directs `:`
    - Téléchargez ....
    - Téléchargez ....

**Comment by Tdauvet89** [comment]
On a le GO de Frédérika pour pousser en production
