### ISSUE TITLE
[Bug]: Les données "qualité de produit" ne s'affichent pas pour la CS alors que les achats sont complétés par la CC

### ISSUE THREAD

**Issue by Charline-L** [betagouv/ma-cantine#4775]
### Ton prénom

Charline

### C'est de quel prio ?

{"label"=>"Gênant (sprint prochain si on peut)"}

### Le(s) url(s) où tu vois le bug

https://ma-cantine-demo.cleverapps.io/nos-cantines/1973--Restaurant%20d'entreprise%20NDAYAS

### Quel type d'utilisateur est concerné ?

- [X] Gestionnaire
- [ ] Équipe
- [X] Citoyen
- [ ] Administration
- [ ] Autre (à decrire avec le champ en dessous)

### Qu'est-ce que tu veux faire ?

Les données d'achats ont été enegistrées par la Cuisine Centrale, elles sont visibles dans le tableau de bord, mais elles ne s'affichent pas dans la page "Cantine" pour l'année en cours. 

Page cantine : https://ma-cantine-demo.cleverapps.io/nos-cantines/1973--Restaurant%20d'entreprise%20NDAYAS
Page tableau de bord : https://ma-cantine-demo.cleverapps.io/dashboard/1973--Restaurant%20d'entreprise%20NDAYAS

### Qu'est-ce que t'as bloqué ?

Je ne vois pas les informations que je cherche.

### Tu utilises quel navigateur ?

{"label"=>"Firefox"}

### Les détails de ce bug sont ouvert au grand public. Cocher ce cas pour confirmer que t'as pas ajouté des infos qui pourraient identifier les utilisateurs.

- [X] Il y a pas des données identifiantes.

**Comment by Greta712** [comment]
Merci

**Comment by Charline-L** [comment]
Le bilan provisioire de la CS était caché. Ce paramètre est activable dans la page "Editer mon affiche".
