### ISSUE TITLE
Bug : CSRF token pas valide dans un call vers /subscribeNewsletter

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#802]
Le call vers /subscribeNewsletter a échoué avec un Forbidden car le token CSRF n'était plus à jour. 

[Lien Kibana des logs](https://kibana-bxrbvv38clpvd6tvzpkz-elasticsearch.services.clever-cloud.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(columns:!(),filters:!(),index:'27286670-4916-11ec-8b3d-9d70ac09e556',interval:auto,query:(language:kuery,query:'message:%20subscribeNewsletter'),savedQuery:'Tout%20sauf%20loggedUser',sort:!(!('@timestamp',desc)))).

**Comment by alemangui** [comment]
Pas sur de la solution - peut être un edge case ? https://code.djangoproject.com/ticket/21704

**Comment by hfroot** [comment]
il y a quelques bad requests dans les derniers deux mois avec cet endpoint, mais pas de CSRF. Je ferme l'issu
