### ISSUE TITLE
Petites corrections de texte

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#901]
- "Si vous ne connaissez pas votre **part** de bio, produits durables, produits issues du commerce équitable, nous vous proposons un outil simple pour **les** calculer." -> il faut qu'on choisisse singulier ou pluriel
- "Visiter" pour les boutons/liens d'outils est un anglicisme ?

**Comment by Greta712** [comment]
J'ai une future utilisatrice qui m'a fait remarquer que dans le champ secteur d'activité ( à renseigner sur la page " Modifier ma cantine") il serait bien de distinguer le scolaire en indiquant scolaire 1er degré et scolaire 2nd degré. Ace jour, c'est scolaire et scolaire primaire
