### ISSUE TITLE
Suivi d'achat, partie 2

### ISSUE THREAD

**Issue by alemangui** [betagouv/ma-cantine#923]
- [x] Ajouter un champ pour la description de l'achat
- [x] Remplissage automatique des auto-diagnostics
- [x] Bouton "Valider et ajouter un nouveau"
- [ ] Revoir les _v-chips_ pour les catégories
- [x] Filtrage par période / par catégorie de produit / fournisseurs / labels
- [ ] Affichage de stats après filtrage
- [x] Triage (https://github.com/betagouv/ma-cantine/pull/1063)
- [x] Recherche (https://github.com/betagouv/ma-cantine/pull/1073)
- [x] Possibilité d'implémenter les contrôles de pagination de v-data-table (https://github.com/betagouv/ma-cantine/pull/1063)
- [ ] a11y pour le v-data-table (Bug Vuetify : https://github.com/vuetifyjs/vuetify/issues/9164). S'aider du du [slot item](https://vuetifyjs.com/en/api/v-data-table/#slots-item). Possibilité d'ajouter un tabindex avec : 
```javascript
this.$el.querySelectorAll(".v-data-table tbody tr").forEach((x) => (x.tabIndex = 0))
```
- [ ] [Caption](https://vuetifyjs.com/en/api/v-data-table/#props-caption) a11y
- [x] Supprimer un achat (https://github.com/betagouv/ma-cantine/pull/1048)

**Comment by hfroot** [comment]
Tu penses quoi du possibilité de supprimer un achat ?

**Comment by alemangui** [comment]
@hfroot ajouté :) Plus de détails ici : https://github.com/betagouv/ma-cantine/pull/910#discussion_r789025987

**Comment by hfroot** [comment]
> Bouton valider et ajouter un nouveau

#923

**Comment by hfroot** [comment]
> Filtrage, triage, recherche

Je pense qu'ils sont 'gratuits' si on utilise les fonctionnalités de vuetify, mais on devrait envoyer les infos sur tous les achats dès le back. Je suis tentée d'essayer cette option jusqu'à on a des problèmes avec le performance, qu'on pourrait identifier en regardant un tableur [celui-ci sur stats.data.gouv.fr](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=162&period=range&date=previous30#?idSite=162&period=range&date=previous30&category=General_Actions&subcategory=PagePerformance_Performance&popover=RowAction$3APagePerformance$3AActions.getPageUrls$3A$40$252Fmes-achats.)

SInon https://vuetifyjs.com/en/components/data-tables/#server-side-paginate-and-sort
