### ISSUE TITLE
(import massif) proposer aux utilisateurices de nous envoyer directement le fichier excel qu'iels ont eux avec leur email afin qu'on les recontacte

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#925]
<img width="756" alt="Capture d’écran 2022-01-20 à 14 25 27" src="https://user-images.githubusercontent.com/36134318/150347562-96ffb636-e10e-4655-a733-11ddb7e0eeb8.png">

contexte : on a eu un webinaire au Syndicat de la Restau co donc les grosses entreprises de concessions (Elior, Compass, Restoria, Dupont, API, Vitalrest, Sodexo...)
le but : leur présenter la plateforme
on imagine qu'iels vt tester et se créer un compte; on leur a expliqué l'import massif; on leur propose aussi de ns envoyer leur fichier.... 
pq pas qu'iels puissent le faire à l'envie sur le site directement ? 
j'y crois peu.....

**Comment by hfroot** [comment]
@JenniferStephan est-ce que tu veux qu'on construit ça, ou tu veux en discuter ensemble ?

**Comment by JenniferStephan** [comment]
c'était à discuter avec vs :)
j'ai remis sur l'agenda, les 2ème semaines de sprint, un affinage de 30min pour justement évoquer l'avancée du sprint et éventuellement les user stories qu'on peut embarquer et prioriser en plus de celles prevues sur le sprint
