### ISSUE TITLE
(expé gaspillage) ajouter les champs spécifique à l'expériementation "test d'une application de réservation de repas afin de réduire le gaspillage"

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#926]
<img width="821" alt="Capture d’écran 2022-01-20 à 14 33 35" src="https://user-images.githubusercontent.com/36134318/150348736-c8f02b9d-0fa2-4c55-a798-bbdeee93ca30.png">
<img width="469" alt="Capture d’écran 2022-01-17 à 15 34 26" src="https://user-images.githubusercontent.com/36134318/150348510-4d2c3a26-9212-4c39-8827-56bcf9b69f65.png">
<img width="472" alt="Capture d’écran 2022-01-17 à 14 53 34" src="https://user-images.githubusercontent.com/36134318/150348516-67adb9f9-81ac-4384-b16c-c21ad3560690.png">

figma autodiag : https://www.figma.com/file/Wy0JohuTd3zP9fTGERs5qq/Egalim-nouveauparcours?node-id=401%3A1486

- [ ] ajouter un texte introductif avant le champ libre "commentaires" ds l'encart gaspillage alimentaire : "Une expérimentation vous propose de tester et mesurer l’impact de la réservation de repas sur le gaspillage alimentaire. Si cette solution n’est pas encore mise en place dans votre établissement, vous pouvez vous déclarer volontaire et ainsi bénéficier d’un accompagnement sur cette expérimentation. 

NB : vous pouvez commencer l’expérimentation à la date souhaitée; un certain nombre de questions vous seront régulièrement posées afin de mesurer l’évolution." 
- [ ] ajouter option "je me déclare participant à l'expérimentation"
- [ ] ajouter un encart ressource "télécharger le guide de l'expérimentation"
- [ ] au clic sur le "je me déclare", afficher, sous en dropdown soit en modale : la liste des indicateurs suivants
- [ ] si on s'est déjà déclaré; mettre un lien "revenir à mes indicateurs" pour ouvrir la liste des indicateurs

- [ ] indicateurs descriptifs : 

<img width="465" alt="Capture d’écran 2022-01-20 à 14 37 37" src="https://user-images.githubusercontent.com/36134318/150349265-1e36ef9e-8a4e-4f54-884b-400ca0a009c6.png">

Afin d’évaluer et de mesurer les résultats de cette expérimentation, nous vous demandons de suivre et renseigner quelques indicateurs à 3 moments de l’expérimentation.
Date de la mise en place du mode de réservation (nb : pour 6 mois et fin au plus tard le 
31 décembre 2023) T0 :
Quel type de réservation de repas allez-vous mettre en place ? Décrivez-en le fonctionnement ?  
Par quel moyen allez-vous communiquer à vos convives sur la mise en place de 
réservation de repas ?
Un responsable du suivi de l’expé a été désigné
Un réglement à destination des convives a été rédigé

permettre ensuite la saisie d'indicateurs sur 3 temps : T0 / T1 = T0 + 3 mois / T2 = T0 + 6 mois
genre de "tabs" de navigation pr passer d'une période à l'autre ? 
Tous les 3 mois, revenez sur cette page afin de renseigner les taux de fréquentation 
de l’établissement.

<img width="405" alt="Capture d’écran 2022-01-20 à 14 40 02" src="https://user-images.githubusercontent.com/36134318/150349580-6e860985-fb41-437b-969d-23e0374db7e2.png">

**Comment by JenniferStephan** [comment]
doc de retour de Maiwenn donc modifs : https://docs.google.com/document/d/1T8j2kjkKukegN7yjg3FH6sKeCJQwzsd3/edit#

<img width="533" alt="Capture d’écran 2022-01-24 à 14 42 47" src="https://user-images.githubusercontent.com/36134318/150793681-852d008a-4ac9-4748-b5cf-9c17469daff3.png">
<img width="609" alt="Capture d’écran 2022-01-24 à 14 42 42" src="https://user-images.githubusercontent.com/36134318/150793686-096a2472-4b41-4cd0-9760-c18bbf6a78c5.png">
<img width="583" alt="Capture d’écran 2022-01-24 à 14 42 35" src="https://user-images.githubusercontent.com/36134318/150793689-9370e26a-04e6-4510-8235-64aa6065ac56.png">
<img width="569" alt="Capture d’écran 2022-01-24 à 14 42 24" src="https://user-images.githubusercontent.com/36134318/150793693-604d2521-1383-446d-88a1-ad57a43e3e82.png">

https://www.figma.com/file/Wy0JohuTd3zP9fTGERs5qq/Egalim-nouveauparcours?node-id=401%3A1486

- [ ] Vous souhaitez réduire le gaspillage alimentaire dans votre établissement et générer des économies : la réservation de repas peut être une solution !

Pour évaluer ses effets sur le gaspillage alimentaire, la satisfaction de vos convives et le taux de fréquentation de votre établissement, nous vous proposons de participer à une expérimentation prévue par la loi Climat et résilience.

Votre candidature à cette expérimentation vous permettra de mettre en place une démarche d’évaluation dont les résultats permettront de saisir le potentiel de la solution de réservation de repas.

Vous avez déjà mis en place une solution de réservation de repas ou souhaitez en adopter une ? Vous pouvez vous inscrire dès maintenant ! 

Vous serez amenés à répondre à des questions sur votre structure et la solution de réservation que vous aurez mise en place, ainsi qu’à transmettre des données relatives aux évaluations du gaspillage alimentaire, du taux de fréquentation et de la satisfaction des usagers sur une période de six mois. 
Les inscriptions sont ouvertes jusqu’au 1er juillet 2023.

Les informations relatives aux conditions de mise en œuvre de l’expérimentation sont précisées dans le guide pratique. 

- [ ] Je suis volontaire pour participer à l’expérimentation
- [ ] Avez-vous déjà mis en place une solution de réservation de repas ? si oui, demande de date
- [ ] Date de lancement de l’expérimentation (à partir de février – mars 2022 jusqu’au 1er juillet 2023) T0 : 
- [ ] Quel type de réservation de repas allez-vous mettre en place ? Décrivez-en le fonctionnement. 
- [ ] Comment comptez-vous communiquer sur la mise en place de la solution de réservation de
repas dans votre établissement auprès de vos usagers ?
- [ ] Un responsable chargé du pilotage du projet a été désigné. si oui, demander son nom / prénom / mail
- [ ] Un réglement à destination des convives a été rédigé
- [ ]  Un comité de pilotage du projet a été défini


**📊 Evaluons l’impact sur la fréquentation et satisfaction convive**

- [ ] Tous les 3 mois, revenez sur cette page afin de renseigner les taux de fréquentation 
de l’établissement.

- [ ] faire une sorte de tabulation où on peut remplir plusieurs indicateurs pour une période donnée : T0 / T0 + 3 mois / T0 + 5 mois

indicateurs : 
- [ ] Moyenne des pesées des excédents présentés aux convives et non servis (g/ convive) à T0 sur 20 déjeuners successifs 
- [ ] Moyenne des pesées des restes des assiettes exprimées (g/convive) à T0 sur 20 déjeuners successifs 
- [ ] Ratio de la part non comestible (g) rapportée à la part comestible (g)
- [ ] Moyenne des pesées des excédents de préparation (g/convive) - Si vous préparez les repas sur place
- [ ] Moyenne des pesées des pains jetés sur 20 déjeuners successifs (g/convive)
- [ ] Taux de fréquentation moyen à T0
- [ ] Tx d’utilisation de la solution de réservation
- [ ] Satisfaction moyenne convive (par questionnaire) (nb d'étoiles ?)
- [ ] Commentaire : (champ libre)

modèle de données des cantines : 

- [ ] ajouter en plus des options de gestion (concédée/directe) et management (central/site) champ : "Mode de liaison" avec comme option : "froide" ou "chaude"

**Comment by JenniferStephan** [comment]
[20211224-Décret solution de réservation- version à jour.docx](https://github.com/betagouv/ma-cantine/files/7932929/20211224-Decret.solution.de.reservation-.version.a.jour.docx)

**Comment by hfroot** [comment]
travail fait il y a longtemps
