### ISSUE TITLE
Différenciation des couleurs des étiquettes du blog

### ISSUE THREAD

**Issue by gauthierandre** [betagouv/ma-cantine#948]
Je ne sais pas si c'est normal, mais les deux titres sont similaires sur la couleur : témoignage et actualité dans l'exemple
<img width="1176" alt="Capture d’écran 2022-01-26 à 17 47 09" src="https://user-images.githubusercontent.com/85872944/151208938-f65b85f9-e48f-4066-a097-fa3367ea891e.png">
.

**Comment by hfroot** [comment]
Oui, c'est normale, entre guillemets - j'ai trouvé ça difficile de trouver assez des couleurs qui sont très différent, mais on peux trouver un autre :)

**Comment by gauthierandre** [comment]
J'en ai créée 4 : retour d'expérience / réglementation / actualité / témoignage. Pas sûr qu'il y en ait bcp plus. Admettons si on met "autre", ça fait 5.

**Comment by JenniferStephan** [comment]
oui mettons "autre" :) @gauthierandre si on se retrouve avec plein de "autre" ça ns permettra d'identifier une nouvelle étiquette :)

**Comment by hfroot** [comment]
@JenniferStephan est-ce qu'on peut identifier qu'on a besoin d'une nouvelle étiquette aussi bien si il y a plein d'articles sans une étiquette (sans ajouter une pour "autre") ? Je vois pas trop l’intérêt pour l'utilisateur une étiquette dédiée pour ça...

**Comment by alemangui** [comment]
Sinon on peut aussi vous laisser choisir la couleur depuis l'admin (vu que l'assignation est automatique en ce moment des duplicatas arrivent)
