### ISSUE TITLE
Permettre à la cantine d'afficher et communiquer sur papier et par email son % de bio et durables pour les convives

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#95]
pour le commerce équitable, la seule question : 
"est-ce que vous mettez en place une démarche pour l'acquisition de produits issus du commerce équitable ?" oui/non

**Comment by alemangui** [comment]
Je ne crois pas que cette question soit posée, mais l'issue date d'il y a quelques mois déjà. @JenniferStephan est-ce toujours d'actualité ?
