### ISSUE TITLE
(stats) propositions changement UX/UI

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#982]
- [ ] ajouter un filtre "communes" pr les PAT champ multiple
- [x] déplacer le bouton de recherche en le mettant en bas des filtres
- [x] ajouter filtre "secteur" avec champ multiple
- [ ] remplacer "statistiques" par "Chiffres-clé"

A FAIRE NIVEAU DESIGN : 

- [ ] enrober la page, en faire une landing spécifique avec msg clés pr notre persona gérant.e PAT/élu.e.s (@JenniferStephan)

**Comment by hfroot** [comment]
Les PATs peuvent avoir combien de communes max ? Est-ce que c'est un nombre raisonnable pour les utilisateurs a choisir eux-mêmes ?

**Comment by hfroot** [comment]
On a des discussions sur GH autour de la question de PAT/communes alors je ferme cet issu
