### ISSUE TITLE
identification des erreurs de remplissage de champs par les usagers et leur occurence pour essayer de prioriser des "boucliers" niveau produit

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/ma-cantine#983]

**Comment by hfroot** [comment]
j'ai parlé de ça avec quelques dévs dans beta. C'est vrai que ce type de tracking est populaire, mais pas trop fait chez beta. On pourrait imaginer faire quelque chose avec matomo

**Comment by qloridant** [comment]
@Tdauvet89 : a mettre ds Picardie
